vaadin/docs

versions.json
Let’s add this to the master branch, so that we can update the build scripts to use it and see if it actually works in production (even though we don’t yet have the other versions deployed).
I’m not sure if this belongs in the root folder of the repo, though, or if the file name is descriptive enough – maybe use `docs-versions.json`?
=> Add versions.json

articles/fusion/security/fusion-security-configuring.asciidoc
=> Fixed typo ('the the' -> 'the)

articles/theming/css-loading-order.asciidoc
Related to https://github.com/vaadin/flow/issues/9630.
=> Limitation of custom theme for styling the loading indicator

articles/fusion/routing/nested-views.asciidoc
Convert all headings to Title Case, and avoid using code formatting.
=> Fix heading case and formatting

.github/styles/Vocab/Docs/accept.txt, articles/guide/workflow/jetty-scaninterval.asciidoc, articles/guide/workflow/overview.asciidoc, articles/guide/workflow/setup-live-reload-hotswap-agent.asciidoc, articles/guide/workflow/setup-live-reload-jrebel.asciidoc, articles/guide/workflow/setup-live-reload-springboot.asciidoc
This PR contains a number of smaller fixes:
* Streamline the description of live reload and setup instructions
* Simplify section headers
* Clarify the pros and cons between server restarts and hotpatching
* Update external links and modernise (`PolymerTemplate` to `LitTemplate`)
* Fix https://github.com/vaadin/flow-and-components-documentation/issues/1401
* Align with Vale rules
=> doc: improve live reload documentation

articles/flow/cdi/basic.asciidoc
I swapped "about about" to "information about" and removed "tutorial-" from the link since it didn't load.
=> fix broken link and typo

articles/ce/going-to-production.asciidoc, pom.xml, src/main/java/com/vaadin/demo/ce/MyVaadinInitListener.java, src/main/java/com/vaadin/demo/ce/SpringBeanProvider.java
Update `ce-next` with latest changes and depend on CE snapshot.
Closes https://github.com/vaadin/collaboration-engine-internal/issues/512
=> CE: add config auto-detection and setDataDir

articles/guide/installing/frontend.asciidoc
V19 generates the .npmrc file with this flag.
=> Remove the --shamefully-hoist requirement for V19

.vale.ini
Before
```
$ vale ./articles/**/*.asciidoc
2002 errors, 5518 warnings and 0 suggestions in 481 files.
```
After
```
$ vale ./articles/**/*.asciidoc
2213 errors, 6109 warnings and 0 suggestions in 481 files.
```
The `BlockIgnores` and `TokenIgnores` regular expressions in the Vale config were causing incorrect / unnecesary modifications to input AsciiDoc files, and that lead to both valid text triggering errors (false positive) and invalid text not triggering errors (false negative).
There is no need to try to exclude special asciidoc syntax (like `image:` and `include:` macros and `link:` and `<<>>` links) for Vale.
Before linting the text, Vale passes the asciidoc files through an asciidoc processor and works on the HTML output. This means that all special asciidoc syntax that does not …
=> chore: reduce # of false positives and false negatives of Vale linter

.github/styles/Vocab/Docs/accept.txt, articles/fusion/application/accessing-backend.asciidoc, articles/fusion/quick-start-tutorial.asciidoc
This is based on direct user feedback. Ppl do not immediately realise that non-public endpoint methods are not exposed to TypeScript.
Related: https://github.com/vaadin/flow/issues/7681
=> fix: stress that endpoint methods should be public

docbuilder/build/docker-compose.yml, docbuilder/develop/docker-compose.yml, frontend/demo/all-example-resources.ts, frontend/demo/example-resources.ts, frontend/demo/init-flow-namespace.ts, frontend/demo/init.ts, webpack.docbuilder.js
Fixes https://github.com/vaadin/docs-app/issues/215
With the enviroment variable `DOCS_IMPORT_EXAMPLE_RESOURCES` set "true", this will make the app import all the generated Flow resources once the first rendered/live code example is encountered.
- (Rebuild the docbuilder image in case it's outdated)
- Add the following `.env` files with content `DOCS_IMPORT_EXAMPLE_RESOURCES="true"`:
- `docs/docbuilder/develop/.env`
- `docs/docbuilder/build/.env`
- under `docs-app`, run  `DOCS_IMPORT_EXAMPLE_RESOURCES="true" npm start`
=> feat: support Flow-only documentation

.github/styles/Vocab/Docs/accept.txt, articles/fusion/application/state-management.asciidoc
Adds a documentation page "State Management With MobX" under Fusion docs.
Closes #157.
=> docs(fusion): add page State Management With MobX

articles/framework/advanced/advanced-push.asciidoc
The old version leaks memory as listeners are effectively UI's.
See also: https://vaadin.com/forum/thread/18546873/messagebroadcaster-memory-leak
=> Fix the code example Broadcaster

articles/fusion/application/lit-element.asciidoc
Corrected two small typos related to `firstUpdated` lifecycle callback.
=> docs: fix typos in LitElement basics

articles/ds/customization/custom-theme.asciidoc
The example for using imports is 
```css
@import other-styles.css
```
However import doesn't work if you don't:
1. quote the file
2. add a ; at the end.
The format that works is 
```css
@import 'other-styles.css';     
```
=> Fix @import instructions

scripts/dspublisher-init.js
Fixes https://github.com/vaadin/docs-app/issues/249
=> fix: remove quotation marks from the generated .env file

articles/fusion/application/state-management.asciidoc, articles/fusion/tutorials/quick-start-tutorial.asciidoc
The problems were detected when running tests with Studio.
=> Update the quick start tutorial so all code samples can be copy-pastes without syntax errors.

dspublisher/docker-compose.build.yml, dspublisher/docker-compose.rmtarget.yml, package.json
Fixes https://github.com/vaadin/docs-app/issues/250
This PR adds a docker-compose file whose sole purpose is to remove the `docs/target` dir before running the license check. This is needed on Linux hosts, where the generated target files get owned by the root user and so can't be changed by the current user.
Also, any existing build artifacts under `dspublisher/out` get cleaned up on build.
=> fix: remove dspublisher generated files

dspublisher/deployment-example-docker/docker-compose.yml, dspublisher/deployment-example-docker/docs-app.Dockerfile, dspublisher/deployment-example-docker/nginx.conf
Fixes https://github.com/vaadin/docs-app/issues/246
This PR improves the deployment example generated for custom documentation projects:
- changed from light-server to more customizable nginx
- 404 page works as expected
- removed trailing slashes work out of the box
=> refactor: improve the dsp deployment example

src/main/java/com/vaadin/demo/domain/MessageService.java
It breaks currently Flow component demos, because when switching to Java examples, Spring tries to inject the dependencies of MyMessagePerister, although that's part of the CE docs and not related to component demos.
=> Make MessageService a class to fix Spring DI

articles/ce/tutorial.asciidoc
Remove deprection tag from V14 instructions. It notes that something has changed in V19, which should not be relevant in any way for a developer reading instructions for V14 specifically. The `latest` branch already has better instructions for this.
=> Remove deprication in V19 -tag from V14 instructions

articles/ds/customization/custom-theme-configuration.asciidoc
Update the sample for using a node asset
in css to be correct.
part of vaadin/flow#10426
=> fix: Correct sample for asset url in css

articles/ds/components/button/index.asciidoc, articles/ds/components/form-layout/index.asciidoc
The 'incomplete' icon appears next to a component in the navigation menu for those components that have neither Java nor TS examples in the new docs site. This is no longer the case for button and form-layout, so let's remove the icon for them.
=> fix: remove 'incomplete' icon for button and form-layout

articles/ds/components/board/index.asciidoc
The WiP note should be present on the pages that have either TS or Java examples missing. Board is missing Java examples, and therefore should have the WiP note.
=> fix: add WiP note to the board page

articles/flow/styling/custom-theme.asciidoc
* fix: clarify more on document.css usages in theming embedded components (#398)
=> CP clarify document.css usages in theming embedded components

articles/tools/mpr/configuration/custom-ui.asciidoc, articles/tools/mpr/configuration/legacy-theme.asciidoc, articles/tools/mpr/configuration/legacy-widgetset.asciidoc
Since all other annotations should be on the
AppShellConfiguration implementation class
in v19+ also MPR should only look for the
annotations on the configuration class.
part of vaadin/multiplatform-runtime#83
=> fix: Update how MPR annotations are given

articles/guide/production/index.asciidoc
As it is not on the roadmap at the moment.
=> fix: do not give false hope on bundle splitting

articles/flow/styling/lumo/icons.asciidoc
Fix the relative link between v14 and latest.
Currently it's https://vaadin.com/docs/v14/flow/latest/ds/foundation/icons
=> Fix the link between v14 docs and latest

articles/ce/collaboration-avatar-group.asciidoc, articles/ce/collaboration-binder.asciidoc, articles/ce/collaboration-message-list.asciidoc, articles/ce/developing-with-ce.asciidoc, articles/ce/going-to-production.asciidoc, articles/ce/tutorial.asciidoc
The current article titles are a bit long, and some of them are formatted like Java class names, which is discouraged in general.
This change makes the titles short enough to fit on one line, and avoids the class name formatting. That said, those particular articles have very different page headings vs the nav titles. I’m open for suggestions if we can bring them closer together.
(remove unnecessary `ifdef` macros at the same time, those are no longer needed)
=> Collaboration Engine article titles

articles/flow/tutorials/in-depth-course/components-and-layouts.adoc
The description previously read differently to what the screenshot said.
The file "GreetService" needs to be added to the `com.vaadin.tutorial.crm.ui` folder as well, not just `MainView`
This commit simply adds the words "and `GreetService`" to the text.
Simply adding two words to the tutorial.
=> Added "GreetService" to the files to be added to the ui folder

versions.json
Adds a new docs version entry to `versions.json` so that there will be a new `v20` branch that corresponds to docs for V19-20 and the `latest` branch will be for V21 (alpha) for now.
Internal Slack thread for context: https://vaadin.slack.com/archives/CQUQWJ4KU/p1621601391035000
=> feat: add new docs version entry to versions.json

articles/ce/overview.asciidoc
The image is blown up to 100% width right now and it is too big and pixelated. Try to keep original size.
=> CE: Pin avatar image size to it's absolute image size

articles/ce/topic-api.asciidoc, src/main/java/com/vaadin/demo/ce/TopicView.java
The partial examples don't compile if you simply omit parts of the code.
I inlined the partial examples so I could add a "return null" to in the
lambda expression.
=> CE: Fix topic-api examples

articles/guide/production/index.asciidoc
Suggest how to exlude `com.vaadin:vaadin-dev-server` in production mode for smaller application. Not that this is not the default in starter applications yet.
Related to vaadin/flow#10892
=> Suggest excluding vaadin-dev-server module in production mode

articles/flow/integrations/spring/spring-boot.asciidoc
Replace the link to /start with the now-prefered https://start.vaadin.com/. Also, remove the link to spring.io as there's no point in sending users away from our website.
=> Fix link to /start and remove ref to spring.io

articles/fusion/tutorials/in-depth-course/creating-views.adoc
`classes.css` was only available in `lumo-css-framework` v1 and v2 so the instructions don't work if that isn't updated. Since v3.0.10 there is `all-classes.css`. Currently if you follow the tutorial you will get `lumo-css-framework` v4.
This should also be cherry-picked to the `v20` branch.
=> Update import of Lumo CSS framework classes in Fusion tutorial

articles/ds/components/charts/java-api/svg-generator.asciidoc
Changes to the documentation page of the SVG generator feature that came up as a result of DX tests.
* add link to installation instructions for NodeJS
* add list of customizable options
* add a warning block and bold formatting to highlight closing the generator.
* add section to preview SVG image
* add catch clauses to code samples
=> Svg generator DX fixes

articles/fusion/advanced/components-definitions.asciidoc, articles/fusion/application/basics.asciidoc, articles/fusion/forms/appendix-vaadin-components.asciidoc, articles/guide/upgrading.asciidoc
- Adds a section to the Upgrading Guide explaining that the Template API (`<template>`) is no longer supported and renderer functions or the template renderer package should be used instead.
- Removes any mentions of Template API support
- Converts templates to renderer functions in the Fusion examples
Closes https://github.com/vaadin/web-components/issues/2100
Closes https://github.com/vaadin/web-components/issues/2113
=> docs: removing Template API

articles/ds/components/grid/index.asciidoc, frontend/demo/component/grid/grid-cell-focus.ts, frontend/themes/docs/components/vaadin-grid-cell-focus.css, frontend/themes/docs/components/vaadin-grid.css, src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java
Modifies the grid cell focus example to always show the focus outline for demonstration purposes, and adds a hint to the asciidoc about differences to the default behaviour.
Based on feedback from DX testing of the grid cell focus event.
=> docs: make focus outline always visible in grid cell focus example

frontend/demo/example-resources.ts, frontend/demo/session-verification.ts, src/main/java/com/vaadin/demo/DemoExporter.java
`setPollInterval` will keep the session alive while user is online.
If the user or server is not going online for more than 40 minutes, the tab will be reloaded once the server is available.
Logic won't be executed if the included example is not on the page.
=> fix: use timestamp to check if session is still alive

frontend/demo/component/badge/badge-highlight.ts
When binding a renderer to a component, it should be always assigned via Lit's `guard()` to prevent re-assigning on every render.
**Note:** Currently there is [a bug](https://github.com/vaadin/web-components/issues/2161) in Web Components that appears when re-assigning a Lit-based renderer without `guard()`.
=> fix: use guard() when assigning a renderer

frontend/demo/foundation/icons-preview.ts
- Crosses out the deprecated misspelled icons on [the icons preview page](https://vaadin.com/docs/latest/ds/foundation/icons/vaadin)
- Adds the `title` attribute to show a tooltip, e.g: `Since Vaadin 21, 'buss' is deprecated. Please use 'bus' instead.`
Fixes https://github.com/vaadin/web-components/issues/2108
=> feat: deprecate mispelled icons on icons preview page

articles/guide/upgrading.asciidoc
Cherry-picking #577 for v20.
Co-authored-by: Pekka Hyvönen <pekka@vaadin.com>
=> fix: Bump the required version of Spring Boot for v21 (#577)

articles/ds/components/button/index.asciidoc, frontend/demo/component/button/button-basic.ts, src/main/java/com/vaadin/demo/component/button/ButtonBasic.java, src/main/java/com/vaadin/demo/component/button/ButtonContrast.java, src/main/java/com/vaadin/demo/component/button/ButtonDisabled.java, src/main/java/com/vaadin/demo/component/button/ButtonError.java, src/main/java/com/vaadin/demo/component/button/ButtonIcons.java, src/main/java/com/vaadin/demo/component/button/ButtonImages.java, src/main/java/com/vaadin/demo/component/button/ButtonSizes.java, src/main/java/com/vaadin/demo/component/button/ButtonStyles.java, src/main/java/com/vaadin/demo/component/button/ButtonSuccess.java, src/main/java/com/vaadin/demo/component/button/ButtonTertiaryInline.java
Adds the following examples for Flow Button
- basics
- styles
- error
- size
- tertiary-inline
- success
- contrast
- icons
- images
- disabled
=> feat: add first batch of flow Button examples

frontend/demo/component/tree-grid/tree-grid-basic.ts, frontend/demo/component/tree-grid/tree-grid-column.ts, frontend/demo/component/tree-grid/tree-grid-rich-content.ts, src/main/java/com/vaadin/demo/component/treegrid/TreeGridBasic.java, src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java, src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java, src/main/java/com/vaadin/demo/domain/DataService.java
Currently all Flow TreeGrid examples are broken. This change fixes that by:
- fixing the `DataService.getManagers` and `DataService.getPeople` methods to use a mutable collection before using `removeIf`
- adding missing Flow JS imports
- passing the person ID into `getStaff`, instead of `getManagerId()`, which is always null for managers
=> fix: fix broken TreeGrid examples

articles/ds/components/tree-grid/index.asciidoc
Add a mention to an issue with the `scrollToIndex(index)` method in TreeGrid.
Related issue: https://github.com/vaadin/flow-components/issues/1016
=> mention the scroll to index issue in TreeGrid

articles/ds/components/select/index.asciidoc, src/main/java/com/vaadin/demo/component/select/SelectEmptySelection.java, src/main/java/com/vaadin/demo/component/select/SelectEmptySelectionCaption.java
There is an option in the Select component (Flow) to allow an empty item and also to set a caption for this empty item. No documentation exists for this feature. This PR adds a mention and example for both allowing the empty item and setting a caption.
Related: https://github.com/vaadin/flow-components/issues/1085
=> Add mention of select component's empty selection item and Java examples

src/main/java/com/vaadin/demo/domain/MessageService.java
It breaks currently Flow component demos, because
when switching to Java examples, Spring tries to
inject the dependencies of MyMessagePerister, although
that's part of the CE docs and not related to component demos.
cherry-pick: de26ce3f4194ebddf45b7324adc709a8b763479f
=> Make MessageService a class to fix Spring DI (#344)

articles/designer/designer-overview.asciidoc, articles/framework/tutorial.adoc, articles/testbench/chapter-testbench.asciidoc, articles/testbench/testbench-overview.asciidoc, articles/testbench/testbench-quickstart.asciidoc, articles/testbench/testbench-tutorial.asciidoc
Google search of Vaadin-related queries often provides outdated (and hence misleading) v7, v8, and v10 results for Vaadin tutorial. 
This PR clarifies the used Vaadin version for v7 docs. This will hopefully affect Google search results so that the tutorials of LTS and latest are promoted. But even if that doesn't happen, clarifying the tutorial version should reduce the likelihood of misleading users.
=> Make v7 tutorial version more explicit

frontend/demo/component/grid/grid-column-borders.ts, frontend/demo/component/grid/grid-context-menu.ts, frontend/demo/component/grid/grid-no-border.ts, frontend/demo/component/grid/grid-no-row-border.ts, frontend/demo/component/grid/grid-row-reordering.ts, frontend/demo/component/grid/grid-row-stripes.ts, frontend/demo/component/grid/grid-wrap-cell-content.ts
1. Updated the renderers to not use self-closing tags which is not correct for Custom Elements
2. Updated the grid context menu example to remove non-null assertion (type cast is enough).
=> style: fix some lit-plugin warnings

articles/guide/contributing/overview.asciidoc
Languages always begin with a capital letter in English.
=> Fix 'english' not beginning with a capital letter

src/main/java/com/vaadin/demo/component/button/ButtonDisableLongAction.java
This PR changes the ButtonDisableLongAction example to utilize the `button.setDisableOnClick(true);` feature (this is the Java example of that particular feature).
=> docs: update a button example to use disableOnClick

articles/flow/tutorials/in-depth-course/login-and-authentication.adoc
Documentation code snippet had `context.getAuthentication().getPrincipal()` called repeatedly even though it was already in a variable.
Improves documentation code snippet, nothing else.
=> Remove repetitive re-fetching of principal in docs

articles/ds/components/notification/index.asciidoc, frontend/demo/component/notification/notification-basic.ts, frontend/demo/component/notification/notification-contrast.ts, frontend/demo/component/notification/notification-position.ts, frontend/demo/component/notification/notification-primary.ts, frontend/demo/component/notification/notification-static-helper.ts, frontend/demo/component/notification/notification-success.ts, src/main/java/com/vaadin/demo/component/notification/NotificationStaticHelper.java
Adds new section for the Notification.show helper method, now that it is available in both Java + TS. Also updated the basic TS examples to use the helper.
I decided to introduce a new section for this. Although the helper is used in several other examples I though it would be easier to discover this way. Also was easier to explicitely hint at the support for Lit templates in the TS example.
Related to: https://github.com/vaadin/components-team-tasks/issues/593
=> docs: add section for Notification.show helper

articles/ds/components/menu-bar/index.asciidoc, frontend/demo/component/menubar/menu-bar-internationalization.ts, src/main/java/com/vaadin/demo/component/menubar/MenuBarInternationalization.java
Adds a new internationalization section for the menu bar component. Currently only a single aria-label can be localized so I noted that fact in the docs. I also decided to not render the examples, as most users will not be able to make out the difference (if an overflow button is visible, then it has a different aria-label).
Related to https://github.com/vaadin/components-team-tasks/issues/594
=> docs: add menubar section for internationalization

articles/ce/developing-with-ce.asciidoc, articles/ce/going-to-production.asciidoc, articles/ce/overview.asciidoc, articles/ce/topic-api.asciidoc
Related Slack discussion: https://vaadin.slack.com/archives/C01580Y9FLJ/p1632812666025900
=> Remove superfluous "since V14.7" from CE pages

articles/flow/upgrading/legacy-component-pack.asciidoc
- lists out incompatible/changed API per each legacy component class
- lists out unsupported API per each legaacy component class and instructions how to migrate
Closes vaadin/flow-legacy-components#72
=> feat: introduce API migration instructions

articles/fusion/tutorials/in-depth-course/login-and-authentication.adoc
The default permission for endpoint used to be `@PermitAll`, it changed to `@DenyAll` by default, so updating the tutorial accordingly.
=> fix: add missing @PermitAll to the crm auth turorial code example

articles/flow/guide/start/gradle.asciidoc, articles/shared/guide/configuration/_maven.asciidoc, articles/shared/guide/install/_index.asciidoc, articles/shared/guide/production/_index.asciidoc
Introduce `pnpm.global` config parameter to enable using globally installed pnpm.
Default is false, and the pinned supported version of pnpm tool is used.
Related-to https://github.com/vaadin/flow/issues/11730
=> fix: Use pinned supported pnpm version by default

articles/fusion/advanced/client-middleware.asciidoc, articles/fusion/advanced/connection-indicator.asciidoc, articles/fusion/advanced/typescript-client.asciidoc, articles/fusion/tutorials/in-depth-course/installing-and-offline-pwa.adoc, articles/fusion/tutorials/in-depth-course/login-and-authentication.adoc, frontend/demo/component/custom-field/custom-field-basic.ts, frontend/demo/component/select/select-complex-value-label.ts, frontend/demo/component/select/select-custom-renderer-label.ts, frontend/demo/component/select/select-presentation.ts, frontend/demo/fusion/authentication/auth.ts, frontend/demo/fusion/authentication/handle-session-expiration/connect-client.ts, frontend/demo/fusion/authentication/handle-session-expiration/login-overlay.ts, frontend/demo/fusion/authentication/login-view.ts, frontend/demo/fusion/errorhandling/catch-error.ts, frontend/demo/fusion/errorhandling/catch-invalid-args.ts, frontend/demo/pwa/offline/ts-view-with-endpoint.ts, package.json, pom.xml
- update the fusion imports from `@vaadin/flow-frontend` to `@vaadin/fusion-frontend`.
- update select component imports
- add `any` type to param in catch statement
=> fix: update frontend errors for updating to 22alpha5

frontend/demo/foundation/include-module.ts, frontend/demo/foundation/lumo-tokens.ts, frontend/demo/foundation/material-tokens.ts
Removes the Polymer legacy adapter from the Foundation docs, which was used to access the dark theme CSS, and uses CSSResults instead which are now exported by the Lumo style modules in V22.
=> chore: remove polymer legacy adapter in foundation docs

articles/ds/components/crud/index.asciidoc
The PR is the follow-up on the internal discussion where it was agreed that it would be more clear if the “Disabling sorting and filtering” example in the "Sorting & Filtering" section on the CRUD page was moved to a separate sub-section.
Otherwise, it is quite confusing that the first example in the "Sorting & Filtering" section doesn’t actually allow sorting and filtering items and, instead, demonstrates how it would look like if sorting and filtering were disabled.
=> chore: disable CRUD sorting and filtering in separate section

articles/ce/advanced/topic-api.asciidoc
This adds a TIP about using `EntryScope` when adding values to a topic.
=> CE: Tip about entry scope for topic data

articles/ds/foundation/icons/index.asciidoc, frontend/demo/component/badge/badge-highlight.ts, frontend/demo/component/badge/badge-icons-only-table.ts, frontend/demo/component/badge/badge-icons.ts, frontend/demo/component/board/example-indicator.ts, frontend/demo/component/notification/notification-basic.ts, frontend/demo/component/notification/notification-contrast.ts, frontend/demo/component/notification/notification-error.ts, frontend/demo/component/notification/notification-keyboard-a11y.ts, frontend/demo/component/notification/notification-position.ts, frontend/demo/component/notification/notification-primary.ts, frontend/demo/component/notification/notification-retry.ts, frontend/demo/component/notification/notification-static-helper.ts, frontend/demo/component/notification/notification-success.ts, frontend/demo/component/notification/notification-undo.ts
Based on https://github.com/lit/lit/issues/1986, the `.js` is required by Lit.
=> fix: use .js extension for Lit decorator/directive imports

articles/ds/foundation/icons/index.asciidoc, frontend/demo/component/badge/badge-highlight.ts, frontend/demo/component/badge/badge-icons-only-table.ts, frontend/demo/component/badge/badge-icons.ts, frontend/demo/component/board/example-indicator.ts, frontend/demo/component/notification/notification-basic.ts, frontend/demo/component/notification/notification-contrast.ts, frontend/demo/component/notification/notification-error.ts, frontend/demo/component/notification/notification-keyboard-a11y.ts, frontend/demo/component/notification/notification-position.ts, frontend/demo/component/notification/notification-primary.ts, frontend/demo/component/notification/notification-retry.ts, frontend/demo/component/notification/notification-success.ts, frontend/demo/component/notification/notification-undo.ts
Cherry-pick https://github.com/vaadin/docs/pull/901 to v21
=> fix: use .js extension for Lit decorator/directive imports (v21)

articles/ds/components/accordion/index.asciidoc, articles/ds/components/avatar/index.asciidoc, articles/ds/components/button/index.asciidoc, articles/ds/components/checkbox/index.asciidoc, articles/ds/components/combo-box/index.asciidoc, articles/ds/components/confirm-dialog/index.asciidoc, articles/ds/components/context-menu/index.asciidoc, articles/ds/components/crud/index.asciidoc, articles/ds/components/custom-field/index.asciidoc, articles/ds/components/date-picker/index.asciidoc, articles/ds/components/date-time-picker/index.asciidoc, articles/ds/components/details/index.asciidoc, articles/ds/components/dialog/index.asciidoc, articles/ds/components/email-field/index.asciidoc, articles/ds/components/form-layout/index.asciidoc, articles/ds/components/grid-pro/index.asciidoc, articles/ds/components/grid/index.asciidoc, articles/ds/components/input-fields/index.asciidoc, articles/ds/components/list-box/index.asciidoc, articles/ds/components/menu-bar/index.asciidoc, articles/ds/components/number-field/index.asciidoc, articles/ds/components/password-field/index.asciidoc, articles/ds/components/progress-bar/index.asciidoc, articles/ds/components/radio-button/index.asciidoc, articles/ds/components/rich-text-editor/index.asciidoc, articles/ds/components/select/index.asciidoc, articles/ds/components/text-area/index.asciidoc, articles/ds/components/text-field/index.asciidoc
Restores cross-references in component docs. Note that there are still some remaining TODOs that can only be resolved after porting the foundation docs, or porting certain features.
=> docs: restore cross-references in component docs

articles/ds/components/charts/java-api/css-styling.asciidoc
The instructions to add the annotations needed for using the styled mode on a Chart is inlined on the text, which can be a little confusing.
Add the instructions on a code block bellow the text.
=> docs: make loading CSS instructions more clear

articles/ds/figma.asciidoc
Fixes links for Vaadin Charts + Vaadin Icons Figma documents, which were reversed.
=> fix: fix links to Figma documents

articles/ds/figma.asciidoc, articles/ds/material-theme-demo.asciidoc, articles/ds/overview.asciidoc, articles/index.asciidoc
- adds Figma page
- adds Material Theme demo link
- removes WIP hints for Design System from root index page
=> docs: port Figma docs to 14

src/main/java/com/vaadin/demo/component/menubar/MenuBarDisabled.java
Use `setEnabled` API to disable menu bar items.
Fixes https://github.com/vaadin/web-components/issues/3203
=> docs: use setEnabled API in menu bar disabled demo

articles/framework/portal/portal-osgi.asciidoc
gwt-elemental is now needed to be activated separately as it is its own bundle and not static part of vaadin-shared, see
https://github.com/vaadin/framework/pull/12416
=> Update bundle loading sequence

articles/flow/advanced/application-lifecycle.asciidoc
Vaadin Flow requires Java Servlet API 3.1 (JSR-340) or newer: https://github.com/vaadin/platform/releases/tag/22.0.0
=> Fix Servlet version

articles/upgrading/index.adoc
The new [upgrade page](https://vaadin.com/docs/latest/upgrading) momentarily shows all the upgrade content before they are hidden. This PR removes quotation marks from attribute selectors in an attempt to fix this.
=> Fix Upgrade page flicker

articles/flow/tutorial/project-setup.adoc
Latest was using `prerelease` when we had separate V21 and latest branches. Now it needs to point to latest.
=> Use `latest`, not `prerelease` for Flow tutorial download

articles/ds/upgrading.asciidoc
As described in https://github.com/vaadin/web-components/issues/3275#issuecomment-1014517409, one regression that we didn't consider when switching to slotted `<input>` is the fact that it breaks setting `tabindex` attribute with positive value. This PR is intended to document it.
- Docs
=> docs: add tabindex limitation to upgrading guide

articles/flow/integrations/quarkus.asciidoc
TestBench requires guava 31.0.1-jre, but Quarkus BOM pins a prior version.
The more recent version must be added in project POM dependency management section.
=> Added info for TestBench 8/Quarkus guava dependency conflict

articles/ds/components/form-layout/index.asciidoc
FormLayout docs have a warning about accessibility issues with FormItem. As these issues have now been fixed, this PR removes the warning.
=> Removal of accessibility warning for FormLayout

articles/upgrading/styling/_21-22.adoc
Links to the "Input field components" section in the Upgrade Guide are still broken. This is yet another attempt to fix them.
=> Yet another attempt to fix links to Input Field Components section

.github/styles/Vocab/Docs/accept.txt, articles/ds/components/map/index.asciidoc, frontend/demo/component/map/map-theme-borderless.ts, src/main/java/com/vaadin/demo/component/map/MapThemeBorderless.java
Adds a theme variants section to the map component docs, demonstrating the borderless theme variant.
Depends on https://github.com/vaadin/flow-components/pull/2694
=> docs: add theme variants section for map component

articles/routing/defining.asciidoc, articles/routing/nested-views.asciidoc, articles/routing/url-parameters.asciidoc
Updated the Hilla routing doc to remove mentions of server-side routes, and to add an example of accessing route parameters.
=> Remove references to server side routing

articles/upgrading/index.adoc, frontend/demo/upgrade-tool/upgrade-tool.ts
This will enable us to share the upgrade settings for specific versions and configurations more easily. It will also preserve the configuration upon navigating forward and then backward to the tool again.
=> Store update config in URL

frontend/demo/session-verification.ts
Seems there's a difference in how the V23 and V14 versions respond to the current server online check:
https://vaadin.com/docs/latest/vaadin/index : 200
https://vaadin.com/docs/v14/vaadin/index : 404
Change the path to something that returns 200 on V14
=> fix: change server check path for V14 session verification

articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
V14 does not have class AppShellRegistry, 
so this is not an issue.
=> Remove mention of AppShellRegistry::getTitle

articles/flow/guide/quick-start.adoc
Let's test removing the gitpod link for few weeks to see whether it has any positive or negative changes on the performance of this page. I speculate that the gitpod link might actually be distracting as users are not used to online IDEs in general, and on VS Code-like IDEs in particular.
=> Remove link to gitpod from quick start tutorial

src/main/java/com/vaadin/demo/component/map/MapBasic.java, src/main/java/com/vaadin/demo/component/map/MapEvents.java, src/main/java/com/vaadin/demo/component/map/MapLayers.java, src/main/java/com/vaadin/demo/component/map/MapMarkers.java, src/main/java/com/vaadin/demo/component/map/MapSources.java, src/main/java/com/vaadin/demo/component/map/MapThemeBorderless.java, src/main/java/com/vaadin/demo/component/map/MapViewport.java
Some Map component samples were importing `com.vaadin.demo.flow.routing.Route` instead of `com.vaadin.flow.router.Route`.
=> Fixed incorrect Route import in Map samples.

dspublisher/theme/global.css, dspublisher/theme/header.ts
We are adding a new menu item "Support" to Hilla website. I know `overflow-x: auto` is a lousy mobile nav workaround but hope it is ok for now.
=> Add support menu item to hilla nav

articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
The version number in the asciidoc doesn't get updated automatically.
Another option would be to use `...change the Vaadin version to {moduleMavenVersion:com.vaadin:vaadin}` but then the version would automatically get bumped to the next major (24, sometime in the future) together with the docs project.
=> docs: remove fixed vaadin version from the upgrade guide

articles/advanced/endpoints-urls.asciidoc
Updating documentation for endpoint URL configuration to reference current `vaadin.endpoint.prefix` property instead of previous `vaadin.connect.prefix`.
=> docs: Fix endpoint mapping property name

src/main/java/com/vaadin/demo/component/customfield/DateRangePicker.java, src/main/java/com/vaadin/demo/component/customfield/MoneyField.java
Updated Java examples for `CustomField` to use correct `querySelector` for setting `aria-label` on the slotted input.
TS examples have been updated previously but Java examples still used old, pre-V22 DOM structure.
=> fix: update aria-label logic in Java examples

articles/ds/components/charts/configuration.asciidoc
This PR attempts to improve the plot options documentation in several ways:
- improve introduction to clarify that this is what you want if you are trying to customize how series are displayed
- clarify distinction between setting options on chart vs. series, use more appropriate code snippets
- cleanup section about different types of plot options, use a table for better overview, and add links to API docs
- add some practical examples (snippets only) that came up in real-world support cases, to give an idea what's possible. Addresses this BFP: https://github.com/vaadin/flow-components/issues/2669
- remove "other options" section that explained random options, half of which were wrong or do not exist
This also adds some improvement to the "Legend" section, to clarify how the color dot …
=> docs: improve chart plot options documentation

articles/shared/guide/install/_node-js.asciidoc
The shared document is using an id that is already used in` articles/flow/configuration/node-js.asciidoc`. There is also one erroneous display of the filename
=> Fix Node installation page

articles/ds/components/charts/configuration.asciidoc
Looks like this warning caused AWS build to fail.
```
2022-04-14T06:52:50.076Z [WARNING]: error Broken cross reference [1m/ds/components/charts/basic-use.asciidoc[0m in ds/components/charts/configuration.asciidoc
```
=> docs: fix broken charts cross-reference

articles/ds/components/dialog/index.asciidoc
We missed to add a note indicating that new features are only supported in pre-release.
=> docs: add since admonitions to dialog

articles/ds/components/charts/data.asciidoc
Adds a section about the charts' turbo mode that explains what it is and how it can be configured or disabled.
=> docs: charts turbo mode

src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightEditableCells.java, src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightReadOnlyCells.java
Fixed typo in the route for newly added GridPro theme variants examples.
=> fix: use correct route for GridPro theme demos

dspublisher/dspublisher-scripts.js
Extracted from https://github.com/vaadin/docs/pull/1341
Adds scripts for running DSP commands that use the NPM package release (instead of the Docker image) without yet changing the `package.json` scripts or the DSP documentation. This allows for testing the feature without it yet being publicly available for DSP users.
Testing:
start: `node dspublisher/dspublisher-scripts.js --develop`
build: `node dspublisher/dspublisher-scripts.js --build`
clean: `node dspublisher/dspublisher-scripts.js --clean`
=> feat: add scripts for running DSP commands

articles/upgrading/essential-steps/index.adoc
This link mentions a guide that is not really a guide; it's a marketing page. And in any case, in the point just above that, we are also linking to the migration guides of versions prior to V14 (which include V7 and V8).
=> Remove link to vaadin.com/vaadin-8

frontend/demo/init-flow-components.ts
https://github.com/vaadin/flow-components/commit/0edc42b5a25bdb5327c4f0e871289bb5b0c75f04 introduced `contextMenuTargetConnector.js` which was missed to be manually imported in the docs likewise `contextMenuConnector.js`.
Fixes #1376
=> fix: import contextMenuTargetConnector manually

articles/framework/tutorial.asciidoc
For whatever reason, googling "Vaadin tutorial" still delivers users to the V8 tutorial. This PR adds a warning about v8 end of life, and encourages users to go the latest quick-start guide.
=> Add warning about V8 end of life

articles/flow/integrations/quarkus.asciidoc
Pro components' jandex index is not included in vaadin-core-jandex dependency and the need for manually adding the vaadin-jandex dependency have not been mentioned anywhere.
Fixes: [#flow-components/3135](https://github.com/vaadin/flow-components/issues/3135)
=> mention vaadin-jandex for pro components

articles/flow/routing/templates.asciidoc
Remove what appears currently as spaces in the the route template parameters:
=> Remove extra spaces from Route template parameters

articles/routing/route-parameters.asciidoc
I was not able to find any concrete information regarding this information from the sources below.
https://vaadin.com/api/platform/23.1.0/com/vaadin/flow/router/Route.html
https://vaadin.com/api/platform/23.1.0/com/vaadin/flow/router/WildcardParameter.html
Further confirmation from Vaadin team is needed.
=> Clarifying empty wildcard parameter default value

articles/data-binding/vaadin-components.asciidoc
Add a code snippet to demonstrate how to bind a boolean to a `select`.
Closes #1474
=> Hilla: update the boolean binding example for `<vaadin-select>`

frontend/demo/component/contextmenu/context-menu-best-practices.ts, src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuBestPractices.java
1. Updated the `vaadin-context-menu` [TS example](https://vaadin.com/docs/latest/components/context-menu/#best-practices) to not show the "overflow" button (caused by `auto-width`).
2. Changed the grid column in the example to use Lit renderer directive instead of creating element with JS
3. Updated Java example accordingly and changed to use `tertiary` theme instead of `tertiary-inline`.
4. Added missing sub-menu items to the `MenuBar` in the Java example to make it actually work.
=> fix: ensure menu-bar column is rendered correctly

frontend/demo/component/crud/crud-localization.ts, frontend/demo/component/datepicker/date-picker-custom-functions.ts, frontend/demo/component/datepicker/date-picker-internationalization.ts, frontend/demo/component/datepicker/date-picker-week-numbers.ts, frontend/demo/component/datetimepicker/date-time-picker-internationalization.ts, frontend/demo/component/datetimepicker/date-time-picker-week-numbers.ts, frontend/demo/component/login/login-additional-information-preview.ts, frontend/demo/component/login/login-additional-information.ts, frontend/demo/component/upload/upload-all-files.ts, frontend/demo/component/upload/upload-auto-upload-disabled.ts, frontend/demo/component/upload/upload-button-theme-variant.ts, frontend/demo/component/upload/upload-file-count.ts, frontend/demo/component/upload/upload-file-format.ts, frontend/demo/component/upload/upload-file-size.ts, frontend/demo/component/upload/upload-helper.ts, frontend/demo/component/upload/upload-labelling.ts
Follow-up to #1549 and #1552.
Updated all the examples that set `i18n` property to use definite assignment assertion.
This makes the code a bit cleaner as we don't need to check if the element is there.
=> refactor: simplify setting i18n property in TS examples

package.json
For some reason the `"overrides"` entry was missing for `@vaadin/multi-select-combo-box` so I added it.
=> chore: update package.json overrides section

frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts
Added a missing import for `@vaadin/button`.
=> fix: add missing vaadin-button import to layout example

articles/components/map/index.asciidoc, src/main/java/com/vaadin/demo/component/map/MapEvents.java, src/main/java/com/vaadin/demo/component/map/MapMarkers.java, src/main/java/com/vaadin/demo/component/map/MapViewport.java
Adds a section about coordinate systems, and how to set user projections or define custom projections. As the docs already use 23.2, while most users are still using 23.1, this also adds a section about the breaking changes since 23.1 explaining how users on 23.1 can still make use of the documentation.
Todo:
Marked as draft: This should only be merged after updating to the next 23.2 alpha (should be `23.2.0.alpha2`).
=> docs: map coordinate systems

dspublisher/theme/init-browser.ts
We're going to create notifications for new threads and we use urls from discussion component to generate links. I noticed that you drop /docs prefix from url parameter in the integrated discussion component and this causes invalid links. To avoid dirty workarounds on our side I think it's easier just to leave the prefix.
=> Leave /docs prefix in discussion url

articles/components/charts/index.asciidoc
Accidentally copy-pasted `moduleNpmVersion:vaadin-crud` from another module.
Fixed to `moduleNpmVersion:vaadin-charts`
Both packages are released with same version so link was fine anyway.
=> chore: Fix typo in charts link computation

frontend/demo/session-verification.ts
To try to understand what's happening in production when Java examples sometimes fail to show up properly.
=> Add logging to session-verification

frontend/demo/component/tabs/tabs-content.ts
Fixed the error in [Switching Between Content](https://vaadin.com/docs/latest/components/tabs/#switching-between-content) TS example:
```
Uncaught TypeError: Cannot read properties of null (reading 'adoptedStyleSheets')
at L (commons-cb7494fc173cb1a6ae9d.js:7056:66146)
at R (commons-cb7494fc173cb1a6ae9d.js:7056:66471)
at new s (350-4341b9acaec60b4aacbc.js:1:7906)
at i.<anonymous> (commons-cb7494fc173cb1a6ae9d.js:5638:5560)
at new i (commons-cb7494fc173cb1a6ae9d.js:5638:6059)
at GddB.customElements.define (app-01dd008c8c882daa6248.js:2:164990)
at commons-cb7494fc173cb1a6ae9d.js:5638:5968
```
This was the only component that used `applyTheme()` in the `constructor()` and had this error.
Moved the `applyTheme()` call to `createRenderRoot()`, same as in other TS examples.
=> fix: move applyTheme to createRenderRoot

articles/upgrading/essential-steps/instructions/_styling.adoc, articles/upgrading/essential-steps/instructions/_typescript.adoc, articles/upgrading/upgrade-tool/styling/_21-22.adoc, articles/upgrading/upgrade-tool/typescript/_21-22.adoc
Replaced `“` and `”` (left and right double quotation marks) with correct `"` quotation marks.
This is needed to make sure these HTML and CSS examples work when copying to editor.
=> docs: use correct quotes in code examples

articles/binding-data/data-provider.asciidoc, articles/components/charts/configuration.asciidoc, articles/create-ui/templates/and-binder.asciidoc, articles/integrations/quarkus.asciidoc
Fixed a few typos discovered using [`cspell`](https://www.npmjs.com/package/cspell) CLI utility.
=> docs: fix typos detected by cspell

tsconfig.json
Now when Vaadin supports latest versions of browsers, it makes sense to also enable ES2021 features.
In particular, this includes [String.prototype.replaceAll()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) used in #1612
This feature is supported in [Safari 13.1 and later](https://caniuse.com/mdn-javascript_builtins_string_replaceall) so it should be safe for us to use it.
=> chore: set target in tsconfig.json to es2021

articles/components/menu-bar/index.asciidoc, frontend/demo/component/menubar/menu-bar-right-aligned.ts, src/main/java/com/vaadin/demo/component/menubar/MenuBarRightAligned.java
Added an Alignment section to the MenuBar docs to demonstrate how to align menu items.
Fixes https://github.com/vaadin/docs/issues/1679
=> feat: add MenuBar Alignment section

articles/tools/observability/advanced/custom-instrumentation.asciidoc
The instrumentation-annotation was mistakenly
dropped during refactoring. Re add  required
dependencies to correct parts of the document.
`opentelemetry-api` only brings in `opentelemetry-context`
and `opentelemetry-instrumentation-annotations` has no dependencies
=> fix: add missing annotations dependency

articles/tools/observability/integrations/datadog.asciidoc, articles/tools/observability/integrations/grafana.asciidoc, articles/tools/observability/integrations/index.asciidoc, articles/tools/observability/integrations/jaeger-prometheus.asciidoc, articles/tools/observability/integrations/newrelic.asciidoc
- simplify and align page titles
- switch page order to prefer production-ready setups and targeted customer base
- mention explicitly supported integrations in overview, add links to OpenTelemetry
- mention Grafana as alternative for local development, explain upsides, downsides
=> docs: observability integrations polish

frontend/demo/component/accordion/accordion-summary.ts, frontend/demo/component/badge/badge-counter.ts, frontend/demo/component/button/button-labels.ts, frontend/demo/component/grid/grid-dynamic-height.ts, frontend/demo/component/grid/grid-item-details-toggle.ts, frontend/demo/component/gridpro/grid-pro-editors.ts, frontend/demo/upgrade-tool/upgrade-tool.ts
Aligned formatting for open and closing HTML tags to make it look nicer (and fix some Prettier weirdness).
These elements are mostly inline (`<span>`, `<a>`, `<vaadin-button>`) so whitespace does not matter.
=> chore: align open and closed tags formatting

frontend/demo/component/avatar/avatar-abbreviation.ts, frontend/demo/component/avatar/avatar-basic.ts, frontend/demo/component/avatar/avatar-image.ts, frontend/demo/component/avatar/avatar-sizes.ts, src/main/java/com/vaadin/demo/component/avatar/AvatarAbbreviation.java, src/main/java/com/vaadin/demo/component/avatar/AvatarBasic.java, src/main/java/com/vaadin/demo/component/avatar/AvatarImage.java, src/main/java/com/vaadin/demo/component/avatar/AvatarSizes.java
Toggling between the Java/TypeScript source in the Avatar examples shows a mismatch with layouting. The TS example has spacing between the avatars while the Java example does not.
https://user-images.githubusercontent.com/1222264/191939897-1773ebcf-97ea-47b7-9c6d-e4018d955e04.mp4
This PR makes the Avatar examples use the same approach as we use with many other examples to align the spacing = wrap the individual instances in a `HorizontalLayout`.
=> chore: use horizontal layout in avatar examples

frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts, frontend/demo/component/basiclayouts/basic-layouts-margin.ts, frontend/demo/component/basiclayouts/basic-layouts-padding.ts, frontend/demo/component/basiclayouts/basic-layouts-spacing-variants.ts, frontend/demo/component/basiclayouts/basic-layouts-spacing.ts, frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-horizontal-alignment.ts, frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-individual-alignment.ts, frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-vertical-alignment.ts
Change the `vaadin-radio-group` usage in basic layouts TS demos to bind `.value` property.
This makes the code a bit more readable and is aligned with other field components demos.
=> refactor: use radio-group value instead of checked

src/main/java/com/vaadin/demo/component/applayout/AppLayoutBottomNavbar.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbar.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacement.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacementSide.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutSecondaryNavigation.java, src/main/java/com/vaadin/demo/component/avatar/AvatarSizes.java, src/main/java/com/vaadin/demo/component/confirmdialog/ConfirmDialogCancelButton.java, src/main/java/com/vaadin/demo/component/confirmdialog/ConfirmDialogRejectButton.java, src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java, src/main/java/com/vaadin/demo/component/map/MapEvents.java, src/main/java/com/vaadin/demo/component/menubar/MenuBarInternationalization.java, src/main/java/com/vaadin/demo/component/messages/MessageInputComponent.java, src/main/java/com/vaadin/demo/component/messages/MessageListComponent.java, src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java, src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java, src/main/java/com/vaadin/demo/component/notification/NotificationStaticHelper.java, src/main/java/com/vaadin/demo/component/scroller/ScrollerBasic.java, src/main/java/com/vaadin/demo/component/scroller/ScrollerBoth.java, src/main/java/com/vaadin/demo/component/scroller/ScrollerMobile.java, src/main/java/com/vaadin/demo/component/select/SelectCustomRendererLabel.java, src/main/java/com/vaadin/demo/component/select/SelectDisabled.java, src/main/java/com/vaadin/demo/component/select/SelectPlaceholder.java, src/main/java/com/vaadin/demo/component/select/SelectPresentation.java, src/main/java/com/vaadin/demo/flow/application/resources/ImageClassResource.java, src/main/java/com/vaadin/demo/flow/binding/DataBinding.java, src/main/java/com/vaadin/demo/flow/routing/LoginScreen.java
Added missing `// hidden-source-line` comments to some `DemoExporter` imports in Java examples.
=> chore: add missing comments to DemoExporter imports

src/main/java/com/vaadin/demo/component/accordion/AccordionBasic.java, src/main/java/com/vaadin/demo/component/board/BoardBasic.java, src/main/java/com/vaadin/demo/component/gridpro/GridProBasic.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxBasic.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxI18nDemo.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxReadOnly.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelection.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectionChange.java, src/main/java/com/vaadin/demo/component/notification/NotificationBasic.java, src/main/java/com/vaadin/demo/component/notification/NotificationContrast.java, src/main/java/com/vaadin/demo/component/notification/NotificationError.java, src/main/java/com/vaadin/demo/component/notification/NotificationKeyboardA11y.java, src/main/java/com/vaadin/demo/component/notification/NotificationLink.java, src/main/java/com/vaadin/demo/component/notification/NotificationPosition.java, src/main/java/com/vaadin/demo/component/notification/NotificationPrimary.java, src/main/java/com/vaadin/demo/component/notification/NotificationRetry.java, src/main/java/com/vaadin/demo/component/notification/NotificationStaticHelper.java, src/main/java/com/vaadin/demo/component/notification/NotificationSuccess.java, src/main/java/com/vaadin/demo/component/notification/NotificationUndo.java, src/main/java/com/vaadin/demo/component/virtuallist/VirtualListBasic.java
Part of #1735
Fixed indentation from 2 spaces to 4 spaces for the following components examples:
- `Accordion`
- `Board`
- `GridPro`
- `MultiSelectComboBox`
- `Notification`
- `VirtualList`
Use "hide whitespace" checkmark when reviewing to make PR diff smaller.
=> chore: reindent Java examples using 4 spaces (part 5)

articles/advanced/servlet-container-authentication.asciidoc, articles/create-ui/creating-components/mixins.asciidoc, articles/create-ui/enabled-state.asciidoc, articles/create-ui/templates/and-binder.asciidoc, articles/create-ui/templates/basic.asciidoc, articles/create-ui/templates/components-in-slot.asciidoc, articles/create-ui/templates/components.asciidoc, articles/create-ui/templates/limitations.asciidoc, articles/create-ui/templates/polymer/bindings.asciidoc, articles/create-ui/templates/polymer/event-handlers.asciidoc, articles/create-ui/templates/polymer/list-bindings.asciidoc, articles/create-ui/templates/polymer/model-bean.asciidoc, articles/create-ui/templates/polymer/model-encoders.asciidoc, articles/create-ui/templates/polymer/parent-layout.asciidoc, articles/create-ui/templates/polymer/polymer-template-and-binder.asciidoc, articles/create-ui/templates/polymer/polymer-template-basic.asciidoc, articles/create-ui/templates/polymer/polymer-template-components-in-slot.asciidoc, articles/create-ui/templates/styling-templates.asciidoc, articles/create-ui/templates/subtemplate.asciidoc, articles/integrations/cdi/instantiated-beans.asciidoc, articles/tools/dspublisher/customization.asciidoc
- Changed the indentation of Polymer and Lit template to 2 spaces,
- Fixed a few things like self-closing tags, incorrect binding syntax,
- Also wrapped backticks, which seems to fix code highlighting:
Use "hide whitespace" checkmark when reviewing to make PR diff smaller.
=> chore: fix Polymer and Lit templates indentation

articles/components/grid/index.asciidoc, articles/components/menu-bar/index.asciidoc, articles/components/tabs/index.asciidoc, articles/components/tooltip/index.asciidoc, frontend/demo/component/tooltip/tooltip-positioning.ts
Fixed some DX test findings:
- Added heading for `TabSheet` to the `Tabs` page to emphasize it
- Fixed broken API docs link for `vaadin-tooltip` web component
- Changed some tooltip TS examples to have better separation
- Changed the snippet in the TS example for tooltip positioning
=> docs: fix DX findings for TabSheet and Tooltip

articles/components/tooltip/index.asciidoc
Add TS example for configuring tooltip delays. Currently, there's an example for Java only.
=> docs: add TS example for configuring tooltip delays

articles/tutorials/in-depth-course/type-safe-server-access-with-endpoints.adoc
UUID import wasn't added when changed in the final fixes prior to launching Hilla: https://github.com/vaadin/docs/commit/3bc1fb572767d956bdacd3aaaf472f0e5d84a6bd
=> In-Depth Course, Backend Page: Add missing import in the initial class snippet

src/main/java/com/vaadin/demo/component/accordion/AccordionContent.java, src/main/java/com/vaadin/demo/component/details/DetailsContent.java, src/main/java/com/vaadin/demo/component/details/DetailsSummary.java
Removed usage of `ElementConstants` from several Java examples for consistency.
IMO it's ok to use `getStyle().set("color", "var(--lumo-primary-text-color)")`.
This also makes the code slightly more readable by not wrapping in 2 lines.
=> chore: do not use ElementConstants for inline styles

src/main/java/com/vaadin/demo/component/applayout/AppLayoutBasic.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutBottomNavbar.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutHeightAuto.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutHeightFull.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbar.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacement.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacementSide.java, src/main/java/com/vaadin/demo/component/applayout/AppLayoutSecondaryNavigation.java
Fixes #1735
Fixed indentation from 2 spaces to 4 spaces for the following components examples:
- `AppLayout`
Use "hide whitespace" checkmark when reviewing to make PR diff smaller.
=> chore: reindent Java examples using 4 spaces (part 6)

src/main/java/com/vaadin/demo/component/confirmdialog/ConfirmDialogRejectButton.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectionChange.java, src/main/java/com/vaadin/demo/component/notification/NotificationKeyboardA11y.java, src/main/java/com/vaadin/demo/component/tabs/TabSheetLazyInitialization.java, src/main/java/com/vaadin/demo/component/tooltip/TooltipHtmlElement.java
Follow-up to #1791. Added some missing `// hidden-source-line` comments, fixed formatting.
=> chore: hide DemoExporter from Java examples

articles/advanced/components-definitions.asciidoc
Removed `since` badges which are no longer relevant for Hilla. Also fixed the introduction: the `.d.ts` files are no longer generated, and "TypeScript support" / "client-side views" were only relevant for Flow (not Hilla).
=> chore: update components TS definitions article

articles/tutorial/overview.adoc
The CRM tutorial live [demo](https://crm.demo.vaadin.com/) cannot be accessed with the provided username and password. Let's remove the link to demo until we figure out how to update it.
=> Remove link to non-functioning application

articles/guide/step-by-step/importing/index.asciidoc
Microsoft stopped working on Atom and it will be officially sunset on December 15, 2022, see [the announcement](https://github.blog/2022-06-08-sunsetting-atom/).
Removed it from the table. We might want to also update [Editing Tools](https://vaadin.com/docs/latest/contributing-docs/authoring/editing-tools/#atom-editor) page to add VS Code instead.
=> docs: remove Atom from commonly used IDEs

pom.xml
I forgot to bump `spring-boot-starter-parent` as part of #1914, so doing it here.
=> chore: bump spring-boot-starter-parent to 2.7.4

articles/404.asciidoc, articles/components/grid/index.asciidoc, articles/components/menu-bar/index.asciidoc, articles/components/text-field/index.asciidoc, articles/contributing-docs/authoring/editing-tools.asciidoc, articles/contributing-docs/style-guide/formatting-style.asciidoc, articles/contributing/editor-settings-intellij-idea.asciidoc, articles/create-ui/shortcut.asciidoc, articles/tutorial/components-and-layouts.adoc
There is a lack of consistency with the presentation of key inputs. This standardizes the usage across the documentation.
=> Clean up key input formatting

articles/upgrading/essential-steps/instructions/_common.adoc
Since Vaadin 23.3 some generated resources has been moved from target to fronted/generated directory.
When downgrading, running Vaadin clean tasks is necessary to avoid compilation errors building against the earlier version.
Closes vaadin/flow#15208
=> docs: mention to run cleanup task when downgrading

articles/react/components/input-fields/index.adoc
"Input fields" page contains a duplicate header which is removed in this PR
=> fix: remove duplicate header from input fields

articles/tools/observability/getting-started.asciidoc, articles/tools/observability/index.asciidoc
Updates the O11y Kit agent pre-release download link with the Maven Central 1.0.0 artifact.
=> Update O11y Kit download link

articles/lit/start/in-depth/installing-and-offline-pwa.adoc
start.vaadin.com no longer generates projects with the `@PWA` annotation. The annotation should, thus, be added rather than updated.
=> Indicate @PWA should be added rather than updated

articles/components/date-picker/index.asciidoc
Fix typo in reference date documentation. The 2-digit year for the example date should be '49', but is '39'.
=> docs: fix typo in reference date example

articles/components/number-field/index.asciidoc, frontend/demo/component/numberfield/number-field-min-max.ts, frontend/demo/component/numberfield/number-field-step-buttons.ts, frontend/demo/component/numberfield/number-field-step.ts, src/main/java/com/vaadin/demo/component/numberfield/NumberFieldMinMax.java, src/main/java/com/vaadin/demo/component/numberfield/NumberFieldStep.java, src/main/java/com/vaadin/demo/component/numberfield/NumberFieldStepButtons.java
Replaces usages of the deprecated `hasControls` property with the `stepButtonsVisible` property, and updates references to the buttons in the asciidoc.
Needs to wait for the next 23.3 alpha release before being merged.
Part of https://github.com/vaadin/flow-components/issues/1106
=> docs: replace hasControls with stepButtonsVisible

articles/lit/start/basics/index.adoc, articles/lit/start/in-depth/project-setup.adoc, articles/lit/start/quick.adoc
A community member reached out and said that they were not able to start a Hilla project with the CLI because of corporate policy blocking the CLI. This PR provides direct download links to the same projects as ZIP files. 
Please verify this locally before merging, I was not able to get the docs app running locally.
=> Add direct download links as alternate ways to start a Hilla project

frontend/demo/component/avatar/avatar-image.ts, frontend/demo/component/button/button-images.ts, frontend/demo/component/login/login-overlay-mockup.ts, frontend/demo/component/scroller/scroller-both.ts
Vite exports images via the default export. Updated the imports accordingly to fix the images not showing up in certain examples.
```diff
- import * as img from '../../../../src/main/resources/images/starry-sky.png';
+ import img from '../../../../src/main/resources/images/starry-sky.png';
```
=> fix: use default import syntax for images

frontend/demo/example-resources.ts, frontend/demo/init-flow-namespace.ts, frontend/demo/init.ts, frontend/demo/session-verification.ts
Removed usage of `// @ts-ignore` to fix related warnings from `eslint-config-vaadin`.
=> chore: replace ts-ignore comments with ts-expect-error

frontend/demo/component/notification/notification-rich.ts
The Notification [rich content](https://vaadin.com/docs/latest/components/notification/#icons-and-other-rich-formatting) example is currently broken when [opening in a new tab](https://vaadin.com/docs/latest/example?path=component/notification/notification-rich.ts).
Added a missing import for `vaadin-horizontal-layout` web component to fix that.
=> chore: add missing horizontal-layout import to demo

frontend/demo/component/icons/iconset-generator.ts, frontend/demo/component/icons/iconset-helpers.ts
1. Simplified the icons generator logic and moved some functions to separate file,
2. Fixed some `eslint-config-vaadin` errors, including `async` / `await` usage.
=> chore: refactor icons generator, fix ESLint errors

frontend/demo/component/custom-field/custom-field-size-variants.ts
1. Updated the demo to use `items` property for `vaadin-select`,
2. Changed to use `@query()` decorator for setting `aria-label`.
=> chore: simplify custom-field size variants demo

frontend/demo/component/grid/grid-drag-rows-between-grids.ts, frontend/demo/component/gridpro/grid-pro-edit-column.ts
Fixed the following TS compilation errors that I introduced by accident 😞 
```
13:54:55  [ERROR] frontend/demo/component/grid/grid-drag-rows-between-grids.ts(7,1): error TS6133: 'GridColumnBodyLitRenderer' is declared but its value is never read.
13:54:55  [ERROR] frontend/demo/component/grid/grid-drag-rows-between-grids.ts(88,39): error TS2339: Property 'fullNameRenderer' does not exist on type 'Example'.
13:54:55  [ERROR] frontend/demo/component/gridpro/grid-pro-edit-column.ts(9,1): error TS6133: 'GridColumnBodyLitRenderer' is declared but its value is never read.
```
=> chore: fix TS compilation errors in grid examples

frontend/demo/component/checkbox/checkbox-custom-presentation.ts, frontend/demo/component/combobox/combo-box-presentation.ts, frontend/demo/component/contextmenu/context-menu-best-practices.ts, frontend/demo/component/contextmenu/context-menu-presentation.ts, frontend/demo/component/grid/grid-column-width.ts, frontend/demo/component/tree-grid/tree-grid-rich-content.ts
Fixed some more `eslint-config-vaadin` errors by removing extra `return` from Lit renderers.
=> chore: simplify Lit renderers by removing extra return

frontend/demo/component/charts/charts-overview.ts
This PR fixes the following warning from the `lit/attribute-value-entities` rule by `eslint-plugin-lit`:
```
/Users/serhii/vaadin/docs/frontend/demo/component/charts/charts-overview.ts
110:9  error  Attribute values may not contain unencoded HTML entities, e.g. use `&gt;` instead of `>`
```
Also, we generally should  use TypeScript instead of JSON objects to HTML attributes 🙈
=> chore: update charts to set additionalOptions using JS

frontend/demo/component/inputfields/input-field-helper.ts, frontend/demo/component/passwordfield/password-field-advanced-helper.ts
Simplified two demos (which are almost identical) to not use TypeScript `enum` which we generally don't recommend.
These examples are quite simple, and union type for `PasswordStrength` seems like a better fit in this case.
=> chore: update password strength demos to not use enum

dspublisher/application-theme-plugin/application-theme-plugin.js, dspublisher/application-theme-plugin/package.json, dspublisher/application-theme-plugin/theme-copy.js, dspublisher/application-theme-plugin/theme-generator.js, dspublisher/application-theme-plugin/theme-handle.js, dspublisher/dspublisher-scripts.js, frontend/demo/init-flow-components.ts, webpack.dspublisher.js
- Update webpack config to use dynamic `import()` for `application-theme-plugin`
- Remove the no longer existing connector imports
- Bump DSP version
- Temporarily copy application-theme-plugin to the project
=> fix: fix webpack config for Vaadin 24

articles/upgrading/V23-V24-steps/_styling.adoc
Adds missing instructions for migrating date picker theme. Also fixes existing instructions to refer to month calendar CSS file.
=> docs: add missing upgrade instructions for date picker

articles/components/grid/index.asciidoc, frontend/demo/component/grid/grid-cell-focus.ts, frontend/themes/docs/components/vaadin-grid.css, frontend/themes/docs/grid-cell-focus.css, frontend/themes/docs/styles.css, src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java
Updates the grid cell focus example to use the new theming mechanism.
=> docs: update grid cell focus example to use global styles

.github/styles/Vocab/Docs/accept.txt, articles/components/rich-text-editor/index.asciidoc, frontend/demo/component/richtexteditor/rich-text-editor-set-get-value.ts, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
Updates the RichTextEditor "Value Format" section to reflect changes in v24 where the HTML format becomes the default for the Flow component.
Also updates the code examples to demonstrate usage of both formats.
This should only be merged after v24 has been released and docs have been upgraded.
=> docs: update RTE value docs to reflect default format change (v24)

frontend/demo/component/app-layout/app-layout-bottom-navbar.ts
Fixes the app layout bottom navbar example to work in Safari, as in make the navbar actually show up on the bottom. For some reason the app layout style rule is not applied in Safari, so I additionally added inline styles to the element.
Fixes https://github.com/vaadin/docs/issues/940
=> fix: applayout bottom navbar in Safari

src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorBasic.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorMinMaxHeight.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorReadonly.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeCompact.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeNoBorder.java, src/main/java/com/vaadin/demo/domain/Templates.java
As part of updating the RTE docs for v24, I missed to update the remaining examples to initialize the editor with an HTML value. Now that the component has a validation check that prevents setting delta values, this breaks every single example.
=> fix: use HTML value in RTE examples

articles/api.adoc
The "Javadoc" button in https://vaadin.com/docs/latest/api links to https://vaadin.com/api/platform/23.3.6/ which redirects to https://vaadin.com/api/api/platform/23.3.6/index.html (404) instead of https://vaadin.com/api/platform/23.3.6/index.html
=> fix: fix link to API documentation

articles/lit/guides/production/production-build.asciidoc
Made it possible to link directly to the production build command and changed the title to match the navigation
=> Reorganized production build chapter

frontend/demo/component/datetimepicker/date-time-picker-input-format.ts, src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInputFormat.java
Sets the date format to "dd/MM/yyyy" in both TS and Java examples so that the behaviour matches with what's written in helper text. Otherwise it takes the server locale into account.
Note that the time part in Java example still not correct because of https://github.com/vaadin/flow-components/issues/2831
Fixes https://github.com/vaadin/web-components/issues/172
=> fix: Incorrect date format in DateTimePicker example

frontend/themes/docs/components/vaadin-grid-styling.css
Fixes: https://github.com/vaadin/docs/issues/2024
Light:
Dark:
=> fix: use lumo colors in the grid styling example

frontend/demo/component/accordion/accordion-basic.ts, frontend/demo/component/accordion/accordion-content.ts, frontend/demo/component/accordion/accordion-disabled-panels.ts, frontend/demo/component/accordion/accordion-filled-panels.ts, frontend/demo/component/accordion/accordion-reverse-panels.ts, frontend/demo/component/accordion/accordion-small-panels.ts, frontend/demo/component/accordion/accordion-summary.ts, frontend/demo/component/details/details-basic.ts, frontend/demo/component/details/details-content.ts, frontend/demo/component/details/details-disabled.ts, frontend/demo/component/details/details-filled.ts, frontend/demo/component/details/details-reverse.ts, frontend/demo/component/details/details-small.ts, frontend/demo/component/details/details-summary.ts, frontend/demo/component/virtuallist/virtual-list-basic.ts, frontend/demo/upgrade-tool/upgrade-tool.ts
Updated `vaadin-details` and `vaadin-accordion` TS examples:
1. Changed to use `summary` property shorthand where it makes sense (in most of demos),
2. Updated other demos to use `vaadin-details-summary` and `vaadin-accordion-heading`.
=> fix: adjust details and accordion TS examples to V24 API

articles/components/rich-text-editor/index.asciidoc, frontend/demo/component/richtexteditor/rich-text-editor-set-get-value.ts, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorBasic.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorMinMaxHeight.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorReadonly.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeCompact.java, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeNoBorder.java
Updates the example under `Value format` to also show the Delta value, and allow editing it. This is adapted from the updated example from v24: https://github.com/vaadin/docs/pull/2027
There are some differences in the example compared to v24:
- It uses an improved helper text instead of a placeholder. I'll add that for v24 in a separate PR.
- In the Java example, changing the Delta value does not update the HTML value. That is not supported by the Flow component in v23.
The PR also updates the other examples to not use the deprecated `setValue` method.
=> docs: update RTE value example to show Delta value

frontend/demo/component/custom-field/custom-field-basic.ts, frontend/demo/component/custom-field/custom-field-size-variants.ts, src/main/java/com/vaadin/demo/component/customfield/DateRangePicker.java, src/main/java/com/vaadin/demo/component/customfield/MoneyField.java
We internally agreed with @web-padawan that we will use the `title` attribute instead of `aria-label` in Custom Field examples until https://github.com/vaadin/web-components/issues/5580 is fixed.
=> docs: use title instead of aria-label in Custom Field examples

articles/create-ui/shortcut.asciidoc
Adds more specific examples for event propagation and  binding to another component.
Fixes https://github.com/vaadin/docs/issues/2122
=> feat: Add more example to the Shortcuts API chapter

frontend/demo/component/custom-field/custom-field-basic.ts
The line was accidentally removed in #2186.
=> fix: restore date-fns import in custom-field-basic

articles/components/rich-text-editor/index.asciidoc
Based on #2177 
Adds a collapsible section detailling the Delta format. 
Closes https://github.com/vaadin/docs/issues/496
I'll see if I can refactor the examples to also show the templates used by `DataService`, but in a separate PR.
=> docs: add Delta format details to RTE docs

articles/components/rich-text-editor/index.asciidoc
- Move the `Value Format` section to the top, as it's arguably the most interesting one
- Update the existing text of the `Value Format` section to better reflect that both formats can be used equally, and how to use them - adapted from https://github.com/vaadin/docs/pull/2027
- Add a collapsible section detailling the HTML format
=> docs: add HTML format details to RTE docs

articles/components/grid/flow.asciidoc
Document using model properties in LitRenderer.
This is only relevant for Vaadin 24 (targeting `next` branch).
Related internal Slack [discussion](https://vaadin.slack.com/archives/C3TGRP4HY/p1676534800750329)
=> docs: document using model properties in LitRenderer

articles/components/rich-text-editor/index.asciidoc, frontend/demo/component/richtexteditor/rich-text-editor-set-get-value.ts, src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
Manually porting changes from `latest` to `next`, as v24 changes will prevent a clean merge:
- Update example to use helper texts instead of placeholders (#2176)
- Move `Value Format` section to top, add HTML details (#2177)
- Add Delta details (#2187)
None of the asciidoc texts have been modified.
=> docs: add HTML and Delta format details to RTE docs (v24)

frontend/demo/component/datepicker/date-picker-min-max.ts, frontend/demo/component/datetimepicker/date-time-picker-custom-validation.ts, frontend/demo/component/datetimepicker/date-time-picker-min-max.ts, frontend/demo/component/timepicker/time-picker-min-max.ts, src/main/java/com/vaadin/demo/component/datepicker/DatePickerMinMax.java, src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerCustomValidation.java, src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerMinMax.java, src/main/java/com/vaadin/demo/component/timepicker/TimePickerMinMax.java
This PR aims to fix accessibility review findings for the following components:
Fixes https://github.com/vaadin/web-components/issues/104
Fixes https://github.com/vaadin/web-components/issues/105
Fixes https://github.com/vaadin/web-components/issues/109
The part about old "Custom validator" example in https://github.com/vaadin/web-components/issues/104 is no longer relevant:
> The same happens for the [Custom validator](https://vaadin.com/components/date-picker/html-examples/date-picker-validation-demos#custom-validator) example if the user chooses a date that is not a working day.
> The date picker with an invalid date - only the background colour of the control is changed
=> docs: use proper error messages to fix examples a11y findings

frontend/demo/component/grid/grid-buffered-inline-editor.ts, frontend/demo/component/grid/grid-unbuffered-inline-editor.ts
Opening the examples in new tabs did not work due to missing imports. This PR adds those imports to the 2 Java-only inline editor examples.
Fixes #810 
Updated PR with clean branch. See [initial PR](https://github.com/vaadin/docs/pull/2193).
=> docs: add missing imports to grid inline editor examples

pom.xml
Needed after https://github.com/vaadin/docs/pull/2178 to fix `Field vaadinDefaultRequestCache in com.vaadin.flow.spring.security.VaadinWebSecurity required a bean of type 'com.vaadin.flow.spring.security.VaadinDefaultRequestCache' that could not be found.`
Thanks @mcollovati for finding the solution.
=> fix: update Spring Boot parent version

articles/advanced/classic-components.asciidoc
Add mention of `AbsoluteLayout` to the classic components page.
Fixes #2208 2208
=> docs: classic components absolute layout

articles/configuration/live-reload/jetty.asciidoc
V24 uses Jetty 11 with Jakarta 10 support, docs update according live update.
=> docs: udpdate jetty live update info in V24

articles/components/grid/flow.asciidoc, articles/components/grid/index.asciidoc
Reworks the Flow-specific `Column Sorting` section. While the content was good, there were some confusing or missing parts, and usage of deprecated or removed API.
I tried to address the following issues:
- Start by explaining how to enable sorting in the first place, when it is enabled automatically, and when it is not.
- In addition to explaining in-memory and back-end sorting, also explain when a column is automatically configured for either method. 
- Removed section that used deprected methods of setting sort property names directly in `Grid.addColumn(String, String...)`. This is also required in v24, where these methods have been removed.
- Reworked the following two sections to be explicitely about configuring in-memory sorting, and back-end sorting, rather than about which API …
=> docs: improve Flow grid sorting section

articles/advanced/customize-system-messages.adoc
Documentation for Customizing System Messages was present in Vaadin 8 but not ported to Flow.
Fixes #1699
=> docs: ported and reworked Customizing System Messages documentation

articles/advanced/application-lifecycle.asciidoc
Clarified that Vaadin session expiration does not imply HTTP session invalidation.
Documented the client side behavior on session expiration and customization options.
Closes #1954
=> chore: improved Vaadin session expiration docs

articles/components/custom-field/index.asciidoc
Added a section explaining the difference between how Custom Field handles the value type and format in Java and TypeScript.
Fixes #1941
=> docs: explain Custom Field value type and format

articles/components/grid/index.asciidoc, frontend/demo/component/grid/grid-data-provider.ts, src/main/java/com/vaadin/demo/component/grid/GridDataProvider.java, src/main/java/com/vaadin/demo/component/grid/PersonDataProvider.java, src/main/java/com/vaadin/demo/component/grid/PersonFilter.java
Added a Grid example showing basically how to use data providers for lazy loading, sorting, and filtering items.
Fixes https://github.com/vaadin/docs/issues/79, https://github.com/vaadin/docs/issues/513
=> docs: add Grid data provider examples

src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomField.java
Streams don't support the `toList()` method in Java 11. The `collect(Collectors.toList())` construction is the right alternative.
=> refactor: do not use Java 17 API in Form Item examples

articles/security/enabling-security.adoc
The previous example returned an `Optional` object instead of the desired username.
=> Fix faulty code in security example

frontend/demo/component/grid/grid-drag-drop-filters.ts, frontend/demo/component/tree-grid/tree-grid-basic.ts, frontend/demo/component/tree-grid/tree-grid-column.ts
The deprecated property `itemHasChildrenPath` was removed from `<vaadin-grid-tree-column>` in https://github.com/vaadin/web-components/pull/4942
=> fix: move itemHasChildrenPath property to the grid element

.github/styles/Vocab/Docs/accept.txt
It only works without the dash at the moment. It becomes apparent when "Sign-in" is in a title.
=> Add sign-in and sign-out to vocabulary

articles/lit/start/basics/index.adoc
The link to the word "spacing properties" redirects to `https://vaadin.com/docs/latest/styling/lumo/design-tokens/size-space#space` which results in a 404 not found error.  The corrected link now takes you to the correct Lumo Style page: `https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/size-space#space`
=> fix broken link to "spacing properties"

articles/contributing/overview.asciidoc
Apparently, the `master`-branch has been renamed to `main`.
=> chore: use branch main instead of master

articles/lit/start/in-depth/type-safe-server-access-with-endpoints.adoc
In the code that gets generated by `npx @hilla/cli init --preset hilla-crm-tutorial hilla-crm`, the `id` property of the `AbstractEntity` class is type `Long`, not `java.util.UUID`.  Using `UUID` as the type for the `contactId` parameter in the `deleteContact()` method results in a compile error:
```
The method deleteById(Long) in the type CrudRepository<Contact,Long> is not applicable for the arguments (UUID)
```
=> fix compile error in deleteContact() method

articles/security/enabling-security.adoc
In Spring Boot 3 there is no http.authorizeRequests().antMatchers... anymore. I replaced it in spring boot 3 style.
=> Update antMatchers to SpringBoot3 style

articles/guide/quick-start.adoc
Remove the link to outdated video tutorials (and remove the unhelpful link to the overview page).
=> Remove link to outdated video tutorials and simplify next-steps instructions

articles/components/grid/styling.asciidoc
Corrects the label for `last-row-cell` to be "Cell in last row". Also reverses the order of `even-row-cell` and `odd-row-cell` to match `even-row` and `odd-row`.
=> Correct label for `last-row-cell` and standardize order of even/odd

articles/tools/observability/getting-started.asciidoc, articles/tools/observability/index.asciidoc
The download buttons for the Observability Kit agent do not point to the correct versions.
This updates them to V2.0.0. Note: This will need to be changed to V2.1.0 for V24.1 of the docs.
=> Update download links to point to v2.0.0

articles/compatibility.adoc
Added a list of supported technologies for V23, same as https://github.com/vaadin/docs/pull/2419 for latest
=> Add compatibility matrix for V23

articles/tools/sso/integrations/azure-ad.asciidoc
This fixes a typo in the Azure AD tutorial for SSO Kit, where the login path should start with `/oauth2` (not `/oauth`).
=> Fix typo in SSO Azure tutorial

articles/components/index.asciidoc, dspublisher/theme/global.css
Better PRO indicators for components page:
=> PRO badges in Components page

.eslintrc.js, dspublisher/config/default.json, dspublisher/dspublisher-scripts.js, dspublisher/theme/global.css, package-lock.json, package.json, tsconfig.json
In preparation for adding live React examples on hilla.dev this PR adds the setup necessary to run the examples.
Related to https://github.com/vaadin/docs/pull/2506
Since this PR doesn't yet include any changes to the existing components pages, it should be safe to merge.
=> feat: setup react live examples for hilla

articles/production/production-build.adoc
Excluding `vaadin-dev` instead of `vaadin-dev-server` prevents also the `vaadin-dev-bundle` to being included in the production build.
BTW, this is the configuration provided by start.vaadin.com
=> chore: update exclusion of dev artifacts for production build

articles/components/tabs/styling.asciidoc
Hovering of a vaadin-tab is only possible via CSS pseudo-class e.g. `vaadin-tab:hover { ... }` and not via CSS pseudo-element `vaadin-tab::hover { ... }`.
Therefore, the documentation should be adapted.
=> Tab hover only as CSS pseudo-class

README.md, articles/components/accordion/index.asciidoc, articles/components/app-layout/index.asciidoc, articles/components/avatar/index.asciidoc, articles/components/badge/index.asciidoc, articles/components/button/index.asciidoc, articles/components/combo-box/index.asciidoc, articles/components/date-picker/index.asciidoc, articles/components/grid/index.asciidoc, articles/components/login/index.asciidoc, articles/components/notification/index.asciidoc, articles/components/tabs/index.asciidoc, articles/components/upload/index.asciidoc, dspublisher/config/default.json, dspublisher/config/production.json, dspublisher/dspublisher-scripts.js, src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
- Bumps DSP to 2.2.0-alpha.2
- Updates configuration to remove the `hiddenContent` setting that was removed, and adds attributes for frameworks that should be enabled
- Wrap React examples into conditional so that they are only shown when `React` attribute is defined
- Update conditionals for Flow / Java-only content
For now this only adds / updates conditionals that are required to properly display content for the Vaadin docs site. I'll open follow-up PRs to:
- Introduce a `lit` attribute, and wrap all examples with a respective conditional (`flow`, `lit`, `react`)
- Do the same version bump and configuration update in the `hilla` branch
=> chore: bump DSP to 2.2.0-alpha.2

articles/index.asciidoc
It's the _free_ support that ended. The existing commercial support is also "official".
=> Change V7 end of free support note

webpack.dspublisher.js
The `webpack.dspublisher.js` file is imported using a dynamic `require()` call in DSP (`gatsby-node.js`). This fails on Windows in the type of error in the following screenshot:
Using a file URL for the dynamic `import()` call in the `webpack.dspublisher.js` file resolves the issue.
Tested locally on Windows 11 and macOS 13.4 (Ventura), both running Node v18.
=> fix: use file URL for dynamic `import()`

articles/components/index.asciidoc
This will hide `Spreadsheet` card and the "Didn't Find What You Need?" section on the component index page when `flow` (and `lit`) attribute isn't true (React components documentation).
=> chore: mark flow and lit only content on components page

scripts/pick/cherry-pick-config-hilla-react-components.js
This PR adds a [cherry-pick](https://github.com/vaadin/docs/tree/latest/scripts/pick) config for cloning the component documentation from `latest` to `hilla` branch.
The script can be run with:
```
node ./scripts/pick/cherry-pick.js -t hilla -c ./scripts/pick/cherry-pick-config-hilla-react-components.js
```
Here's an example PR generated with this configuration: https://github.com/vaadin/docs/pull/2600
=> feat: add cherry-pick config for hilla react components

articles/tools/observability/integrations/jaeger-prometheus.asciidoc
Clarify that it's the example that is not production-ready, not the observability Kit itself.
=> Clarify that it's the O11y example that is not production-ready

frontend/demo/component/textfield/text-field-constraints.ts
Due to a [recent change in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1412729#c55), the pattern validation in the textfield examples doesn't work because the regex can not be parsed:
```
text-field#constraints:1 Pattern attribute value ^[+]?[(]?[0-9]{3}[)]?[-s.]?[0-9]{3}[-s.]?[0-9]{4,6}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[+]?[(]?[0-9]{3}[)]?[-s.]?[0-9]{3}[-s.]?[0-9]{4,6}$/v: Invalid character in character class
```
This fixes the regex by properly escaping problematic characters in character groups.
Fixes https://github.com/vaadin/web-components/issues/6274
=> fix: properly escape regex in textfield examples

articles/create-ui/creating-components/mixins.asciidoc
Links to API should use {moduleMavenVersion:com.vaadin:vaadin} attribute to be synced with documentation version.
Related-to: vaadin/flow#10761
=> Update links in mixins documentation

articles/react/guides/forms/binder-load.adoc
The React doc was not referencing the respective Lit doc correctly.
=> fix: update include for Hilla React binder load docs

articles/lit/guides/forms/binder-validation.adoc, articles/lit/guides/forms/form-status-tracking.adoc, articles/lit/guides/forms/reference.adoc
- Fix `useEffect` usage in cross-field validation docs
- Clarify form states
- Use correct source type in form reference
=> docs: small improvements to Hilla React forms docs

articles/lit/start/basics/index.adoc
This removes the usage of Formik in our basic tutorial, 
and uses Hilla built-in binder API (`useForm`) instead.
=> fix: remove Formik and replace it with useForm API

articles/lit/guides/forms/binder-validation.adoc
Sample image for the cross-field validation was showing the validation error for the password
while the React sample code was returning the `repeatedPassword` property.
=> fix: sync sample code with sample image

articles/react/components/index.asciidoc, dspublisher/theme/global.css
Show the first few items in the components navigation even when collapsed, making the following category more easily discoverable.
Before:
After:
=> fix: Improve navigation menu discoverability

frontend/demo/component/grid/grid-dynamic-height.ts
Fixes #2800
While `Person.id` has type `number`, the actual value from JSON is of `string` type.
Updated the comparison to ensure the ID returned from the server is also a string.
=> fix: ensure string ID in grid dynamic height TS example

.gitattributes, scripts/pick/cherry-pick-config.js
Creating .gitattributes file for recognizing ascii doc files, used in GitHub's language calculation.
=> Add asciidoc Language

articles/react/components/figma.adoc
Re-introduce the change made in #2785 that was (I suppose mistakenly) reverted in #2827. 
FYI, @jouni.
=> Don't show Figma libraries at the top

articles/tutorial/forms-and-validation.adoc
Binder<Contact> binder = new BeanValidationBinder<>(Contact.class); ❌
⬇️
BeanValidationBinder<Contact> binder = new BeanValidationBinder<>(Contact.class); ✅
=> Addition of proper constructor

articles/tools/appsec/advanced-topics.asciidoc, articles/tools/appsec/getting-started.asciidoc, pom.xml
- Fixes internal link in the AppSec Kit getting started documentation
- Removes the `appsec-kit-v24` dependency from the docs project and sets the version to `1.1.0` in the documentation and updates the description for it. This is needed because the `appsec-kit-v24 `dependency requires the users of the docs project to have a license and a subscription for it because without that the docs app can't be started. This change (revert of this [commit](https://github.com/vaadin/docs/pull/2818/commits/3d4a45fe049f109fe10fd631ef369baf315f8ed9)) solves this issue.
=> Fix internal link in AppSec Kit documentation

.github/styles/Vaadin/Terms-FrontendBackend.yml, .github/styles/Vaadin/Terms.yml, articles/lit/acceleration-kits/observability-kit/getting-started.adoc, articles/lit/acceleration-kits/sso-kit/getting-started.adoc, articles/lit/guides/architecture.adoc, articles/lit/guides/client-middleware.adoc, articles/lit/guides/endpoints.adoc, articles/lit/guides/forms/binder-validation.adoc, articles/lit/guides/forms/binder.adoc, articles/lit/guides/index.adoc, articles/lit/guides/production/production-build.asciidoc, articles/lit/guides/routing.adoc, articles/lit/guides/security/spring-stateless.adoc, articles/lit/guides/security/vulnerabilities.adoc, articles/lit/guides/state-management.adoc, articles/lit/reference/endpoint-generator.adoc, articles/lit/start/basics/index.adoc, articles/lit/start/faq.adoc, articles/lit/start/gradle.adoc, articles/lit/start/in-depth/crud-operations.adoc, articles/lit/start/in-depth/index.adoc, articles/lit/start/in-depth/installing-and-offline-pwa.adoc, articles/lit/start/in-depth/production-build-and-deployment.adoc, articles/lit/start/in-depth/project-setup.adoc, articles/lit/start/in-depth/type-safe-server-access-with-endpoints.adoc, articles/react/components/progress-bar/index.asciidoc, articles/react/guides/endpoints.adoc, articles/react/guides/testing.adoc
We've decided to change our policy about whether Back-End and Front-End should be hyphenated based on its use in a sentence. For now on, we'll write them as compound words -- regardless of the usage and context.
=> Migrate Back-End & Front-End

src/main/java/com/vaadin/demo/component/grid/GridDragDropFilters.java
Follow-up from a Flow component [issue](https://github.com/vaadin/flow-components/issues/5530).
The example removes the item on drop before adding it under a parent again. This makes the item to lose its children, which is the way `TreeData.remove` works. To update the parent of an item in the tree, `TreeData.setParent` should be used instead. 
This PR updates the example to set the parent correctly.
=> refactor: grid drag drop example should set parent correctly

frontend/demo/component/grid/grid-styling.ts, frontend/demo/component/grid/react/grid-styling.tsx, frontend/themes/docs/grid-styling.css, src/main/java/com/vaadin/demo/component/grid/GridStyling.java
Reset the background color of loading rows in the Grid styling example. Couldn't find a way to achieve this by modifying the existing selectors (instead of overriding with a new selector).
Before:
https://github.com/vaadin/docs/assets/1222264/63379269-e40c-43e1-b13c-670fff64cdbe
After:
https://github.com/vaadin/docs/assets/1222264/c26cc390-92a3-4874-ba5b-a6618db4b3cb
=> chore: reset loading rows background in grid styling example

articles/react/guides/data-grids.adoc, dspublisher/dspublisher-scripts.js
Updates the DS Publisher build script to copy product data file into the static content hosted by nginx, so that it can be downloaded from there.
=> fix: use static hosting for product data download

articles/routing/exceptions.asciidoc
Adds a description about `eagerServerLoad` property for Flow, which is needed in cases when HTTP code response from `RouteNotFoundError` has to go to the browser.
Fixes: #1521
=> docs: note about eagerServerLoad property in exceptions article

scripts/pick/cherry-pick-config.js
Update `latest` -> `dsp` cherry-pick script configuration to align with the updated `dsp` branch structure.
Testing:
- `node ./scripts/pick/cherry-pick.js`
- `cd tmp/dsp`
- (`npm run dspublisher:clean`)
- `npm run dspublisher:start`
=> fix: update dsp cherry-pick config to match the new structure

articles/components/index.asciidoc
Tooltip Component is linked to spreadsheet instead of tooltip details. had no test so please check if new link is correct. KR Martin
=> fix tooltip link in component overview

articles/tools/dspublisher/custom-theme.adoc
`@Theme("docs")` should always be used with DSP projects because the default theme includes example-specific CSS files, such as https://github.com/vaadin/docs/blob/latest/frontend/themes/docs/board.css
So if you change the application not use “docs” theme, for instance the Board examples would break because the above CSS file would no longer get included.
Advise setting the custom theme as parent for the default "docs" theme instead.
=> docs: recommend using a parent theme with dsp

articles/create-ui/shortcut.adoc, articles/create-ui/shortcut.asciidoc
Adds a note to point out how click notifier's `addClickShortcut` method's default behaviour has changed since 24.3.
Related-to: vaadin/flow#5959
=> docs: update click shortcut chapter in shortcut article

articles/lit/reference/gradle.adoc, articles/react/reference/gradle.adoc
In its current position in the navigation, the docs can imply that Hilla is only Gradle-based. This PR moves the Gradle guide under the references heading.
=> Move Gradle guides under References

articles/create-ui/shortcut.adoc
Reverted earlier changes from https://github.com/vaadin/docs/pull/2954. Default behaviour of `addClickShortcut` is now reverted back to old one due to side effects. Added new chapter about resetFocusOnActiveElement, merged with previously added text, added example code.
=> docs: updated shortcut.adoc for resetFocusOnActiveElement

src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxAutoExpand.java, src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectedItemsOnTop.java
Updated Java examples to not include `add(comboBox)` to the code snippet, as it's unnecessary.
=> docs: fix code snippets for new MSCB Java examples

frontend/demo/component/combobox/react/combo-box-basic.tsx
For some reason this `tsx` file uses dash-case attributes while others use camel case. Updated it for consistency.
=> docs: use camel-case item properties in React example

frontend/demo/component/menubar/react/menu-bar-combo-buttons.tsx, frontend/demo/component/menubar/react/menu-bar-icon-only.tsx, frontend/demo/component/menubar/react/menu-bar-icons.tsx
The `aria-label` attribute from React's `AriaAttributes` should be used with React components instead of the `ariaLabel` -property from `ARIAMixin` derived from `HTMLElement`
=> docs: use dash-case aria label in React examples

articles/styling/lumo/lumo-variants.adoc
The "Lumo Colors" link at https://vaadin.com/docs/latest/styling/lumo/lumo-variants redirects to https://vaadin.com/styling/lumo/lumo-style-properties/color which results in a 404 error. The corrected link now takes you to the correct page: https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/color
=> Fix broken link to Lumo Colors

articles/security/advanced-topics/securing-plain-java-app.adoc, articles/tools/mpr/configuration/session.asciidoc
Invalidating the session before accessing UI.getCurrent() may cause null pointer exceptions on some servlet container (for example Tomcat).
Fixes vaadin/flow#18284
=> docs: swap logout instructions

articles/testing/ui-unit/component-query.adoc
The code example for a scoped query in the UI Unit Testing section uses `$view(class, parent)` for a nested query, however it should be `$(class, parent)`.
=> [UI Unit Testing] Use the correct query form in the scoped example

articles/create-ui/dnd/drag-source.asciidoc, articles/create-ui/dnd/drop-target.asciidoc
Not used in the examples and most there is not an element like card in the user code either.
=> bugfix: Removed invalid card elements from css selectors

articles/flow/binding-data/data-provider.adoc
* docs: update data-provider article for item index provider
Document how to make callback for an item index with lazy data binding.
Related-to: vaadin/flow#18088
* docs: fix vale findings
* First pass at editing.
* Vale fix
* Second full pass at editing.
---------
Cherry pick of the https://github.com/vaadin/docs/pull/3089
=> docs: update data-provider article for item index provider (#3089) (CP: next)

src/main/java/com/vaadin/demo/component/login/LoginOverlayInternationalization.java
The Login internationalization Java example is broken because the header was never set. This is required because there is no default for Header. It is also broken in v23, but is masked by the unified preview example.
This PR initializes the i18n Header.
Fixes #[5903](https://github.com/vaadin/flow-components/issues/5903)
=> fix: set i18n header before modifying for login java example

frontend/demo/component/grid/grid-column-borders.ts, frontend/demo/component/grid/grid-content.ts, frontend/demo/component/grid/grid-no-border.ts, frontend/demo/component/grid/grid-no-row-border.ts, frontend/demo/component/grid/grid-rich-content-sorting.ts, frontend/demo/component/grid/grid-row-reordering.ts, frontend/demo/component/grid/grid-row-stripes.ts, frontend/demo/component/grid/grid-wrap-cell-content.ts, frontend/demo/component/grid/react/grid-column-borders.tsx, frontend/demo/component/grid/react/grid-content.tsx, frontend/demo/component/grid/react/grid-no-border.tsx, frontend/demo/component/grid/react/grid-no-row-border.tsx, frontend/demo/component/grid/react/grid-rich-content-sorting.tsx, frontend/demo/component/grid/react/grid-row-reordering.tsx, frontend/demo/component/grid/react/grid-row-stripes.tsx
Original TS examples added in #411 were using `<img>` for rendering images in grid cells. Later on, they were replaced with `vaadin-avatar` in #631 but the `alt` attribute wasn't removed. This attribute is not supported by `vaadin-avatar`.
=> docs: remove unsupported alt attribute from avatars

frontend/demo/component/accordion/react/accordion-summary.tsx, frontend/demo/component/badge/react/badge-basic.tsx, frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-horizontal-alignment.tsx, frontend/demo/component/board/react/board-breakpoints.tsx, frontend/demo/component/button/react/button-grid.tsx, frontend/demo/component/contextmenu/react/context-menu-presentation.tsx, frontend/demo/component/crud/react/crud-localization.tsx, frontend/demo/component/grid/react/grid-item-details.tsx, frontend/demo/component/icons/react/svg-sprites.tsx, frontend/demo/component/menubar/react/menu-bar-combo-buttons.tsx, frontend/demo/component/messages/react/message-list-component.tsx, frontend/demo/component/notification/react/notification-primary.tsx, frontend/demo/component/radiobutton/react/radio-button-checkbox-alternative.tsx, frontend/demo/component/tabs/react/tabsheet-lazy-initialization.tsx, frontend/demo/component/upload/react/upload-labelling.tsx
- Added missing `// hidden-source-line` comments to a few React examples
- Sorted imports so that `import React from 'react'` would be the topmost
=> chore: add missing hidden-source-line, align React imports

articles/flow/create-ui/element-api/client-server-rpc.adoc
Adds a note about the usage of AllowInert annotation to allow RPC calls to components behind a modal dialog or component.
Fixes vaadin/flow#17496
=> docs: add note about AllowInert on RPC calls (#3111) (CP: next)

dspublisher/config/production.json
Enable showing the React examples in production on `next`. Currently, they are only visible in development mode.
=> chore: show react examples in production

articles/hilla/lit/guides/forms/reference.adoc
Pull request 2733 was merged and closed without language being checked. This PR covers the documents affected by that earlier PR.
=> Add reference.adoc - PR 2733

articles/components/icons/index.adoc
Add a note about importing icon collections explicitly when using the Web component or React icon.
Closes https://github.com/vaadin/react-components/issues/218
=> chore: advise importing icon collections client-side

articles/components/menu-bar/index.adoc
Part of https://github.com/vaadin/platform/issues/5018
=> docs: document menu-bar reverse-collapse

articles/flow/routing/navigation.adoc
HasRouteParameters interface does not exist, the correct name is HasUrlParameter.
=> fix: fix interface name in navigation docs

frontend/demo/component/datepicker/react/date-picker-custom-validation.tsx, frontend/demo/component/timepicker/react/time-picker-custom-validation.tsx
Part of #3212 
UPD: the `DateTimePicker` is currently blocked by https://github.com/vaadin/hilla/issues/2134
=> docs: add date-picker and time-picker custom validator React example

frontend/demo/component/accordion/react/accordion-summary.tsx
Fixes #3210 
Aligned `accordion-summary.tsx` (React) with `accordion-summary.ts` (Lit), added `AccordionHeading` and binder.
=> docs: update accordion summary React example to use binder

frontend/demo/component/custom-field/custom-field-basic.ts, frontend/demo/component/custom-field/custom-field-size-variants.ts, frontend/demo/component/custom-field/react/custom-field-basic.tsx, frontend/demo/component/custom-field/react/custom-field-size-variants.tsx, frontend/demo/component/formlayout/form-layout-custom-field.ts, frontend/demo/component/formlayout/react/form-layout-custom-field.tsx, src/main/java/com/vaadin/demo/component/customfield/DateRangePicker.java, src/main/java/com/vaadin/demo/component/customfield/MoneyField.java, src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomField.java
Replaced `title` attribute with `accessibleName` property and `setAriaLabel()` Java API added in 24.1.
This keeps the code cleaner, reduces usage of `executeJs` and directly accessing internal `focusElement`.
Also, `aria-label` is generally considered a better option for screen readers than the title attribute.
=> docs: replace title attribute usage with accessibleName

frontend/demo/component/app-layout/react/app-layout-basic.tsx, frontend/demo/component/avatar/react/avatar-abbreviation.tsx, frontend/demo/component/button/react/button-disable-long-action.tsx, frontend/demo/component/combobox/react/combo-box-auto-open.tsx, frontend/demo/component/combobox/react/combo-box-custom-entry-1.tsx, frontend/demo/component/combobox/react/combo-box-presentation.tsx, frontend/demo/component/grid/react/grid-external-filtering.tsx, frontend/demo/component/gridpro/react/grid-pro-enter-next-row.tsx, frontend/demo/component/scroller/react/scroller-mobile.tsx, frontend/demo/component/side-nav/react/side-nav-labelled.tsx, frontend/demo/component/side-nav/react/side-nav-suffix.tsx, frontend/demo/component/tabs/react/tabsheet-prefix-suffix.tsx, frontend/demo/component/textarea/react/text-area-helper.tsx, frontend/demo/component/upload/react/upload-clear-button.tsx
Some React examples are using closing tags where it's not needed (as there are no children).
Updated these to keep the code cleaner and also to align with other React examples.
=> chore: use self-closing tags for React components in JSX

frontend/demo/component/grid/react/grid-column-freezing.tsx, frontend/demo/component/grid/react/grid-content.tsx
Remove workarounds related to https://github.com/vaadin/react-components/issues/129 since the issue has now been fixed
=> chore: remove grid auto-width workarounds from React examples

package-lock.json, package.json
Follow-up to #3201.
In the React adapter guide, `react-colorful` dependency was added, but it's missing from `package.json`. This PR adds it.
=> chore: add react-colorful dependency to package.json

frontend/demo/component/datetimepicker/react/date-time-picker-custom-validation.tsx
Fixes #3212
This is based on 24.4.0.alpha8 that comes with a Hilla fix needed for DTP validation to work.
=> docs: add DateTimePicker custom validation React example

articles/flow/styling/lumo/lumo-variants.adoc
Fixes #3215
Added Lit and React snippets for setting `theme` attribute and toggling it dynamically:
For other code snippets (setting `dark` theme globally and `compact` preset) I only added single TypeScript snippet.
=> docs: add Lit and React snippets to Lumo Variants page

frontend/demo/component/app-layout/app-layout-bottom-navbar.ts, frontend/demo/component/app-layout/app-layout-navbar.ts, frontend/demo/component/app-layout/app-layout-secondary-navigation.ts
Fixed some Lit TS examples to hide imports of `patchAppLayoutNavigation` and correctly apply `hidden-source-line` comments. Currently, some of the demos are rendered incorrectly due to those comments on wrong lines:
=> chore: fix hidden-source-line usage for navigation helper

frontend/demo/component/contextmenu/react/context-menu-left-click.tsx, frontend/demo/component/grid/react/grid-row-reordering.tsx, frontend/demo/component/gridpro/react/grid-pro-prevent-save.tsx, frontend/demo/component/notification/react/notification-rich.tsx
Some of our examples use `React.useEffect` instead of `useEffect`. Updated these to align them. Also run Prettier.
=> chore: align usage of React hooks to use named exports

articles/flow/create-ui/creating-components/mixins.adoc
In the documentation about using Mixins there was an error in example code
SampleTooltip should extend LitElement, not  LitTemplate
=> SampleTooltip in typescript extends LitElement, not LitTemplate

articles/flow/advanced/service-init-listener.adoc, articles/flow/integrations/spring/events.adoc
Adds a similar page for events as for CDI integration. A list of events that are published automatically and can be listened to.
Related-to: vaadin/flow#14086
=> docs: add Spring Events article

articles/tools/observability/index.asciidoc
The text "to observe the frontend" is already a part of the link - no need to repeat it
=> Remove duplicated text

articles/upgrading/index.adoc
Nowadays, it's common to use a [Java toolchain](https://docs.gradle.org/current/userguide/toolchains.html) instead of `sourceCompatibility` and `targetCompatibility`.
=> docs: Use Gradle toolchain to specify Java version in upgrade guide

articles/routing/navigation.asciidoc
HasRouteParameters interface does not exist, the correct name is HasUrlParameter.
=> fix: fix interface name in navigation docs (CP: latest)

dspublisher/dspublisher-scripts.js
Make `npm run dspublisher:clean` also remove `node_modules` and `frontend/generated`
See https://vaadin.slack.com/archives/CQUQWJ4KU/p1713512265294569?thread_ts=1713511058.904139&cid=CQUQWJ4KU
=> fix: make dspublisher:clean also remove node_modules

frontend/demo/component/select/react/select-basic-features.tsx
Mentioned issue has been resolved and the features work now.
=> chore: enable icon and tooltip in select example

articles/components/checkbox/index.adoc, frontend/demo/component/checkbox/checkbox-readonly.ts, frontend/demo/component/checkbox/react/checkbox-readonly.tsx, src/main/java/com/vaadin/demo/component/checkbox/CheckboxReadonly.java
Fixes #3358
Added `readonly` examples for the CheckboxGroup and updated the corresponding article.
=> docs: add CheckboxGroup read-only state examples

articles/components/checkbox/index.adoc, frontend/demo/component/checkbox/checkbox-group-basic-features.ts, frontend/demo/component/checkbox/checkbox-required.ts, frontend/demo/component/checkbox/react/checkbox-group-basic-features.tsx, frontend/demo/component/checkbox/react/checkbox-required.tsx, src/main/java/com/vaadin/demo/component/checkbox/CheckboxGroupBasicFeatures.java, src/main/java/com/vaadin/demo/component/checkbox/CheckboxRequired.java
Fixes #3359
- Added an example of using `required` on individual checkbox
- Added individual checkbox with `helperText` to basic features
=> docs: add docs for Checkbox required and helper features

articles/components/grid-pro/index.adoc, frontend/demo/component/gridpro/grid-pro-cell-editability.ts, frontend/demo/component/gridpro/react/grid-pro-cell-editability.tsx, src/main/java/com/vaadin/demo/component/gridpro/GridProCellEditability.java
Fixes #3355
Added the example based on the Flow components IT for the feature:
=> docs: add examples for GridPro cell editability

articles/hilla/lit/guides/upgrading/index.adoc
This fixes the diff highlighting in the Hilla upgrade guide article. The output is much better that before with just some `-` and `+` in the code blocks:
=> fix diff highlighting in Hilla upgrade guide

articles/flow/integrations/hilla.adoc
If the function is not capitalized, changes to the view are not immediately applied in the browser.
=> chore: capitalize react view function name

articles/flow/integrations/cdi/index.adoc, articles/tools/mpr/configuration/mpr-cdi-tutorial.adoc
As now `hilla-dev` marks `hilla-endpoints` dependency as optional and, if no `vaadin-spring-boot-starter` in a project, the Hilla endpoints are not added, i.e. no need to exclude.
Note that the `hilla-dev` module will be removed soon as a part of unification for Vaadin HotSwap agent plugin.
=> Hilla-dev exclusions are not needed for non-Spring projects

frontend/demo/component/grid/grid-drag-drop-filters.ts, frontend/demo/component/grid/grid-drag-rows-between-grids.ts, frontend/demo/component/grid/grid-row-reordering.ts, frontend/demo/component/grid/react/grid-drag-drop-filters.tsx, frontend/demo/component/grid/react/grid-drag-rows-between-grids.tsx, frontend/demo/component/grid/react/grid-row-reordering.tsx, src/main/java/com/vaadin/demo/component/grid/GridDragDropFilters.java, src/main/java/com/vaadin/demo/component/grid/GridDragRowsBetweenGrids.java, src/main/java/com/vaadin/demo/component/grid/GridRowReordering.java
Currently, all the grids in the drag & drop examples section use static drop mode values. This means that the drop indicator is shown for them even while dragging unrelated things like text or rows from another example:
https://github.com/vaadin/docs/assets/1222264/f780e578-fe75-41af-b1ed-4ae7725f8753
This PR fixes the issue by updating the examples to dynamically apply the drop mode when a row drag starts and clear the drop mode when the row drag ends.
Related to https://github.com/vaadin/flow-components/issues/6306
=> fix: do not use static drop mode for grids in dnd examples

articles/hilla/guides/routing.adoc
Makes it easier to find the reference section by searching for 'ViewConfig'
=> Mention ViewConfig in related options reference

articles/lit/reference/gradle.adoc
https://github.com/vaadin/hilla/issues/2197
The commands given by the document missed an space.
文档给出的指令漏了个空格。
=> docs: The commands given by the document missed an space.

articles/flow/security/enabling-security.adoc
change "Could Not Vavigate" to "Could Not Navigate"
=> fix typo in enabling-security article

frontend/demo/foundation/lumo-tokens.ts
Manually include utility classes in `lumo-tokens.ts`.
This fixes the classes missing from the examples at https://vaadin.com/docs/latest/styling/lumo/utility-classes#list-of-utility-classes
=> fix: manually include utility classes

pom.xml
Use a specific commons-io version to fix spreadsheet examples
Note: This is to be revered later once a version required by poi installs without forcing the version in docs.
=> fix: use specific commons-io version to fix spreadsheet examples

frontend/demo/component/grid/grid-styling.ts, frontend/demo/component/grid/react/grid-styling.tsx, frontend/themes/docs/grid-styling.css, src/main/java/com/vaadin/demo/component/grid/GridStyling.java
Fixes #3442
This essentially reverts #2866 as the related issue https://github.com/vaadin/web-components/issues/7447 is now fixed.
=> docs: remove no longer needed class name from grid example

src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsVerticalLayoutVerticalAlignment.java, src/main/java/com/vaadin/demo/component/charts/charttypes/ChartTypeAreaSplineRange.java, src/main/java/com/vaadin/demo/component/checkbox/CheckboxGroupBasicFeatures.java, src/main/java/com/vaadin/demo/component/combobox/ComboBoxReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/datepicker/DatePickerReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerBasicFeatures.java, src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/emailfield/EmailFieldReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/login/LoginOverlayCustomFormArea.java, src/main/java/com/vaadin/demo/component/numberfield/NumberFieldBasicFeatures.java, src/main/java/com/vaadin/demo/component/numberfield/NumberFieldReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/passwordfield/PasswordFieldBasicFeatures.java, src/main/java/com/vaadin/demo/component/passwordfield/PasswordFieldConstraints.java, src/main/java/com/vaadin/demo/component/passwordfield/PasswordFieldReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/radiobutton/RadioButtonGroupBasicFeatures.java, src/main/java/com/vaadin/demo/component/select/SelectReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/textarea/TextAreaReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/textfield/TextFieldReadonlyAndDisabled.java, src/main/java/com/vaadin/demo/component/timepicker/TimePickerReadonlyAndDisabled.java
Found these after running `mvn formatter:format` and extracted to separate PR to make the one about formatting smaller.
=> chore: format demo exporter lines for Java examples

frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-margin.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-padding.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing-variants.ts, frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing.ts, src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutMargin.java, src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutPadding.java, src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutSpacing.java, src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutSpacingVariants.java
Fixes #3551
Updated incorrect classes passed to `DemoExporter`. Also updated `@customElement` accordingly.
These examples had this problem since adding them in 38467a301bc744b223019d47f8540cccba6f93d0
=> fix: use correct class for basic layouts DemoExporter

src/main/java/com/vaadin/demo/component/emailfield/EmailFieldBasic.java
The manual `setInvalid` call is unnecessary, as setting an invalid email already makes the component invalid.
=> refactor: remove unnecessary setInvalid call

articles/components/button/index.adoc, articles/components/dialog/index.adoc, articles/components/upload/file-handling.adoc
Update group names of inline code examples to match the group names of rendered code examples.
=> docs: update source group names

webpack.dspublisher.js
This fixes the following error:
```
Module not found: Error: Can't resolve 'Frontend/generated/flow/ReactAdapter.js'
in '/Users/serhii/vaadin/docs/frontend/generated/jar-resources'
```
The file is there but has `.tsx` extension which isn't currently resolved.
=> fix: allow to resolve tsx file extension

articles/components/popover/index.adoc, articles/components/popover/styling.adoc, frontend/demo/component/popover/popover-anchored-dialog.ts, frontend/demo/component/popover/popover-arrow.ts, frontend/demo/component/popover/popover-dropdown-field.ts, frontend/demo/component/popover/popover-interactive-tooltip.ts, frontend/demo/component/popover/popover-modal.ts, frontend/demo/component/popover/popover-notification-panel.ts, frontend/demo/component/popover/popover-positioning.ts, frontend/demo/component/popover/popover-user-menu.ts, frontend/demo/component/popover/react/popover-anchored-dialog.tsx, frontend/demo/component/popover/react/popover-arrow.tsx, frontend/demo/component/popover/react/popover-dropdown-field.tsx, frontend/demo/component/popover/react/popover-interactive-tooltip.tsx, frontend/demo/component/popover/react/popover-modal.tsx, frontend/demo/component/popover/react/popover-notification-panel.tsx, frontend/demo/component/popover/react/popover-positioning.tsx, frontend/demo/component/popover/react/popover-user-menu.tsx, frontend/demo/init.ts, frontend/themes/docs/document.css, frontend/themes/docs/popover-notification-panel.css, src/main/java/com/vaadin/demo/component/popover/PopoverAnchoredDialog.java, src/main/java/com/vaadin/demo/component/popover/PopoverArrow.java, src/main/java/com/vaadin/demo/component/popover/PopoverDropdownField.java, src/main/java/com/vaadin/demo/component/popover/PopoverInteractiveTooltip.java, src/main/java/com/vaadin/demo/component/popover/PopoverModal.java, src/main/java/com/vaadin/demo/component/popover/PopoverNotificationPanel.java, src/main/java/com/vaadin/demo/component/popover/PopoverPositioning.java, src/main/java/com/vaadin/demo/component/popover/PopoverUserMenu.java
Added Popover documentation and live examples based on the [document](https://docs.google.com/document/d/1ucCxGcHK6xtjTvepL9UzMqESSaPEMUaks70uyJL6UPE/edit?usp=sharing).
=> docs: add Popover documentation and live examples

frontend/demo/component/custom-field/react/custom-field-native-input.tsx, frontend/demo/component/textfield/react/text-field-constraints.tsx, frontend/demo/component/textfield/text-field-constraints.ts, src/main/java/com/vaadin/demo/component/textfield/TextFieldConstraints.java
Added missing escaping in Java examples and removed incorrect escaping in React examples. This makes the pattern property work in those examples.
=> fix: escape special chars correctly in pattern

frontend/demo/component/popover/popover-anchored-dialog.ts
Fixes a warning for the `popover-anchored-dialog.ts`
```
warn /Users/serhii/vaadin/docs/articles/components/popover/index.adoc, line 3 - detected unclosed tag 'snippet' starting at line 36 of include file: /Users/serhii/vaadin/docs/frontend/demo/component/popover/popover-anchored-dialog.ts
```
=> fix: remove incorrect unclosed snippet tag

articles/components/popover/index.adoc
Let's add the inline `since` tag since we can't have one on the title due to the tabbed page.
=> docs: add since tag to popover description

articles/hilla/guides/production/production-build.adoc, articles/hilla/lit/guides/production/production-build.adoc
These have been removed long ago, see https://github.com/vaadin/flow/pull/13083 (and Vite is now used instead of webpack).
=> docs: remove mentions of deleted webpackTemplate

frontend/demo/auth/LoginView.tsx, frontend/demo/auth/index.tsx, frontend/demo/auth/routes.tsx, frontend/demo/component/formlayout/form-layout-custom-field.ts, frontend/demo/component/grid/react/grid-column-filtering.tsx, frontend/demo/component/grid/react/grid-column-freezing.tsx, frontend/demo/component/gridpro/react/grid-pro-prevent-save.tsx, frontend/demo/component/tree-grid/react/tree-grid-column.tsx, frontend/demo/component/tree-grid/react/tree-grid-scroll-to-index.tsx, frontend/demo/component/tree-grid/tree-grid-scroll-to-index.ts, frontend/demo/flow/integration/react/rgba-color-picker.tsx
Fixed some ESLint and Prettier warnings related to unused imports and formatting.
The `rgba-color-picker` code example required `prettier-ignore` so that the comment would remain in place:
=> chore: remove unused imports, apply Prettier formatting

.eslintrc.json, package-lock.json, package.json
Adds the `simple-import-sort` ESLint plugin to ensure the consistent import order in JS/TS examples. The plugin configuration is based on that in the `web-components` repo.
=> chore: add simple-import-sort ESLint plugin

articles/hilla/lit/reference/gradle.adoc
The currently documented properties are outdated and no longer work
=> fix(gradle): replace outdated properties from hilla to vaadin

articles/tools/sso/getting-started/hilla.adoc
The npm scope was changed from `@hilla` to `@vaadin` in the latest version: https://github.com/vaadin/sso-kit/commit/b3b1a4068ce60164dca8d7fd4d8c553dcf956b7a
Updated inline code examples to use correct npm package name. Also changed to use single quotes.
=> docs: update outdated Hilla SSO kit npm package name

articles/flow/integrations/hilla.adoc, articles/flow/integrations/react.adoc, articles/getting-started/tutorial/hilla/first-view.adoc, articles/getting-started/tutorial/hilla/layout.adoc, articles/getting-started/tutorial/hilla/reconnects.adoc, articles/getting-started/tutorial/hilla/second-view.adoc, articles/getting-started/views/index.adoc, articles/hilla/guides/flow-integration.adoc, articles/hilla/guides/routing.adoc, articles/hilla/guides/testing.adoc, articles/hilla/lit/guides/forms/binder-validation.adoc, articles/hilla/lit/guides/forms/binding-arrays.adoc, articles/hilla/lit/guides/forms/form-images.adoc, articles/hilla/lit/guides/forms/reference.adoc, articles/hilla/lit/guides/forms/vaadin-components.adoc, articles/hilla/lit/guides/reactive-endpoints.adoc, articles/hilla/lit/guides/upgrading/index.adoc, articles/hilla/lit/start/basics/index.adoc, articles/hilla/tutorial/index.adoc
Updated inline code examples to use single quotes (mostly in imports). Also changed `{Button}` to `{ Button }` etc.
=> docs: use single quote in inline React examples

articles/control-center/getting-started/index.adoc
This improves the look of the code references (now rendering as encircled numbers). It also changes the command to get the passkey so that it aligns with the instructions Control Center gives the user.
=> Make some improvements to the Control Center getting started page

articles/hilla/lit/reference/type-conversion.adoc
As a follow-up to https://github.com/vaadin/docs/pull/3670, this PR adds missing version information to new features.
=> fix: add version information for Hilla paper cuts

articles/tools/ai-form-filler/index.adoc, articles/tools/appsec/index.adoc, articles/tools/azure-cloud/index.adoc, articles/tools/collaboration/index.adoc, articles/tools/copilot/index.adoc, articles/tools/designer/index.adoc, articles/tools/dspublisher/index.adoc, articles/tools/kubernetes/index.adoc, articles/tools/modernization-toolkit/index.adoc, articles/tools/mpr/index.adoc, articles/tools/observability/index.adoc, articles/tools/sso/index.adoc, articles/tools/start/index.adoc, articles/tools/swing/index.adoc
Some subfolders were missing order which caused them to be incorrectly sorted with the Astro version.
=> chore: align order for tools section subfolders

frontend/demo/init.ts
This was first added in c6e10c30ea5ab2d66c0a2f2b15763f10a4baccc7 - back then there was an issue in Hilla.
Tested the `v23` branch and the workaround is no longer necessary since corresponding types e.g. `AppointmentModel` already declare correct type for the static `createEmptyValue()` method. Apparently it was fixed by https://github.com/vaadin/hilla/pull/656 which was included to Hilla 1.4 used by the `v23` branch (which also uses Vite 3 mentioned in the PR).
Note: the workaround is already removed from `latest` branch in https://github.com/vaadin/docs/pull/2384.
=> chore: remove obsolete Hilla workaround from v23 branch

frontend/demo/component/icons/icons-color.ts, frontend/demo/component/icons/icons-padding.ts, frontend/demo/component/icons/icons-sizing.ts, frontend/demo/component/icons/react/icons-color.tsx, frontend/demo/component/icons/react/icons-padding.tsx, frontend/demo/component/icons/react/icons-sizing.tsx, frontend/demo/component/icons/react/svg-sprites.tsx, frontend/demo/component/icons/react/svg-standalone.tsx, frontend/demo/component/icons/svg-sprites.ts, frontend/demo/component/icons/svg-standalone.ts, frontend/types.d.ts
Make the svg imports in icon examples Vite-friendly.
This is a required change in preparation for DSP3.
Confirmed that the change is also compatible with DSP2.
=> refactor: make svg imports in icon examples vite-friendly

frontend/demo/services/mocks.ts, vite.dspublisher.ts
Alias `Frontend/generated/endpoints` in the dsp Vite config similarly to how it's currently in the [dsp webpack config](https://github.com/vaadin/docs/blob/284e7766058094fb7f49cb4a3dca4e5c966733f5/webpack.dspublisher.js#L93-L98).
Also, remove the `/connect` proxy setup since it's unused.
Fixes https://github.com/orgs/vaadin/projects/75/views/1?pane=issue&itemId=83263680
=> fix: add endpoint mocks alias to dsp vite config

vite.dspublisher.ts
`vite.dspublisher.ts` needs to import `vite.generated.ts` to adopt some of its configuration. `vite.generated.ts` accesses `__dirname`, which doesn't resolve with Astro's Vite config without the variable being defined first. This results in an error (`"__dirname is not defined"`) getting thrown on import by default.
The current workaround modifies the `vite.generated.ts` file to define `const __dirname` before importing it. This PR refactors `vite.dspublisher.ts` to use a less intrusive workaround that instead declares `__dirname` in the global object.
=> refactor: cleanup dsp vite dirname workaround

package-lock.json, package.json, vite.dspublisher.ts
Added Vite config for DSP3. 
Note, I had to pin `magic-string` as Vite 3 brings an older version without `replaceAll()` support.
=> feat: add Vite config for Astro DSP to v23 branch

articles/mpr/configuration/adding-legacy-components.asciidoc, articles/mpr/configuration/custom-ui.asciidoc, articles/mpr/configuration/legacy-widgetset.asciidoc, articles/mpr/configuration/limitations.asciidoc, articles/mpr/configuration/production-mode.asciidoc, articles/mpr/configuration/push.asciidoc, articles/mpr/configuration/session.asciidoc, articles/mpr/introduction/step-1-maven-v7.asciidoc, articles/mpr/introduction/step-1-maven-v8.asciidoc, articles/mpr/introduction/step-1-migration-guide.asciidoc, articles/mpr/introduction/step-2-legacy-servlets.asciidoc, articles/mpr/introduction/step-3-cdi.asciidoc, articles/mpr/introduction/step-3-legacy-uis.asciidoc, articles/mpr/introduction/step-3-navigator.asciidoc, articles/mpr/introduction/step-3-no-framework.asciidoc, articles/mpr/introduction/step-3-spring-boot.asciidoc, articles/mpr/introduction/step-4-ui-parameters.asciidoc, articles/mpr/introduction/step-5-adding-legacy-components.asciidoc
Fixed some links in V10 MPR docs to not use capitalized `Overview` as this points to "Page not found" page.
=> fix: use correct links to MPR overview page in V10 docs

articles/building-apps/application-layer/application-services.adoc, articles/building-apps/application-layer/persistence/repositories/index.adoc, articles/building-apps/application-layer/persistence/repositories/pluggable.adoc, articles/building-apps/architecture/monoliths.adoc, articles/components/notification/styling.adoc, articles/flow/advanced/custom-instantiators.adoc, articles/flow/create-ui/shortcut.adoc, articles/flow/testing/end-to-end/advanced-concepts.adoc, articles/flow/tutorial/project-setup.adoc, articles/upgrading/index.adoc
Fixed some typos detected by `cspell` and also removed trailing whtiespaces.
=> chore: fix some typos, remove trailing whitespaces

articles/tools/modernization-toolkit/classic-components.adoc
Discovered these when building docs locally:
```
Broken cross reference /tools/routing/exceptions in C:\Users\serhii\docs\articles\tools\modernization-toolkit\classic-components.adoc
Broken cross reference /tools/create-ui/shortcut in C:\Users\serhii\docs\articles\tools\modernization-toolkit\classic-components.adoc
```
=> docs: fix broken cross-references in Classic Components

frontend/demo/component/avatar/avatar-image.ts, frontend/demo/component/avatar/react/avatar-image.tsx, frontend/demo/component/button/button-images.ts, frontend/demo/component/button/react/button-images.tsx, frontend/demo/component/login/login-overlay-mockup.ts, frontend/demo/component/login/react/login-overlay-mockup.ts, frontend/demo/component/scroller/react/scroller-both.tsx, frontend/demo/component/scroller/scroller-both.ts, frontend/types.d.ts
Same as #3803 but for `.jpg` and `.png` imports.
The reason why this is needed is the fact that without `?url`, Astro processes imports and returns `ImageMetadata` object instead of just `src` (which is what Vite does) - see https://github.com/withastro/astro/issues/5924 (the issue was closed as intended).
=> refactor: make image imports in TS examples work with Astro

articles/control-center/getting-started/index.adoc
Part of https://github.com/vaadin/control-center/issues/658
Improves the command to retrieve the Control Center passkey. It now works for Windows Command Prompt, Windows PowerShell, and Mac Terminal.
=> [Control Center] Improve the passkey command

vite.dspublisher.ts
For some reason in V23, embedded web components have imports that look like this:
```js
import {applyTheme} from '/generated/theme';
```
This is different from V24 where imports have correct `Frontend` prefix:
```js
import {applyTheme} from 'Frontend/generated/theme.js';
```
Added the alias so that Astro DSP build works correctly.
=> fix: add missing theme alias for embedded components to V23

vite.dspublisher.ts
Added a workaround similar to the one included to v23 branch to avoid following errors:
```
Uncaught (in promise) ReferenceError: JSCompiler_renameProperty is not defined
at get observedAttributes (chunk-GOCCCYYU.js?v=034aa3b9:3713:17)
at defineCustomElement
```
I thought it was only happening with legacy Polymer elements but we also reproduced it in V24.
In particular, can be reproduced on the Board page http://localhost:8000/components/board
=> chore: add workaround to rewrite JSCompiler_renameProperty

frontend/demo/component/board/example-statistics.ts, frontend/demo/component/board/react/ExampleStatistics.tsx
This fixes the hydration warning on the Board component page due to incorrect HTML tags usage:
```
Warning: validateDOMNesting(...): <th> cannot appear as a child of <thead>.
at th
at thead
at table
at div
at div
at ExampleStatistics
```
=> fix: use tr element in thead to fix hydration warning

frontend/demo/component/formlayout/form-layout-colspan.ts
Fix for the following error on the Form Layout page:
```
Uncaught (in promise) NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "form-layout-custom-layout" has already been used with this registry
at chunk-CJV2DPYP.js?v=e35ab810:13:20
at __decorateClass (form-layout-colspan.ts:7:57)
at form-layout-colspan.ts:45:11
```
=> fix: use correct tag name in form-layout colspan TS example

frontend/demo/component/formlayout/form-layout-colspan.ts
Same as #3866 but for `v23` branch.
=> fix: use correct tag name in form-layout colspan TS example (v23)

frontend/demo/init-flow-components.ts
This should fix the following error on the Button page:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initDisableOnClick')
at Button.eval (eval at rE (FlowClient-CFpeFTrH.js:3:42450), <anonymous>:3:54)
```
=> fix: add Flow button JS import to init-flow-components

frontend/demo/component/crud/crud-editor-content.ts, frontend/demo/component/crud/react/crud-editor-content.tsx
This fixes the warning I noticed on the CRUD page by not setting empty array to responsive steps by default:
```
Invalid empty "responsiveSteps" array, at least one item is required. Using default 'responsiveSteps' instead.
```
This would also make the logic aligned with other examples where `responsiveSteps` is always set initially.
=> fix: set responsiveSteps initially to avoid warning

articles/control-center/getting-started/index.adoc
This removes the numbered comments erroneously added into code examples during the language check for #3887 .
=> [Control Center] Remove numbered comments from code examples

articles/control-center/application-deployment/index.adoc
Adds specific instructions for using local Kubernetes clusters such as minikube, KiND and k3s.
Fixes https://github.com/vaadin/control-center/issues/634
=> [Control Center] Clarify instructions for local clusters

articles/framework/advanced/advanced-javascript.asciidoc
This has finally been checked and the API is indeed so.
=> Remove TODO from advanced-javascript.asciidoc

frontend/demo/init-flow-components.ts
This file was moved in https://github.com/vaadin/flow-components/pull/6815 released in the latest 24.6 alpha.
=> fix: update import for disable on click functions

dspublisher/config/default.json, dspublisher/config/production.json, dspublisher/dspublisher-scripts.js, src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
Configures DSP to show Flow and React examples first. Also updates DSP to a new version that has that feature, and removes obsolete config options.
Closes https://github.com/vaadin/docs/issues/3351
=> chore: reorder example groups

articles/_preview-banner.adoc
Looks like so:
Usage:
```
:preview-feature: Dashboard
:feature-flag: com.vaadin.experimental.dashboardComponent
:feedback-url: https://vaadin.com/forum/t/vaadin-slider-element/167827
include::{articles}/_preview-banner.adoc[opts=optional]
```
- If `feature-flag` is omitted, the normal Preview admonition is rendered instead.
- If `feedback-url` is omitted, the paragraph is rendered without a link.
=> Added feature flag and feedback link versions of preview feature admonition

articles/components/upload/index.adoc
Document that upload now supports drag and drop of folders.
=> docs: upload folder drag and drop

README.md, articles/flow/advanced/modifying-the-bootstrap-page.adoc, articles/flow/configuration/pwa.adoc, articles/flow/integrations/hilla.adoc, articles/flow/security/enabling-security.adoc, articles/hilla/lit/guides/reactive-endpoints.adoc, articles/hilla/lit/guides/upgrading/index.adoc, articles/hilla/lit/start/faq.adoc
Old hilla.dev links redirect to vaadin.com now. This fix replaces those links in the latest Docs content with the final addresses they currently redirect to, removing the old links pointing to hilla.dev and removing redirections.
Example:
- Old link: https://hilla.dev
- New link: https://vaadin.com/hilla
=> Replace old hilla.dev links

articles/components/dashboard/index.adoc
Add Dashboard documentation for the `Persisting and Loading Widgets` section
=> docs: document dashboard persistence

frontend/demo/component/dashboard/dashboard-announcements.ts, frontend/demo/component/dashboard/react/dashboard-announcements.tsx
Also update the state widgets in Dashboard announcements example. Otherwise, the widgets can get reverted on state change:
https://github.com/user-attachments/assets/e5daaa7d-56dc-48ac-9e33-e97cf5a4855a
=> fix: store updated widgets in dashboard announcements example

articles/bakeryfw8/adding-a-view.asciidoc, articles/charts/productpage-external.asciidoc, articles/framework/articles/VaadinTutorialForSwingDevelopers.asciidoc, articles/framework/introduction-external.asciidoc, articles/spreadsheet/spreadsheet-overview.asciidoc
Removes redirections from version 8 docs content by changing a link's URL to the final address that URL redirects to.
=> Remove redirection chains from v8 content

articles/components/multi-select-combo-box/index.adoc
Fixes a cross-reference to combo box docs.
=> docs: update custom item presentation link

frontend/demo/component/details/details-content.ts, frontend/demo/component/details/details-disabled.ts, frontend/demo/component/details/details-filled.ts, frontend/demo/component/details/details-reverse.ts, frontend/demo/component/details/details-small.ts, frontend/demo/component/details/details-summary.ts
Current snippets for `vaadin-details` Lit examples are unnecessarily large (since these were added in https://github.com/vaadin/docs/pull/71).
While basic example was changed to only include relevant HTML in https://github.com/vaadin/docs/commit/20a20fc46f54f9f9ccfbf4e527eb9743ee9d47da, others were not. This PR fixes that.
=> docs: update snippet tags for details Lit examples

frontend/demo/component/select/react/select-custom-renderer-label.tsx
This workaround is no longer needed after adding `label` property to `vaadin-item` in https://github.com/vaadin/web-components/pull/6919.
See https://github.com/vaadin/react-components/issues/147 for the original issue where this specific case was mentioned.
=> docs: remove no longer needed item label attribute workaround

pom.xml
The `commons-io` version was fixed to 2.16.1 in https://github.com/vaadin/docs/pull/3500 to unbreak the Spreadsheet examples. Using the fixed version is no longer necessary as a newer library version gets installed by default.
=> chore: remove fixed commons-io version

articles/components/grid/styling.adoc
Use correct part names for rows/cells with opened details.
=> docs: fix grid part names

articles/flow/configuration/development-mode/node-js.adoc
=> fix: typo in .npmrc proxy example

articles/bakeryfw8/overview.asciidoc
- Remove link to live demo, as it is no longer active
- Replace link to start.vaadin.com with Maven Archetype doc page as start.vaadin.com cannot be used with Vaadin 8
=> Update Bakery Vaadin 8 page

articles/components/_styling-section-theming-props.adoc
Adds documentation for focus ring CSS properties for input fields.
=> docs: input field focus ring properties

articles/flow/integrations/spring/configuration.adoc
Current documentation for Vaadin URL mapping handling seems outdated and provides a wrong example code that causes application failure. This change updates the docs to provide more information and solutions to handle static resources.
Fixes #2768
=> fix: fix Vaadin url mapping documentation

frontend/demo/auth/LoginView.tsx
Related to https://github.com/vaadin/start/pull/3303
Currently, there is a following problem:
- On first failed login attempt, the `hasError.value` is set to `true` as expected,
- When editing some fields and clicking "Submit" again, the `vaadin-login-form` [resets](https://github.com/vaadin/web-components/blob/dc87442bb489e6d447c42fdcb95b4e2921abf86e/packages/login/src/vaadin-login-form-mixin.js#L62) its `error` state to `false`,
- On subsequent failed login attempt, the `hasError.value` is set to `true` again but from the React point of view, nothing changes since the above change to `false` was not propagated and therefore the component is not re-rendered.
Added `onErrorChanged` listener to make sure that we update `hasError.value` on the event from the component.
=> fix: update error in LoginView to make subsequent submit work

articles/flow/binding-data/components-binder.adoc, articles/flow/binding-data/index.adoc, frontend/demo/auth/LoginView.tsx
Fixes https://github.com/vaadin/docs/issues/3933
=> docs: make Forms more prominent in documentation

src/main/java/com/vaadin/demo/SecurityConfig.java
It blocks Flow examples and internal monitoring. Commented out, still available as code example.
=> fix: disable download security config

articles/components/horizontal-layout/index.adoc, articles/components/vertical-layout/index.adoc
Adds documentation for setting a custom spacing in horizontal and vertical layout.
Part of https://github.com/vaadin/flow-components/issues/6999
=> docs: ordered layouts custom spacing

frontend/demo/component/popover/popover-dropdown-field.ts, frontend/demo/component/popover/react/popover-dropdown-field.tsx, src/main/java/com/vaadin/demo/component/popover/PopoverDropdownField.java
Fixes #4147
Added logic to open on <kbd>Arrow Down</kbd> instead of focus as suggested, in addition to click.
This removes the need to set the custom `trigger` in TS examples since `click` is used by default.
Also fixed the width to match the field width (currently examples look broken due to overlay being more narrow).
=> fix: update popover dropdown field to open on arrow down

articles/components/rich-text-editor/index.adoc
Related to https://github.com/vaadin/web-components/issues/8766
=> docs: add note in RichTextEditor documentation about asRequired use

articles/components/charts/configuration.adoc, articles/flow/create-ui/web-components/introduction-to-webcomponents.adoc, articles/flow/security/advanced-topics/strict-csp.adoc, articles/tools/mpr/configuration/limitations.adoc
@mcollovati found that a title in https://github.com/vaadin/docs/blob/latest/articles/flow/security/advanced-topics/strict-csp.adoc was not formatted correctly because of a `pass` command not having a blank line following.
I have fixed this and several other similar formatting issues.
=> Fix several formatting issues

articles/getting-started/walk-through.adoc, articles/hilla/guides/full-stack-signals.adoc
Fixed a few typos:
- `licence` -> `license`
- `inserLast` -> `insertLast`
- `Opertaion` -> `Operation`
This also removed some trailing whitespaces (auto-formatting on save in VSCode).
=> chore: fix some typos and remove trailing whitespaces

articles/building-apps/security/add-login/flow.adoc, articles/building-apps/security/add-login/hilla.adoc, articles/building-apps/security/add-logout/hilla.adoc, articles/building-apps/security/protect-services/flow.adoc, articles/building-apps/security/protect-services/hilla.adoc, articles/building-apps/security/protect-views/flow.adoc, articles/building-apps/security/protect-views/hilla.adoc, articles/building-apps/views/add-router-layout/hilla.adoc, articles/building-apps/views/add-view/flow.adoc, articles/building-apps/views/add-view/hilla.adoc, articles/building-apps/views/add-view/index.adoc, articles/building-apps/views/navigate/flow.adoc, articles/building-apps/views/navigate/hilla.adoc, articles/building-apps/views/pass-data/query-parameters/hilla.adoc, articles/getting-started/walk-through.adoc
Updates the documentation so that it matches the structure of the walking skeleton after https://github.com/vaadin/walking-skeleton/pull/16 has been merged.
=> Skeleton structure updates

vite.dspublisher.ts
Currently running the docs app in development mode is broken: When opening the app in the browser, the browser either just keeps loading indefinitely or loads an initial page, but with none of the links working. Firefox sometimes shows this error:
```
UnhandledRejection: Astro detected an unhandled rejection. Here's the stack trace:
Error: Build failed with 1 error:
../../../../../../dev/vaadin/docs/node_modules/@vaadin/hilla-frontend/FluxConnection.js:44:16: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
at failureErrorWithLog (/Users/sascha/.npm/_npx/370bd51a675d5282/node_modules/@vaadin/dspublisher/node_modules/esbuild/lib/main.js:1472:15)
```
This is caused by a recent change in Hilla …
=> fix: enable top-level await for dependencies

articles/flow/integrations/react.adoc
The numbered callouts (2 and 3) are not aligned with the explanations below.
=> docs: reorder descriptions of annotations in integration example

articles/upgrading/index.adoc
configuration method is really called 'configure' but I am not sure I could correct the broken braces rendering.
=> Fix code example of configuring SecurityContext requireExplicitSave

articles/components/rich-text-editor/index.adoc
Fixed a finding from the comments. The actual tag used by Quill is `<s>` and not `<strikethrough>`.
=> docs: use correct HTML tag name for strike-through text

articles/components/combo-box/index.adoc, frontend/demo/component/combobox/combo-box-lazy-loading.ts, frontend/demo/component/combobox/react/combo-box-lazy-loading.tsx, frontend/demo/services/ComboBoxCountryService.ts, frontend/demo/services/mocks.ts, src/main/java/com/vaadin/demo/component/combobox/ComboBoxCountryRepository.java, src/main/java/com/vaadin/demo/component/combobox/ComboBoxCountryService.java, src/main/java/com/vaadin/demo/component/combobox/ComboBoxLazyLoading.java
Adds a section for how to implement lazy loading with combo box. This mainly showcases the newly added `setItemsPageable` and `useComboBoxDataProvider` APIs.
=> docs: combo box lazy loading

articles/testbench/testbench-overview.asciidoc
JDK 1.6 was a Vaadin 7 requirement, Vaadin 8 has required JDK 8 from the beginning.
=> Update JDK requirement in Vaadin 8 TestBench Overview

articles/building-apps/views/pass-data/query-parameters/flow.adoc
Adding the missing getLocation() to the query parameter handling snippet in the Flow code examples for V24.
=> Fixing the Flow Query Parameters code snippet

articles/hilla/lit/components/create.adoc, articles/hilla/lit/guides/upgrading/_styling.adoc, articles/styling/application-theme.adoc, articles/upgrading/_styling.adoc
Fixed two broken links: "style scopes" now returns 404 and the link to `next` branch navigates to main page.
Also fixed some wrong backtick for `@CssImport` annotation.
=> docs: fix broken Styling links and backticks

dspublisher/config/production.json
Configure the preferred example render groups feature added in https://github.com/vaadin/docs-app/pull/505. This would make live examples preferrably render the React or Lit live example. If none of those are present if falls back to the live example for the currently selected group.
=> chore: configure preferred example render groups

articles/flow/configuration/feature-flags.adoc
Since 24.8, Card and Dashboard components are not under preview. So they do not require the feature flag. Hence removed these two components from the feature flag doc and instead added the Master-Detail Layout that is still a preview feature in 24.8
=> Remove card and dashboard components from feature flag docs

articles/flow/testing/end-to-end/maven.adoc
Lazerycode plugin has not been updated for 4 years and attempts to load chrome driver from wrong place and wont work.
=> Change lazerycode plugin to WebDriverManager

articles/flow/testing/selenium.adoc
The exclusions are good to document, as they are needed due our license checker conflicting with them.
=> Update WebDriverManager dependency

articles/flow/advanced/service-executor.adoc, articles/flow/integrations/cdi/service-beans.adoc, articles/flow/integrations/quarkus.adoc, articles/flow/integrations/spring/configuration.adoc
=> chore: add documentation for Vaadin Executor

dspublisher/theme/global.css
Revert font weight back to semibold for docs headings.
Reason: Updated font face declarations will map the BOLD version of NB International Pro to headings with font weight of 600 or 700.
=> v23: Revert font weight back to semibold for docs headings

dspublisher/theme/global.css
Revert font weight back to semibold for docs headings.
Reason: Updated font face declarations will map the BOLD version of NB International Pro to headings with font weight of 600 or 700.
=> v10: Revert font weight back to semibold for docs headings

versions.json
Vaadin 25 has reached alpha status and a prerelease of the documentation needs to be published.
The default version still is Vaadin 24 pointing to vaadin.com/docs/latest.
Also, this version is build with noindex by build configuration in Jenkins to prevent it getting indexed by search engines.
=> Adds V25 prerelease to versions.json

articles/getting-started/prerequisites.adoc
If we link to React and TS, we should also have a link to Java
=> Add link to Java language as it is with React and TS

articles/components/popover/index.adoc, frontend/demo/component/popover/popover-anchored-dialog.ts, frontend/demo/component/popover/popover-arrow.ts, frontend/demo/component/popover/popover-dropdown-field.ts, frontend/demo/component/popover/popover-interactive-tooltip.ts, frontend/demo/component/popover/popover-modal.ts, frontend/demo/component/popover/popover-notification-panel.ts, frontend/demo/component/popover/popover-positioning.ts, frontend/demo/component/popover/popover-user-menu.ts, frontend/demo/component/popover/react/popover-dropdown-field.tsx, frontend/demo/component/popover/react/popover-interactive-tooltip.tsx, frontend/demo/component/popover/react/popover-notification-panel.tsx, frontend/demo/component/popover/react/popover-user-menu.tsx, frontend/themes/docs/document.css, frontend/themes/docs/styles.css, src/main/java/com/vaadin/demo/component/popover/PopoverUserMenu.java
Updated `vaadin-popover` examples:
- Replaced `overlayRole` with `role`
- Replaced `accessibleName` with `aria-label`
- Replaced `popoverRenderer` directive with light DOM content
- Preserved separate methods for some large templates
- Moved `.css` files from `document.css` to `styles.css`
Also changed wording to not use `overlay`.
=> docs: update popover docs for V25, do not use deprecated API

articles/components/avatar/styling.adoc, articles/components/combo-box/styling.adoc, articles/components/confirm-dialog/styling.adoc, articles/components/context-menu/styling.adoc, articles/components/crud/styling.adoc, articles/components/date-picker/styling.adoc, articles/components/dialog/styling.adoc, articles/components/login/index.adoc, articles/components/login/styling.adoc, articles/components/menu-bar/styling.adoc, articles/components/multi-select-combo-box/styling.adoc, articles/components/popover/index.adoc, articles/components/popover/styling.adoc, articles/components/select/styling.adoc, articles/components/time-picker/styling.adoc, articles/components/tooltip/styling.adoc, articles/styling/styling-components/parts-and-states.adoc
Updated Styling docs for overlay based components to use new part names.
=> docs: update overlay components styling docs for V25

pom.xml
Exclude observability kit from runtime to avoid getting errors like these in the logs:
```
ERROR 60835 --- [nio-8080-exec-5] c.v.observability.ObservabilityHandler   : Observability agent is not running
```
From what I can see observability kit is only in the dependencies so that the example code snippets compile, but these examples never actually run at runtime so the dependency should not be needed there. To exclude it:
- Change the scope to provided which should remove it from production builds
- Also exclude it from the Spring boot maven plugin, which otherwise still puts Maven dependencies with provided scope on the classpath when starting the app in dev mode
=> chore: exclude observability kit from runtime
