vaadin/docs

- frontend/demo/init.ts
Fixes https://github.com/vaadin/docs-app/issues/178
> Use Lumo properties for code example default styles

- articles/themes/application-theme.asciidoc
Update the documentation for reusable theme
to expect less knowledge about project structure.
Fixes vaadin/flow#9586
> Fix: Update reusable theme documentation

- articles/theming/application-theme.asciidoc
> feat: Add parent theme documentation

- articles/theming/application-theme.asciidoc
- articles/theming/src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponent.java
- articles/theming/src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java
> Feat: add embedded component theme example

- articles/theming/application-theme.asciidoc
Resolves https://github.com/vaadin/flow/issues/9693
> Add docs for application theme importCss config

- articles/flow/web-components/integrating-a-web-component.asciidoc
> fix: use working link for add-on starter

- articles/theming/application-theme.asciidoc
Fixes: https://github.com/vaadin/flow/issues/9596
> Add a note about webpack error upon theme file removal

- articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
Added some documentation for custom events typings and removed the corresponding section from "limitations".
> docs: document TS custom events typings

- articles/flow/advanced/tutorial-push-configuration.asciidoc
Remove " or individual views of your application." as it is wrong information.
Fixes: https://github.com/vaadin/flow-and-components-documentation/issues/1406
> Remove " or individual views of your application."

- articles/flow/advanced/push-configuration.asciidoc
> Remove  "or individual views of your application"

- articles/theming/creating-a-custom-theme.asciidoc
> Add note for importing in sub folders.

- articles/flow/spring/tutorial-spring-basic-mvc.asciidoc
Split the code into 2 classes.
See this ticket : https://github.com/vaadin/docs/issues/117
> Update Spring MVC example

- articles/flow/advanced/osgi-basic.asciidoc
Related-to: https://github.com/vaadin/osgi/issues/22
> fix: Fix OSGi docs as per PiT feedback

- articles/ce/going-to-production.asciidoc
Update CE documentation reflecting the latest changes in configuration.
> CE: add docs for configuration auto-detection and setDataDir

- articles/ce/tutorial.asciidoc
Cherry-picked from latest.
Also includes some rewording that wasn't backported previously.
> CE: Update tutorial to discourage PushMode.MANUAL usage (#127)

- articles/fusion/pwa/cache-client-side-data.asciidoc
Fixes https://github.com/vaadin/flow/issues/9837
> clarify how to import cacheable function

- .github/styles/Vocab/Docs/accept.txt
- articles/guide/installing/frontend.asciidoc
- articles/guide/installing/overview.asciidoc
> Frontend package installation with pnpm instructions

- articles/ce/collaboration-avatar-group.asciidoc
- articles/ce/collaboration-binder.asciidoc
- articles/ce/going-to-production.asciidoc
- articles/ce/topic-api.asciidoc
- articles/ce/tutorial.asciidoc
Closes https://github.com/vaadin/collaboration-engine-internal/issues/517
> Remove render and group directive from code blocks

- .github/styles/Vocab/Docs/accept.txt
- articles/ce/collaboration-avatar-group.asciidoc
- articles/ce/collaboration-binder.asciidoc
- articles/ce/overview.asciidoc
- articles/ce/topic-api.asciidoc
- articles/ce/tutorial.asciidoc
Note: this fixes only errors, not the warnings.
Fix https://github.com/vaadin/collaboration-engine-internal/issues/511
> Fix Vale errors in CE docs

- .github/styles/Vocab/Docs/accept.txt
- articles/ce/collaboration-avatar-group.asciidoc
- articles/ce/collaboration-binder.asciidoc
- articles/ce/going-to-production.asciidoc
- articles/ce/overview.asciidoc
- articles/ce/topic-api.asciidoc
- articles/ce/tutorial.asciidoc
> CE cherry-picks to v14

- .github/styles/Vaadin/AdmonitionTitle.yml
The link points to a wiki page that tells exactly what to do to fix the issue.
> chore: add a link for the AdmonitionTitle Vale rule

- articles/ds/components/checkbox/index.asciidoc
- articles/ds/components/combo-box/index.asciidoc
- articles/ds/components/date-picker/index.asciidoc
- articles/ds/components/date-time-picker/index.asciidoc
- articles/ds/components/email-field/index.asciidoc
- articles/ds/components/index.asciidoc
- articles/ds/components/number-field/index.asciidoc
- articles/ds/components/password-field/index.asciidoc
- articles/ds/components/radio-button/index.asciidoc
- articles/ds/components/select/index.asciidoc
- articles/ds/components/text-area/index.asciidoc
- articles/ds/components/text-field/index.asciidoc
- articles/ds/components/time-picker/index.asciidoc
- articles/ds/overview.asciidoc
- package.json
- scripts/docbuilder-init.js
Relates to https://github.com/vaadin/docs-app/issues/175
> feat: add custom ds init script

- articles/fusion/advanced/endpoints-method-validation.asciidoc
EnpointValidationException -> EndpointValidationException
> Fixed typo

- articles/404.asciidoc
- scripts/dspublisher-init.js
Needs https://github.com/vaadin/docs-app/pull/224
> feat: add 404 page

- articles/ds/components/avatar/index.asciidoc
- articles/ds/foundation/_shared.asciidoc
This enables changing `DOCS_ARTICLES_PATH`
> fix: use relative ds cross references

- articles/flow/integrations/osgi/tutorial-osgi-basic.asciidoc
> chore: mention necessity to register frontend resources explicitly

- articles/fusion/advanced/typescript-client.asciidoc
- articles/fusion/application/accessing-backend.asciidoc
- articles/fusion/forms/appendix-vaadin-components.asciidoc
- articles/fusion/forms/overview.asciidoc
- articles/fusion/quick-start-tutorial.asciidoc
- articles/fusion/security/authentication.asciidoc
- articles/fusion/security/configuring.asciidoc
- frontend/demo/fusion/errorhandling/catch-error.ts
- frontend/demo/fusion/errorhandling/catch-invalid-args.ts
- frontend/demo/fusion/forms/contact-form.ts
- frontend/demo/pwa/offline/ts-view-with-endpoint.ts
- package.json
- pom.xml
Connected to vaadin/flow#7176
Depends on vaadin/flow#9972
Depends on #152
> Use endpoint wrapper exports

- articles/flow/styling/creating-a-custom-theme-class.asciidoc
- articles/flow/styling/custom-theme-configuration.asciidoc
- articles/flow/styling/custom-theme-packaging.asciidoc
- articles/flow/styling/custom-theme.asciidoc
- articles/flow/styling/overview.asciidoc
- articles/flow/styling/src/main/java/com/vaadin/flow/tutorial/theme/IntegratingComponentTheme.java
- articles/flow/styling/using-themes.asciidoc
Add the custom theme feature documentation
to v14 branch.
Part of vaadin/flow#9983
> feat: Add documentation about custom theme

- articles/ds/charts/java-api/charts-migrating-from-earlier-version.asciidoc
Part of https://github.com/vaadin/vaadin-charts/issues/562
> docs: add session of how to use Charts 9 in V14

- articles/guide/contributing/editor-settings-intellij-idea.asciidoc
> Add note about the IDEA problem

- articles/ds/components/confirm-dialog/index.asciidoc
- frontend/demo/component/confirmdialog/confirm-dialog-basic-preview.ts
- frontend/demo/component/confirmdialog/confirm-dialog-cancel-button.ts
- frontend/demo/component/confirmdialog/confirm-dialog-confirm-button.ts
- frontend/demo/component/confirmdialog/confirm-dialog-reject-button.ts
Requires https://github.com/vaadin/docs/pull/171
> Add confirm dialog TS examples

- frontend/themes/theme.js
- package.json
- webpack.dspublisher.js
Fixes https://github.com/vaadin/docs-app/issues/259
> fix: determine themes path from the theme in use

- articles/ce/collaboration-avatar-group.asciidoc
- articles/ce/collaboration-message-list.asciidoc
- articles/ce/overview.asciidoc
- pom.xml
- src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
Resolves https://github.com/vaadin/collaboration-engine-internal/issues/554
> Add CE message list & input docs

- articles/fusion/security/authentication.asciidoc
- articles/fusion/security/configuring.asciidoc
- articles/fusion/security/intro.asciidoc
- articles/guide/upgrading.asciidoc
Update security docs and upgrade guide to reflect this breaking change.
> fix: @DenyAll is now the default policy

- .github/styles/Vocab/Docs/accept.txt
- articles/ce/collaboration-message-list.asciidoc
- src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
- src/main/java/com/vaadin/demo/ce/MyMessagePersister.java
- src/main/java/com/vaadin/demo/domain/Message.java
- src/main/java/com/vaadin/demo/domain/MessageService.java
- src/main/java/com/vaadin/demo/domain/User.java
Resolves https://github.com/vaadin/collaboration-engine-internal/issues/556
> Add docs for CE message persistence

- articles/fusion/security/spring-login.asciidoc
Use /icons/ that is actually present in starter apps
> Make code example work

- articles/fusion/security/overview.asciidoc
- articles/fusion/security/role-based-access.asciidoc
- frontend/demo/fusion/authentication/auth.ts
- src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfo.java
- src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfoEndpoint.java
> Add Role-Based Access Control article to Fusion Security

- articles/fusion/security/spring-login.asciidoc
> fix: correct Spring security config

- articles/flow/routing/tutorial-routing-get-registered-routes.asciidoc
> @pleku fix: backport getting routes docs for flow

- articles/tools/designer/getting-started/build-your-main-view.asciidoc
- articles/tools/designer/getting-started/setting-up-your-environment.asciidoc
Related to https://github.com/vaadin/designer/issues/2390
> Add mentions about Gradle support in Designer

- articles/ds/components/charts/upgrading.asciidoc
Related to https://github.com/vaadin/vaadin-charts/issues/574
> Fix: clarify styling methods in upgrade guide

- articles/fusion/pwa/offline-authentication-check.asciidoc
- articles/fusion/security/authentication-offline.asciidoc
- articles/fusion/security/overview.asciidoc
- articles/fusion/security/role-based-access.asciidoc
- frontend/demo/fusion/authentication/auth.ts
- frontend/demo/fusion/authentication/main-view.ts
- frontend/demo/fusion/authentication/routes.ts
> Add Fusion offline authentication article

- articles/fusion/forms/appendix-web-component-field-strategy.asciidoc
> Closing quotations were missing

- dspublisher/docker-compose.build.yml
Fixes https://github.com/vaadin/docs-app/issues/272
> chore: rename dsp docs build artifact

- scripts/dspublisher-init-templates/dsp-readme.md
- scripts/dspublisher-init.js
Fixes https://github.com/vaadin/docs-app/issues/267
> docs: add custom readme for dsp projects

- frontend/demo/component/custom-field/custom-field-size-variants.ts
- frontend/demo/component/grid/grid-column-alignment.ts
- frontend/demo/component/grid/grid-context-menu.ts
- frontend/demo/component/messages/message-basic.ts
- frontend/demo/component/select/select-basic.ts
- frontend/demo/component/select/select-disabled.ts
- frontend/demo/component/select/select-dividers.ts
- frontend/demo/component/select/select-placeholder.ts
- frontend/demo/component/upload/upload-demo-helpers.ts
Note: PR is to check if the build is passing.
> Fix prettier errors

- dspublisher/theme/styles/banners.css
- frontend/demo/render-banner.ts
Fixes the issue mentioned [here](https://github.com/vaadin/docs/pull/452#issuecomment-840407517)
> Fix ToC banner image on v14

- dspublisher/theme/styles/banners.css
- frontend/demo/render-banner.ts
Fixes the issue mentioned [here](https://github.com/vaadin/docs/pull/452#issuecomment-840407517).
> Fix ToC banner image on v10

- articles/fusion/security/intro.asciidoc
Minor cosmetic edits.
Minor edits.
N/A
- [N/A] The issue is created in the corresponding repository and I have referenced it.
- [N/A] I have added tests to ensure my change is effective and works as intended.
- [N/A] New and existing tests are passing locally with my change.
- [N/A] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.
> Minor cosmetic edits

- .github/styles/Vocab/Docs/accept.txt
- articles/fusion/advanced/endpoints-generator.asciidoc
> Add documentation for nullability feature & regular enum

- articles/guide/install/index.asciidoc
- articles/guide/introduction/compatibility.asciidoc
> Fix minimum Maven and Gradle versions required in V14 installation guide

- articles/ce/overview.asciidoc
> Add images to the Collaboration Engine supported use cases

- articles/flow/integrations/cdi/contexts.asciidoc
- articles/flow/integrations/spring/scopes.asciidoc
> feat: Add @RouteScope docs for Spring add-on

- .github/styles/Vaadin/Abbr.yml
Added some abbreviations to exceptions based on the Vale comments from #461
> chore: add more abbreviations to exceptions

- scripts/version-update.sh
add script for updating the hard-coded versions used in docs
Fixes https://github.com/vaadin/platform/issues/2127
will need to pick to V14 branch
> chore: add script for updating versions in docs

- articles/fusion/security/spring-login.asciidoc
Fix compilation errors in SecurityConfig.java
> Fix compilation errors in SecurityConfig.java

- frontend/demo/example-resources.ts
Requires https://github.com/vaadin/docs-app/pull/277
Fixes https://github.com/vaadin/docs-app/issues/273
> Reload on session expiration when included example is loaded

- articles/ds/components/messages/index.asciidoc
- frontend/demo/component/messages/message-list-with-theme-component.ts
- frontend/themes/docs/components/vaadin-message-with-theme.css
- frontend/themes/docs/components/vaadin-message.css
- src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java
Fixes: https://github.com/vaadin/collaboration-engine-internal/issues/595
> Docs for vaadin-message-list theme API

- articles/guide/introduction/index.asciidoc
Introduce new users with more high-level API first.
This was discussed more widely earlier, but primarily we should introduce using high-level component API for new Vaadin users, and creating a Div might be misleading.
> Changed the first code sample to use VerticalLayout instead of Div

- articles/ds/components/charts/java-api/svg-generator.asciidoc
Documentation to install and use the new SVG Generator for Vaadin charts.
> SVG Generator documentation

- articles/ds/foundation/icons/index.asciidoc
- articles/ds/foundation/icons/vaadin.asciidoc
Closes https://github.com/vaadin/docs/issues/439
> docs: update ds/foundation/icons to use vaadin-icon

- articles/flow/integrations/spring/view-based-access-control.asciidoc
Improves view based access control docs for Flow Spring integration based on DX feedback:
1) link to security best practices
2) highlight default behavior
3) showcase inheritance from parent classes
Fixes #550 #551 #552
> feat: improve view access control docs

- articles/flow/security/best-practices.asciidoc
> feat: improve view based access control docs

- articles/flow/integrations/spring/view-based-access-control.asciidoc
Adds an example how to implement a logout button in Spring-based applications.
Fixes #545
> feat: Add a logout example for Spring View-based access control

- .github/styles/Vaadin/Abbr.yml
- .github/styles/Vocab/Docs/accept.txt
- articles/flow/integrations/spring/tutorial-spring-basic-mvc.asciidoc
- articles/flow/integrations/spring/tutorial-spring-basic.asciidoc
- Link to start.vaadin.com presets
- Added back Spring Initializr as an option
> Updated getting started links

- articles/flow/styling/custom-theme-packaging.asciidoc
> fix: emphasize not to include generated theme file

- articles/ds/components/charts/java-api/svg-generator.asciidoc
- articles/flow/security/best-practices.asciidoc
Add an example how to pass Login Form credentials to the security context and how to implement a logout capability.
Fixes #548
> feat: Add a login/logout example for View-based access control chapter

- .github/styles/Vocab/Docs/accept.txt
- articles/fusion/advanced/endpoints-generator.asciidoc
This reverts commit 4d278dfafa335bfa214ceb17363991576be94a73.
The doc change for nullability is for v21 only, it got into v20 when the latest branch still means v20.
> Revert "Add documentation for nullability feature & regular enum (#465)"

- articles/flow/security/best-practices.asciidoc
Improves the docs according to given suggestions.
Related-to https://github.com/vaadin/docs/pull/558
> fix: Improve wording and codes for View-based access control

- .github/styles/Vocab/Docs/accept.txt
- articles/fusion/advanced/endpoints-generator.asciidoc
Update nullability info according to the newest updates
> Update nullability info

- articles/ce/collaboration-message-list.asciidoc
- pom.xml
- src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
Fixes: vaadin/collaboration-engine-internal#594
~WIP: Needs vaadin 21.0.0.alpha3~ Ready for review.
> Docs for MessageConfigurator

- frontend/demo/component/grid/grid-cell-focus.ts
- src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java
Improved examples based on feedback from DX testing.
No changes to the asciidoc.
> docs: improve grid cell focus examples

- articles/ce/overview.asciidoc
> Fix CE overview image paths

- articles/ds/components/basic-layouts/index.asciidoc
- frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout.ts
- frontend/demo/component/basiclayouts/basic-layouts-margin.ts
- frontend/demo/component/basiclayouts/basic-layouts-padding.ts
- frontend/demo/component/basiclayouts/basic-layouts-spacing-variants.ts
- frontend/demo/component/basiclayouts/basic-layouts-spacing.ts
- frontend/themes/docs/basic-layouts.css
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsExpandingItems.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayout.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutHorizontalAlignment.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutIndividualAlignment.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutVerticalAlignment.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsMargin.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsPadding.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsSpacing.java
- src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsSpacingVariants.java
Added Flow examples for HorizontalLayout and layout spacing features.
> docs: add horizontal layout + spacing examples

- articles/tools/designer/getting-started/designer-wrap-up.asciidoc
Add a link to Designer training video
> Link to Designer training video

- articles/flow/tutorials/in-depth-course/components-and-layouts.adoc
- articles/flow/tutorials/in-depth-course/configuring-vaadin-grid.adoc
- articles/flow/tutorials/in-depth-course/creating-a-component.adoc
- articles/flow/tutorials/in-depth-course/data-binding-and-events.adoc
- articles/flow/tutorials/in-depth-course/database-entities-and-services.adoc
- articles/flow/tutorials/in-depth-course/e2e-testing-with-testbench.adoc
- articles/flow/tutorials/in-depth-course/filtering-vaadin-grid.adoc
- articles/flow/tutorials/in-depth-course/forms-and-validation.adoc
- articles/flow/tutorials/in-depth-course/index.adoc
- articles/flow/tutorials/in-depth-course/installing-and-offline-pwa.adoc
- articles/flow/tutorials/in-depth-course/login-and-authentication.adoc
- articles/flow/tutorials/in-depth-course/navigation-and-layouts.adoc
- articles/flow/tutorials/in-depth-course/production-deployment.adoc
- articles/flow/tutorials/in-depth-course/project-setup.adoc
- articles/flow/tutorials/in-depth-course/unit-and-integration-testing.adoc
- articles/flow/tutorials/quick-start-tutorial.adoc
Add custom page titles and descriptions for better SEO as discussed.
> Add titles and descriptions to Flow CRM tutorial

- articles/ds/components/grid/index.asciidoc
- frontend/demo/component/grid/grid-column-filtering.ts
- frontend/demo/component/grid/grid-context-menu.ts
- frontend/demo/component/grid/grid-external-filtering.ts
- frontend/demo/component/grid/grid-item-details-toggle.ts
- frontend/demo/component/grid/grid-item-details.ts
- frontend/demo/component/grid/grid-rich-content-sorting.ts
- frontend/demo/component/grid/grid-sorting.ts
- src/main/java/com/vaadin/demo/component/grid/GridColumnAlignment.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnFiltering.java
- src/main/java/com/vaadin/demo/component/grid/GridContextMenuExample.java
- src/main/java/com/vaadin/demo/component/grid/GridExternalFiltering.java
- src/main/java/com/vaadin/demo/component/grid/GridItemDetails.java
- src/main/java/com/vaadin/demo/component/grid/GridItemDetailsToggle.java
- src/main/java/com/vaadin/demo/component/grid/GridRichContentSorting.java
- src/main/java/com/vaadin/demo/component/grid/GridSorting.java
This PR adds a second batch of Flow examples for the Grid. The examples cover the following sections:
- Sorting
- Filtering
- Item Details
- Context Menu
> docs: add second set of Grid Flow examples

- articles/ds/components/grid/index.asciidoc
- frontend/demo/component/grid/grid-column-borders.ts
- frontend/demo/component/grid/grid-no-border.ts
- frontend/demo/component/grid/grid-no-row-border.ts
- frontend/demo/component/grid/grid-row-stripes.ts
- frontend/demo/component/grid/grid-wrap-cell-content.ts
- src/main/java/com/vaadin/demo/component/grid/GridColumnAlignment.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnBorders.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnHeaderFooter.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnWidth.java
- src/main/java/com/vaadin/demo/component/grid/GridCompact.java
- src/main/java/com/vaadin/demo/component/grid/GridNoBorder.java
- src/main/java/com/vaadin/demo/component/grid/GridNoRowBorder.java
- src/main/java/com/vaadin/demo/component/grid/GridRowStripes.java
- src/main/java/com/vaadin/demo/component/grid/GridWrapCellContent.java
Adds Flow examples for the Grid component for the theme variants section.
> docs: add fourth batch of Flow Grid examples

- articles/ds/components/grid/index.asciidoc
- frontend/demo/component/grid/grid-buffered-inline-editor.ts
- frontend/demo/component/grid/grid-drag-rows-between-grids.ts
- frontend/demo/component/grid/grid-row-reordering.ts
- frontend/demo/component/grid/grid-unbuffered-inline-editor.ts
- frontend/themes/docs/components/vaadin-grid-styling.css
- src/main/java/com/vaadin/demo/component/grid/GridBufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/grid/GridDragDropFilters.java
- src/main/java/com/vaadin/demo/component/grid/GridDragRowsBetweenGrids.java
- src/main/java/com/vaadin/demo/component/grid/GridRowReordering.java
- src/main/java/com/vaadin/demo/component/grid/GridSorting.java
- src/main/java/com/vaadin/demo/component/grid/GridStyling.java
- src/main/java/com/vaadin/demo/component/grid/GridUnbufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/grid/PersonWithRating.java
- src/main/java/com/vaadin/demo/component/grid/ValidationMessage.java
Adds Flow examples for the Grid component for the following sections:
- Drag and Drop
- Inline Editing
- Styling Rows and Columns
> docs: add third batch of Flow Grid examples

- articles/flow/components/overview.asciidoc
> fix: mention stadard HTML Components

- articles/ds/components/button/index.asciidoc
- frontend/demo/component/button/button-dialog.ts
- frontend/demo/component/button/button-disable-long-action.ts
- frontend/demo/component/button/button-form.ts
- frontend/demo/component/button/button-grid.ts
- frontend/demo/component/button/button-labels.ts
- frontend/demo/component/button/fake-progress-bar.ts
- src/main/java/com/vaadin/demo/component/button/ButtonBasic.java
- src/main/java/com/vaadin/demo/component/button/ButtonContrast.java
- src/main/java/com/vaadin/demo/component/button/ButtonDialog.java
- src/main/java/com/vaadin/demo/component/button/ButtonDisableLongAction.java
- src/main/java/com/vaadin/demo/component/button/ButtonDisabled.java
- src/main/java/com/vaadin/demo/component/button/ButtonError.java
- src/main/java/com/vaadin/demo/component/button/ButtonForm.java
- src/main/java/com/vaadin/demo/component/button/ButtonGrid.java
- src/main/java/com/vaadin/demo/component/button/ButtonIcons.java
- src/main/java/com/vaadin/demo/component/button/ButtonImages.java
- src/main/java/com/vaadin/demo/component/button/ButtonLabels.java
- src/main/java/com/vaadin/demo/component/button/ButtonSizes.java
- src/main/java/com/vaadin/demo/component/button/ButtonStyles.java
- src/main/java/com/vaadin/demo/component/button/ButtonSuccess.java
- src/main/java/com/vaadin/demo/component/button/ButtonTertiaryInline.java
- src/main/java/com/vaadin/demo/component/button/FakeProgressBar.java
adds Java examples for the following sections:
- Prevent Multiple Clicks
- ARIA Labels
- Buttons in Forms
- Buttons in Dialogs
- Global vs Selection-Specific Actions
> add second batch of button flow examples

- src/main/java/com/vaadin/demo/component/accordion/AccordionFilledPanels.java
- src/main/java/com/vaadin/demo/component/accordion/AccordionReversePanels.java
- src/main/java/com/vaadin/demo/component/accordion/AccordionSmallPanels.java
- src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnFiltering.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnVisibility.java
- src/main/java/com/vaadin/demo/component/grid/GridDynamicHeight.java
- src/main/java/com/vaadin/demo/component/grid/GridItemDetails.java
- src/main/java/com/vaadin/demo/component/grid/GridItemDetailsToggle.java
- src/main/java/com/vaadin/demo/component/inputfields/InputFieldHelperPosition.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarComboButtons.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarIconOnly.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarIcons.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarStyles.java
Updates existing Flow examples to use theme variant constants where possible.
> refactor: use theme variant constants in Flow examples

- articles/ds/components/dialog/index.asciidoc
- frontend/demo/component/dialog/dialog-basic.ts
- frontend/demo/component/dialog/dialog-closing.ts
- frontend/demo/component/dialog/dialog-draggable.ts
- frontend/demo/component/dialog/dialog-no-padding.ts
- frontend/demo/component/dialog/dialog-resizable.ts
- frontend/themes/docs/dialog.css
- frontend/themes/docs/styles.css
- src/main/java/com/vaadin/demo/component/dialog/DialogBasic.java
- src/main/java/com/vaadin/demo/component/dialog/DialogClosing.java
- src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java
- src/main/java/com/vaadin/demo/component/dialog/DialogNoPadding.java
- src/main/java/com/vaadin/demo/component/dialog/DialogResizable.java
Adds Flow examples for the Dialog component.
> docs: add Flow examples for Dialog component

- articles/designer/designer-overview.asciidoc
- articles/framework/tutorial.asciidoc
- articles/testbench/chapter-testbench.asciidoc
- articles/testbench/testbench-overview.asciidoc
- articles/testbench/testbench-quickstart.asciidoc
- articles/testbench/testbench-tutorial.asciidoc
> Make v8 tutorial version more explicit

- articles/flow/gradle-external.asciidoc
https://vaadin.slack.com/archives/CQUQWJ4KU/p1628597985035300
> Remove link to devsoap (v14)

- articles/flow/gradle-external.asciidoc
> Remove link to devsoap (v20)

- articles/flow/gradle-external.asciidoc
> Remove link to devsoap (latest)

- articles/fusion/advanced/endpoints-generator.asciidoc
* Collection type nullability is supported
* Endpoint function parameters are non-omittable
> feat: make docs reflecting latest nullability changes.

- articles/guide/start/maven.asciidoc
- articles/guide/upgrading/v10-13/index.asciidoc
- articles/tools/mpr/configuration/mpr-cdi-tutorial.asciidoc
- articles/tools/mpr/introduction/step-1-maven-v7.asciidoc
- articles/tools/mpr/introduction/step-1-maven-v8.asciidoc
> use only stable release version

- articles/fusion/advanced/components-definitions.asciidoc
1. Added documentation for the TS feature https://github.com/vaadin/web-components/issues/204 which is going to land in Vaadin 21.
2. Removed the Limitations section as addressed by the addition of this feature.
3. Removed all the links to my [CF project](https://github.com/web-padawan/ts-vaadin-examples) as TS examples are now complete.
> docs: document TS generic types feature

- articles/ds/components/grid/index.asciidoc
- articles/flow/components/grid.asciidoc
- frontend/demo/init-flow-components.ts
- src/main/java/com/vaadin/demo/component/combobox/ComboBoxPresentation.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnBorders.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnFiltering.java
- src/main/java/com/vaadin/demo/component/grid/GridColumnFreezing.java
- src/main/java/com/vaadin/demo/component/grid/GridContent.java
- src/main/java/com/vaadin/demo/component/grid/GridExternalFiltering.java
- src/main/java/com/vaadin/demo/component/grid/GridItemDetailsToggle.java
- src/main/java/com/vaadin/demo/component/grid/GridNoBorder.java
- src/main/java/com/vaadin/demo/component/grid/GridNoRowBorder.java
- src/main/java/com/vaadin/demo/component/grid/GridRichContentSorting.java
- src/main/java/com/vaadin/demo/component/grid/GridRowReordering.java
- src/main/java/com/vaadin/demo/component/grid/GridRowStripes.java
- src/main/java/com/vaadin/demo/component/grid/GridWrapCellContent.java
Closes https://github.com/vaadin/docs/issues/561
Closes https://github.com/vaadin/docs/issues/562
> Update the examples and documentation to use LitRenderer

- articles/shared/guide/_upgrading.asciidoc
Fix a broken list format in the upgrading guide.
> chore: fix a broken list format

- articles/ce/components/collaboration-message-list.asciidoc
- articles/ce/managers/message-manager.asciidoc
- src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
- src/main/java/com/vaadin/demo/ce/MessageManagerExample.java
- src/main/java/com/vaadin/demo/ce/MyMessagePersister.java
Adds `MessageManager` documentation.
> CE: Add MessageManager documentation

- articles/flow/binding-data/data-provider.asciidoc
Spring add-on now includes more data helpers which simplify the binding of pageable repository to the components.
> feat: Simplify data binding with a new helper methods

- articles/flow/security/best-practices.asciidoc
Should be reviewed after https://github.com/vaadin/flow/pull/11884 and https://github.com/vaadin/spring/pull/902 are done.
Related-to https://github.com/vaadin/flow/issues/11231
> feat: Enable view access checker by default

- articles/flow/integrations/spring/view-based-access-control.asciidoc
Updates CRM repo branch since the 'latest' doesn't exist
> fix: Update CRM repo branch

- articles/flow/advanced/modifying-the-bootstrap-page.asciidoc
- articles/flow/guide/upgrading.asciidoc
- articles/flow/upgrading/changes.asciidoc
- articles/flow/upgrading/index.asciidoc
- articles/flow/upgrading/overview.asciidoc
- articles/fusion/application/starting.asciidoc
- articles/fusion/guide/upgrading.asciidoc
- articles/fusion/upgrading/changes.asciidoc
- articles/fusion/upgrading/index.asciidoc
- articles/fusion/upgrading/overview.asciidoc
- articles/shared/upgrading/_changes.asciidoc
- articles/shared/upgrading/_common-steps.asciidoc
- articles/tools/mpr/introduction/5-adding-legacy-components.asciidoc
> Moved upgrading guide to its own section

- articles/ce/README.md
- [] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
> Fix 404 links in Collaboration Engine README.md

- articles/flow/upgrading/legacy-component-pack.asciidoc
Fix https://github.com/vaadin/flow-legacy-components/issues/71
> docs: add legacy HL/VL documentation

- articles/flow/guide/configuration/maven.asciidoc
- articles/flow/guide/start/gradle.asciidoc
- articles/fusion/guide/configuration/maven.asciidoc
- articles/shared/guide/configuration/_index.asciidoc
- articles/shared/guide/configuration/_maven.asciidoc
Add documentation for Maven plugin properties.
Add documentation for auto update of node version
installed to `~/vaadin`.
part of vaadin/flow#9864
> Add maven documentation and doc for nodeAutoUpdate

- articles/flow/tutorials/in-depth-course/index.adoc
The feature list had one topic that is not covered in the tutorial
> Remove incorrect list item

- articles/ds/customization/styling-components.asciidoc
- articles/ds/migration.asciidoc
- articles/ds/upgrading.asciidoc
Fixes https://github.com/vaadin/web-components/issues/2897
- Docs
> docs: update components documentation for Vaadin 22

- frontend/demo/component/virtuallist/virtual-list-basic.ts
> fix: update virtual list TS example

- frontend/demo/component/virtuallist/virtual-list-basic.ts
Use live-directive as suggested by @web-padawan 
Follow-up from https://github.com/vaadin/docs/pull/892
> chore: use live directive in virtual list example

- articles/flow/tutorials/quick-start-tutorial.adoc
> Set project download as primary CTA of Flow QuickStart (vLatest)

- articles/ds/components/avatar/index.asciidoc
Noticed that spaces were missing. I thought it was a "thin space" but it turned out to be no space at all.
- Style fix
> style: add spaces around dash in admonition

- articles/fusion/routing/navigation-lifecycle.asciidoc
> Fix link to Router API docs

- articles/fusion/tutorials/in-depth-course/application-state-management-with-mobx.adoc
- articles/fusion/tutorials/in-depth-course/forms-and-validation.adoc
- articles/fusion/tutorials/in-depth-course/installing-and-offline-pwa.adoc
- articles/fusion/tutorials/in-depth-course/login-and-authentication.adoc
- articles/fusion/tutorials/in-depth-course/type-safe-server-access-with-endpoints.adoc
> Fixes based on user feedback

- articles/fusion/guide/quick-start.asciidoc
> Remove initial image from Quick Start guide (Fusion)

- articles/fusion/tutorials/in-depth-course/type-safe-server-access-with-endpoints.adoc
The packaged being referenced was to the service package and no the repository package.
> Updated the package referenced for repositories

- articles/flow/advanced/tutorial-ui-init-listener.asciidoc
> Add mention of SessionInitListener 

- articles/flow/advanced/application-lifecycle.asciidoc
- articles/flow/advanced/browser-access.asciidoc
- articles/flow/advanced/custom-error-handler.asciidoc
- articles/flow/advanced/dependency-filter.asciidoc
- articles/flow/advanced/dynamic-content.asciidoc
- articles/flow/advanced/history-api.asciidoc
- articles/flow/advanced/i18n-localization.asciidoc
- articles/flow/advanced/loading-indicator.asciidoc
- articles/flow/advanced/loading-resources.asciidoc
- articles/flow/advanced/modifying-the-bootstrap-page.asciidoc
- articles/flow/advanced/preserving-state-on-refresh.asciidoc
- articles/flow/advanced/service-init-listener.asciidoc
- articles/flow/advanced/servlet-container-authentication.asciidoc
- articles/flow/advanced/session-and-ui-init-listener.asciidoc
- articles/flow/advanced/stream-resources.asciidoc
> Add Custom Error Handling page (vLatest)

- articles/ds/components/dialog/index.asciidoc
In modal example the variable was button. It should be dialog
> Change dialog modal example

- articles/flow/advanced/service-init-listener.asciidoc
> Mention the use of @Component to register VaadinServiceInitListener

- articles/shared/guide/install/_pnpm.asciidoc
See https://github.com/vaadin/flow/pull/12512
> How to run postinstall for custom npm packages

- articles/flow/configuration/npm-pnpm.asciidoc
- articles/fusion/configuration/npm-pnpm.asciidoc
- articles/shared/guide/configuration/_npm-pnpm.asciidoc
- articles/shared/guide/install/_npm.asciidoc
- articles/shared/guide/install/_pnpm.asciidoc
- articles/upgrading/common/_22-23.adoc
Vaadin uses npm as the default frontend package manager, updating the docs accordingly.
> feat: use npm as the default frontend pacakge manager

- articles/fusion/forms/binder-validation.asciidoc
English-language updates to binder-validation.asciidoc
> English-language updates to binder-validation.asciidoc

- articles/flow/templates/limitations.asciidoc
> Added missing word 'from'.

- articles/ds/components/menu-bar/index.asciidoc
- frontend/demo/component/menubar/menu-bar-custom-theme.ts
- frontend/themes/docs/components/vaadin-context-menu-item.css
- frontend/themes/docs/components/vaadin-menu-bar-button.css
- src/main/java/com/vaadin/demo/component/menubar/MenuBarCustomTheme.java
In progress. Please don't merge!
> feat: style individual menu bar items

- articles/flow/upgrading/classic-components.asciidoc
Add mention of the classic component version of FormLayout.
> add classic form-layout docs

- articles/flow/guide/quick-start.adoc
- articles/flow/guide/start/gradle.asciidoc
- articles/flow/tutorial/_heroku-steps.adoc
- articles/flow/tutorial/overview.adoc
- articles/flow/tutorial/production-deployment.adoc
- articles/fusion/guide/quick-start.asciidoc
- articles/fusion/tutorials/_heroku-steps.adoc
- articles/fusion/tutorials/basics-tutorial.asciidoc
- articles/tools/designer/using-designer/faq.asciidoc
Given that v23 will no longer support Java 8.
> Update required JDK to 11

- .github/styles/Vocab/Docs/accept.txt
- articles/upgrading/common/_22-23.adoc
- articles/upgrading/fusion/_22-23.adoc
- articles/upgrading/index.adoc
- frontend/demo/upgrade-tool/upgrade-tool.ts
Fixes https://github.com/vaadin/hilla/issues/198
> feat: add hilla migration guide

- README.md
Fixed link to Editing Tools page in README.md
> fixed link to editing tools page

- articles/ds/components/map/index.asciidoc
- frontend/demo/component/map/map-events.ts
- frontend/themes/docs/components/vaadin-text-area.css
- src/main/java/com/vaadin/demo/component/map/MapEvents.java
Adds events section to the map component docs.
~Some of the features in here require using a snapshot.~
All features now should be in 23 beta2.
> docs: map events section

- articles/flow/tutorial/project-setup.adoc
- articles/fusion/tutorials/basics-tutorial.asciidoc
- articles/fusion/tutorials/in-depth-course/project-setup.adoc
> Fix starters links

- articles/flow/tutorial/project-setup.adoc
Add a classname to use that to trigger a download event in Tag Manager.
> Add classname to download link in Flow Tutorial

- .github/styles/Vocab/Docs/accept.txt
- articles/contributing-docs/style-guide/word-list.asciidoc
- articles/flow/advanced/application-lifecycle.asciidoc
- articles/flow/advanced/browser-access.asciidoc
- articles/flow/advanced/css-loading-order.asciidoc
- articles/flow/advanced/custom-error-handler.asciidoc
- articles/flow/advanced/dependency-filter.asciidoc
- articles/flow/advanced/dynamic-content.asciidoc
- articles/flow/advanced/history-api.asciidoc
- articles/flow/advanced/i18n-localization.asciidoc
- articles/flow/advanced/loading-indicator.asciidoc
- articles/flow/advanced/loading-resources.asciidoc
- articles/flow/advanced/modifying-the-bootstrap-page.asciidoc
- articles/flow/advanced/preserving-state-on-refresh.asciidoc
- articles/flow/advanced/server-push.asciidoc
- articles/flow/advanced/service-init-listener.asciidoc
- articles/flow/advanced/servlet-container-authentication.asciidoc
- articles/flow/advanced/session-and-ui-init-listener.asciidoc
- articles/flow/advanced/stream-resources.asciidoc
English-language improvements to Flow Advanced
> English-language improvements to Flow Advanced

- .github/styles/Vocab/Docs/accept.txt
- articles/tutorials/basics-tutorial.asciidoc
- articles/tutorials/in-depth-course/application-state-management-with-mobx.adoc
- articles/tutorials/in-depth-course/creating-components.adoc
- articles/tutorials/in-depth-course/creating-views.adoc
- articles/tutorials/in-depth-course/crud-operations.adoc
- articles/tutorials/in-depth-course/dashboard-and-charts.adoc
- articles/tutorials/in-depth-course/forms-and-validation.adoc
- articles/tutorials/in-depth-course/index.adoc
- articles/tutorials/in-depth-course/installing-and-offline-pwa.adoc
- articles/tutorials/in-depth-course/login-and-authentication.adoc
- articles/tutorials/in-depth-course/navigation-and-code-splitting.adoc
- articles/tutorials/in-depth-course/production-build-and-deployment.adoc
- articles/tutorials/in-depth-course/project-setup.adoc
- articles/tutorials/in-depth-course/reacting-to-ui-events.adoc
- articles/tutorials/in-depth-course/type-safe-server-access-with-endpoints.adoc
English-language improvements to Hilla documentation
> English-language improvements to Hilla documentation

- articles/ds/components/map/index.asciidoc
- frontend/demo/component/map/map-layers.ts
- src/main/java/com/vaadin/demo/component/map/LayerOption.java
- src/main/java/com/vaadin/demo/component/map/MapLayers.java
Adds a section about layers to the map component docs.
> docs: add layers section for map component

- articles/data-binding/binder-validation.asciidoc
Restoring a section lost as a result of Hilla docs branching.
> Add documentation for interpolateMessageCallback (Hilla 1.0) (#1015)

- frontend/demo/example-resources.ts
- frontend/demo/session-verification.ts
Backport fixes related to https://github.com/vaadin/docs-app/issues/273
The latest one being [#1045](https://github.com/vaadin/docs/issues/1045)
> fix: backport session verification to V14 branch (#1045)

- .github/.vale-pr.ini
- articles/v14-23-upgrade/index.asciidoc
- articles/v14-23-upgrade/instructions/_after-upgrade.adoc
- articles/v14-23-upgrade/instructions/_common.adoc
- articles/v14-23-upgrade/instructions/_styling.adoc
- articles/v14-23-upgrade/instructions/_typescript.adoc
- package.json
As a first step to implement #1161.
> Copy v14-23 to a separate hidden page

- articles/upgrading/styling/_21-22.adoc
- articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
Added upgrade guide content for ComboBox and Select.
> Upgrade guide: Added notes about slotted item contents in CB and Select

- articles/ds/customization/custom-theme.asciidoc
Fix the documented loading order
in the custom-theme document.
Closes #1174
> fix: Fix them document loading order.

- articles/v14-23-upgrade/final-steps/index.adoc
> Mention PageConfiguration obsolete API

- articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
- articles/v14-23-upgrade/final-steps/index.adoc
> Document necessary Spring security config changes when migrating to V23

- articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> docs: document selenium version override

- articles/v14-23-upgrade/final-steps/index.adoc
- articles/v14-23-upgrade/final-steps/instructions/_typescript.adoc
> docs: document using short package names

- articles/v14-23-upgrade/final-steps/index.adoc
- articles/v14-23-upgrade/final-steps/instructions/_iron.adoc
> docs: document replacing iron components

- articles/v14-23-upgrade/final-steps/index.adoc
- articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> docs: document migrating from PolymerTemplate

- articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> docs: add a note about a cyclic dependency in V14 bakery

- articles/upgrading/essential-steps/instructions/_common.adoc
> docs: link to server-side modality documentation

- articles/ds/components/grid/index.asciidoc
There is `setClassNameGenerator` in `Grid.Column`
> Delete invalid comment

- articles/ds/components/charts/java-api/data.asciidoc
> docs: charts turbo mode (#1323) (CP: 22)

- articles/ds/components/charts/charts-data.asciidoc
Cherry-pick of: https://github.com/vaadin/docs/pull/1323
> docs: charts turbo mode (#1323) (CP: 14)

- articles/data-binding/binder-validation.asciidoc
English-language updates relating to PR 1015.
> English-language updates relating to PR #1137

- articles/flow/advanced/server-side-modality.asciidoc
English-language updates related to PR #1236
> English-language updates related to PR #1236

- articles/contributing/flow-unit-testing.asciidoc
English-language updates related to PR #1257
> English-language updates related to PR #1257

- dspublisher/dspublisher-scripts.js
Before running DSP, check for the following preconditions and show meaningful error messages on failure:
- Ports 8000 and 8080 are available on localhost
- Maven is installed
- Node.js is at least version 14
> chore: add checks for dsp preconditions

- articles/flow/advanced/application-lifecycle.asciidoc
> Fix incorrect code formatting

- articles/tools/testbench/ui-unit-testing.asciidoc
> feat: Added documentation for UI unit test component query

- articles/upgrading/essential-steps/instructions/_common.adoc
> Emphasize the need to check minimum requirements before upgrading

- articles/tools/testbench/ui-unit-testing/spring-tests.asciidoc
> feat: Add documentation for UI Unit Testing with Spring

- articles/tools/dspublisher/start.asciidoc
- articles/tools/dspublisher/updating.asciidoc
Related to https://github.com/vaadin/cli/pull/14
> Update DSP instructions to use new branch

- articles/flow/tutorial/navigation-and-layouts.adoc
> Remove reference to non-existent @Theme annotation

- articles/routing/additional-guides/route-templates.asciidoc
> Adding link to java.util.regex.Pattern class

- articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
- articles/tools/testbench/ui-unit-testing/searching-components.asciidoc
- articles/tools/testbench/ui-unit-testing/spring-tests.asciidoc
Part of vaadin/testbench#1487
Part of vaadin/testbench#1488
> refactor: update docs after naming changes in UI Unit Testing

- articles/upgrading/essential-steps/instructions/_common.adoc
> Advice to upgrade maven-failsafe-plugin instead of jaxb

- articles/security/spring-login.asciidoc
Change HillaWebSecurityConfigurerAdapter to VaadinWebSecurityConfigurerAdapter
> Fix incorrect class in code snippet

- articles/upgrading/essential-steps/instructions/_common.adoc
Closes https://github.com/vaadin/flow-components/issues/3567
> docs: mention combobox constructor changes in upgrade guide

- articles/components/confirm-dialog/index.asciidoc
Related to https://github.com/vaadin/components-team-tasks/issues/607
> chore: remove commercial banner for ConfirmDialog

- package-lock.json
- package.json
- src/main/resources/vaadin-featureflags.properties
Fix a regression from #1620 where `webpack` dependency was incorrectly replaced with `vite`.
> fix: set feature flag to use webpack for frontend

- package-lock.json
- package.json
- src/main/resources/vaadin-featureflags.properties
Cherry-pick https://github.com/vaadin/docs/pull/1622 to `hilla` branch
> fix: set feature flag to use webpack for frontend (#1622)

- dspublisher/theme/global.css
- dspublisher/theme/header.ts
The styles of the notice are copied from the v8 branch End of Life notice.
> Add notice to header about viewing old docs version

- scripts/version-update.sh
update the attribute file used for storing the vaadin version info, which is introduced by https://github.com/vaadin/docs/commit/1414a6c5c98b514c359340108004fb784ba36593
fixes https://github.com/vaadin/platform/issues/3220
> update the version upgrade script

- articles/components/map/index.asciidoc
Fixes https://github.com/vaadin/docs/issues/1680
- Removed "experimental" admonition
- Moved other admonitions below description and main example
- Rephrased feature flag section to indicate pre-23.2 versions
> Updated Map docs for 23.2

- articles/upgrading/essential-steps/instructions/_typescript.adoc
Fixes https://github.com/vaadin/docs/issues/1606#issuecomment-1210349044
> Updated V14 upgrade guide for V23.2

- articles/tools/observability/advanced/custom-instrumentation.asciidoc
Add custom instrumentation document for observability feature branch.
> add custom instrumentation doc

- articles/tools/observability/overview.asciidoc
Address some comments from #1697, add some context why you would want this, and provide overview of data that is collected as well as the used terms.
> docs: improve observability overview

- articles/tools/observability/integrations/integrations.asciidoc
Start the introduction page for
integrations documentation
> feat: start Integrations main page

- articles/tools/observability/advanced/metrics.asciidoc
Add documentation on how to add custom metrics.
Also document enabling system and process metrics
> feat: add custom metrics documentation

- articles/tools/observability/advanced/observability-agent.asciidoc
Provides some detail in the introduction, and adds an overview of traces / spans generated by the agent.
Going to create a separate PR for metrics.
> docs: observability agent improvements

- articles/tools/observability/advanced/configuration.asciidoc
Add documentation for configuration
of agent and instrumentation.
> feat: add configuration document

- .github/styles/Vocab/Docs/accept.txt
- articles/tools/observability/advanced/observability-agent.asciidoc
Document metrics collected by the Java agent.
> docs: add observability agent metrics

- articles/tools/observability/integrations/newrelic.asciidoc
Add some info on where new relic
data can be seen.
> feat: add info on new relic data

- articles/tools/observability/advanced/configuration.asciidoc
Add instructions on how to configure service attributes
> docs: observability service configuration instructions

- articles/tools/observability/integrations/newrelic.asciidoc
- frontend/demo/tools/observability/newrelic/dashboard-generator.ts
- frontend/demo/tools/observability/newrelic/dashboard-template.json
Add instructions and tool for creating a preconfigured dashboard in New Relic.
> docs: observability new relic dashboard generator

- frontend/demo/component/checkbox/checkbox-adjacent-groups.ts
- frontend/demo/component/checkbox/checkbox-custom-presentation.ts
- frontend/demo/component/checkbox/checkbox-horizontal.ts
- frontend/demo/component/confirmdialog/confirm-dialog-cancel-button.ts
- frontend/demo/component/confirmdialog/confirm-dialog-confirm-button.ts
- frontend/demo/component/confirmdialog/confirm-dialog-reject-button.ts
- frontend/demo/component/crud/crud-toolbar.ts
- frontend/demo/component/grid/grid-column-header-footer.ts
Added missing imports to TS demos (currently some of them are broken when opening in a new window).
> fix: add missing component imports to TS demos

- frontend/demo/component/grid/grid-item-details.ts
Updated the `grid-item-details` demo to align with `grid-item-details-toggle`. Missed to update this one in #1534.
> refactor: use Lit helper directive for row details

- articles/tools/observability/advanced/configuration.asciidoc
- articles/tools/observability/advanced/custom-instrumentation.asciidoc
- articles/tools/observability/advanced/metrics.asciidoc
- articles/tools/observability/advanced/observability-agent.asciidoc
- articles/tools/observability/advanced/using-traces.asciidoc
- articles/tools/observability/getting-started.asciidoc
- articles/tools/observability/integrations/datadog.asciidoc
- articles/tools/observability/integrations/grafana.asciidoc
- articles/tools/observability/integrations/jaeger-prometheus.asciidoc
- articles/tools/observability/integrations/newrelic.asciidoc
> fix: Add descriptions

- articles/components/tabs/index.asciidoc
- frontend/demo/component/tabs/tabsheet-basic.ts
- frontend/demo/component/tabs/tabsheet-lazy-initialization.ts
- frontend/demo/component/tabs/tabsheet-prefix-suffix.ts
- src/main/java/com/vaadin/demo/component/tabs/TabSheetBasic.java
- src/main/java/com/vaadin/demo/component/tabs/TabSheetLazyInitialization.java
- src/main/java/com/vaadin/demo/component/tabs/TabSheetPrefixSuffix.java
Update `Tabs` article and add `TabSheet` code examples.
> docs: Add TabSheet documentation and examples

- articles/components/tooltip/index.asciidoc
- src/main/java/com/vaadin/demo/component/grid/GridTooltipGenerator.java
Applied the following improvements to Tooltip documentation:
- Added mentions of `Grid` and `MenuBar` to the tooltip page,
- Changed `setTooltipGenerator()` example to use lambdas.
> docs: tooltip improvements based on DX tests

- articles/production/cloud-providers/index.adoc
This section is not relevant for Hilla
> Remove mention of sticky sessions

- articles/components/tabs/index.asciidoc
- frontend/demo/component/tabs/tabsheet-theme-bordered.ts
- src/main/java/com/vaadin/demo/component/tabs/TabSheetThemeBordered.java
Fixed some DX test findings:
- add tabsheet "bordered" -theme variant example
> docs: add tabsheet bordered theme variant example

- articles/advanced/components-definitions.asciidoc
- articles/advanced/reactive-endpoints.asciidoc
- articles/advanced/type-conversion.asciidoc
- articles/data-binding/binder-validation.asciidoc
- articles/data-binding/reference.asciidoc
- articles/faq.asciidoc
- articles/getting-started.asciidoc
- articles/index.asciidoc
- articles/production/overview.asciidoc
- articles/production/troubleshooting.asciidoc
- articles/pwa/offline-authentication-check.asciidoc
- articles/routing/defining.asciidoc
- articles/routing/nested-views.asciidoc
- articles/routing/url-parameters.asciidoc
- articles/security/index.asciidoc
- articles/tutorials/basics-tutorial.asciidoc
- articles/tutorials/in-depth-course/login-and-authentication.adoc
- articles/tutorials/quickstart.asciidoc
- src/main/java/com/vaadin/demo/fusion/security/stateless/SecurityUtils.java
Some fixes for Hilla docs:
- Fixed multiple spaces between words
- Removed extra trailing whitespaces
> chore: fix extra whitespace in Hilla docs

- articles/data-binding/reference.asciidoc
- articles/data-binding/vaadin-components.asciidoc
- articles/getting-started.asciidoc
- articles/routing/nested-views.asciidoc
- articles/routing/router.asciidoc
- articles/tutorials/basics-tutorial.asciidoc
- articles/tutorials/quickstart.asciidoc
- frontend/demo/fusion/components/color-picker-view.ts
- frontend/demo/fusion/forms/dialogs/newsletter-dialog.ts
Some fixes in Hilla docs (typos, correct imports etc) and TS examples.
> chore: various small fixes for Hilla docs

- articles/application/components.asciidoc
Some fixes to "Using Components" article in Hilla docs.
> fix: some fixes for using components in Hilla

- articles/data-binding/binder.asciidoc
- articles/data-binding/binding-arrays.asciidoc
- articles/index.asciidoc
- articles/tutorials/basics-tutorial.asciidoc
- frontend/demo/fusion/application/basic/reactive-view.ts
- frontend/demo/fusion/authentication/main-view.ts
Some fixes to `html` tagged template literals indentation and formatting for Hilla docs.
> chore: fix html literals formatting in Hilla docs

- articles/advanced/cancelling-endpoint-requests.asciidoc
- articles/advanced/components-definitions.asciidoc
- articles/application/basics.asciidoc
- articles/application/components.asciidoc
- articles/application/custom-type-conversion.asciidoc
- articles/data-binding/binder-load.asciidoc
- articles/data-binding/binder-validation.asciidoc
- articles/data-binding/form-status-tracking.asciidoc
- articles/data-binding/reference.asciidoc
- articles/data-binding/vaadin-components.asciidoc
- articles/tutorials/_heroku-steps.adoc
- articles/tutorials/_reactive-intro.adoc
- articles/tutorials/basics-tutorial.asciidoc
- articles/tutorials/in-depth-course/application-state-management-with-mobx.adoc
- articles/tutorials/in-depth-course/creating-components.adoc
- articles/tutorials/in-depth-course/creating-views.adoc
- articles/tutorials/in-depth-course/crud-operations.adoc
- articles/tutorials/in-depth-course/dashboard-and-charts.adoc
- articles/tutorials/in-depth-course/forms-and-validation.adoc
- articles/tutorials/in-depth-course/installing-and-offline-pwa.adoc
- articles/tutorials/in-depth-course/login-and-authentication.adoc
- articles/tutorials/in-depth-course/navigation-and-code-splitting.adoc
- articles/tutorials/in-depth-course/project-setup.adoc
- articles/tutorials/in-depth-course/reacting-to-ui-events.adoc
- articles/tutorials/in-depth-course/type-safe-server-access-with-endpoints.adoc
Some fixes to indentation and formatting for Hilla code examples in articles.
> chore: fix examples formatting in Hilla docs

- articles/tools/azure/getting-started.asciidoc
Create a getting started tutorial that covers the basics, including:
- Adding the Azure Kit dependency
- Configuring an application
- Deploying the application and Hazelcast to a local cluster
- Scaling the application
- Rolling out a new version of the application
> Create a tutorial for Azure Kit

- .github/styles/Vocab/Docs/accept.txt
- articles/tools/azure/session-replication.adoc
References vaadin/azure-kit#29
> docs: Kubernetes Kit session replication

- articles/tools/azure/configuration.asciidoc
- articles/tools/azure/getting-started.asciidoc
- articles/tools/azure/update-version.asciidoc
Separate out the new version roll out section from the getting started page.
> Refactor the getting started page

- articles/components/date-picker/index.asciidoc
Docs for https://github.com/vaadin/platform/issues/3483
> Added docs for datepicker referenceDate

- articles/tools/kubernetes/getting-started.asciidoc
- articles/tools/kubernetes/session-replication-debug-tool.adoc
- articles/tools/kubernetes/session-replication.adoc
not serializable becomes userializable
use lowercase form for 'debug tool'
Closes vaadin/kubernetes-kit#41
> chore: reword 'not serializable' and 'Debug Tool'

- articles/tools/kubernetes/getting-started.asciidoc
- articles/tools/kubernetes/session-replication.adoc
> chore: renamed transient field filter configuration properties

- articles/lit/start/faq.adoc
Has been asked several times on social media
> add faq question on components

- articles/configuration/feature-flags.adoc
Example was missing the 'com.' prefix
> fix: fixed feature flag configuration example

- articles/advanced/server-push.asciidoc
- articles/configuration/properties.asciidoc
See https://github.com/vaadin/flow/commit/0bfadcd9b903b487069a56f4777d94768e7f3235
> Update push configuration documentation.

- articles/testing/selenium.adoc
The documentation section about the Selenium-Jupiter extension was duplicated.
> Remove duplicate Selenium-Jupiter documentation

- articles/flow/tutorial/overview.adoc
Remove the link to the non-functioning demo until the vaadin.com team figures out how to fix it.
> Remove link to non-functioning demo

- articles/testing/ui-unit/getting-started.adoc
> docs: added dependencies information on setting up Testbench Unit test project

- frontend/demo/component/accordion/accordion-summary.ts
1. Fixed a few ESLint errors reported by `eslint-config-vaadin`
2. Updated `field` Hilla directive usage to the new Lit 2 syntax.
> chore: fix ESLint errors, update field directive usage

- README.md
- articles/lit/guides/security/configuring.adoc
- articles/react/guides/security/configuring.adoc
The old title was too generic to be discoverable
Also added a snippet to README.md about DSP (same as in the `latest` branch)
> New title for endpoint access control

- articles/configuration/properties.asciidoc
- articles/tools/kubernetes/index.asciidoc
- articles/tools/sso/getting-started.adoc
- articles/tools/sso/index.asciidoc
Catching up on old Language Checks of PRs already merged.
> Language Checks: PR 2034, 2042, 2053

- articles/binding-data/data-provider.asciidoc
Instead of showing off with Spring Data helpers, actually help to explain how to implement sorting. Moved mentions of SpringDataHelpers into a separate hint.
> Improving lazy data binding docs

- frontend/demo/component/notification/notification-error.ts
- frontend/demo/component/notification/notification-keyboard-a11y.ts
- frontend/demo/component/notification/notification-link.ts
- frontend/demo/component/notification/notification-retry.ts
- frontend/demo/component/notification/notification-rich.ts
- frontend/demo/component/notification/notification-undo.ts
Fixed warnings reported by `eslint-config-vaadin` in `vaadin-notification` TS examples.
> chore: fix eslint-config-vaadin errors in notification

- frontend/demo/domain/DataService.ts
Fixed a bunch of errors reported by `eslint-config-vaadin`.
> chore: fix eslint-config-vaadin errors in DataService.ts

- README.md
- articles/contributing-docs/authoring/content-guidelines.asciidoc
Added mention about the hilla branch to README.md and a link to the docs repo in content guidelines
> Update contribution instructions

- frontend/demo/component/grid/grid-cell-focus.ts
- frontend/demo/component/grid/grid-column-filtering.ts
- frontend/demo/component/grid/grid-column-freezing.ts
- frontend/demo/component/grid/grid-column-header-footer.ts
- frontend/demo/component/grid/grid-content.ts
- frontend/demo/component/grid/grid-drag-rows-between-grids.ts
- frontend/demo/component/grid/grid-dynamic-height.ts
- frontend/demo/component/grid/grid-external-filtering.ts
- frontend/demo/component/grid/grid-item-details.ts
- frontend/demo/component/grid/grid-rich-content-sorting.ts
- frontend/demo/component/gridpro/grid-pro-edit-column.ts
Fixed some errors reported by `eslint-config-vaadin`, mostly by removing extra `return` from arrow functions.
> chore: fix ESLint warnings in grid and grid-pro demos

- frontend/demo/component/crud/crud-columns.ts
- frontend/demo/component/crud/crud-editor-aside.ts
- frontend/demo/component/crud/crud-editor-bottom.ts
- frontend/demo/component/crud/crud-editor-content.ts
- frontend/demo/component/crud/crud-grid-replacement.ts
- frontend/demo/component/crud/crud-hidden-toolbar.ts
- frontend/demo/component/crud/crud-localization.ts
- frontend/demo/component/crud/crud-open-editor.ts
- frontend/demo/component/crud/crud-sorting-filtering.ts
- frontend/demo/component/crud/crud-toolbar.ts
- frontend/demo/component/grid/grid-column-alignment.ts
- frontend/demo/component/grid/grid-column-filtering.ts
- frontend/demo/component/grid/grid-column-header-footer.ts
- frontend/demo/component/grid/grid-dynamic-height.ts
- frontend/demo/component/grid/grid-external-filtering.ts
- frontend/demo/component/grid/grid-item-details-toggle.ts
- frontend/demo/component/grid/grid-item-details.ts
- frontend/demo/component/grid/grid-multisort.ts
- frontend/demo/component/grid/grid-sorting.ts
Currently, calling `await getPeople()` endpoint doesn't look clean.
Some cases have already been updated, so I changed the rest.
> chore: align and simplify getPeople() endpoint usage

- frontend/demo/component/custom-field/custom-field-basic.ts
- frontend/demo/component/datepicker/date-picker-custom-functions.ts
- frontend/demo/component/datepicker/date-picker-custom-validation.ts
- frontend/demo/component/datetimepicker/date-time-picker-custom-validation.ts
- frontend/demo/component/timepicker/time-picker-custom-validation.ts
- frontend/demo/component/upload/upload-demo-helpers.ts
- frontend/demo/component/upload/upload-demo-mock-files.ts
- frontend/demo/component/virtuallist/virtual-list-basic.ts
- frontend/demo/flow/application/routing/index.ts
- frontend/demo/foundation/icons-preview.ts
- frontend/demo/foundation/include-module.ts
- frontend/demo/fusion/redirect.ts
- frontend/demo/tools/observability/newrelic/dashboard-generator.ts
- frontend/demo/upgrade-tool/upgrade-tool.ts
Fixed more warnings. Now we should be ready to enable the config in a separate PR, with some rules still disabled.
> chore: fix remaining errors from eslint-config-vaadin

- articles/lit/start/in-depth/application-state-management-with-mobx.adoc
> fix: use correct link for image

- articles/create-ui/web-components/an-in-project-web-component.asciidoc
Changed code so that user can now print "hello ${name}"
> as was, it would only print "hello"

- articles/lit/reference/type-nullability.adoc
> feat: add docs for NonNullApi and nullability annotation collision

- src/main/java/com/vaadin/demo/component/emailfield/EmailFieldPattern.java
- src/main/java/com/vaadin/demo/component/grid/GridBufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/grid/GridUnbufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/gridpro/GridProPreventSave.java
- src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
- src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
Formatting went off in a few files, apparently it has changed after `formatter-maven-plugin` version bump.
> chore: run mvn formatter:format for the Java code

- articles/components/form-layout/index.asciidoc
This PR contains some pieces of Russell's proofreading extracted from #2134 because they weren't directly related to that PR.
> docs: improve Form Layout wording

- articles/components/form-layout/index.asciidoc
- frontend/demo/component/formlayout/form-layout-custom-field.ts
- src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomField.java
Added a section explaining how to use multiple fields in form layouts.
Fixes #1005
> docs: explain multiple fields in form layouts

- articles/tools/designer/using-designer/java.asciidoc
> chore: replace PolymerTemplate with LitTemplate

- articles/lit/guides/reactive-endpoints.adoc
- articles/lit/guides/security/configuring.adoc
- articles/lit/start/quick.adoc
> feat: remove Lit from React section

- articles/integrations/cdi/instantiated-beans.asciidoc
Removed part detailing using
a custom UI as that is not supported.
Closes #748
> fix: remove using custom ui

- articles/lit/guides/security/spring-login.adoc
- articles/lit/start/in-depth/login-and-authentication.adoc
- src/main/java/com/vaadin/demo/SecurityConfig.java
- src/main/java/com/vaadin/demo/fusion/security/authentication/SecurityConfigDemo.java
- src/main/java/com/vaadin/demo/fusion/security/stateless/SecurityConfig.java
> chore: remove VaadinWebSecurityConfigurerAdapter from examples

- src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInputFormat.java
- src/main/java/com/vaadin/demo/component/emailfield/EmailFieldPattern.java
- src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomField.java
- src/main/java/com/vaadin/demo/component/grid/GridBufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/grid/GridUnbufferedInlineEditor.java
- src/main/java/com/vaadin/demo/component/gridpro/GridProPreventSave.java
- src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
- src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
This PR is a result of running `mvn formatter:format` on the docs repo.
> refactor: format Java examples

- articles/routing/lifecycle.asciidoc
> fix: Add notes on which order event handlers are called

- articles/advanced/server-push.asciidoc
- articles/tools/mpr/configuration/push.asciidoc
> chore: updated Push documentation

- articles/components/tabs/index.asciidoc
- frontend/demo/component/tabs/tabs-autoselect.ts
> docs: add missing imports to java-only tabs autoselect example

- articles/lit/guides/forms/vaadin-components.asciidoc
> feat: add multi-select combo box to multiple selection suggestions

- articles/tools/sso/getting-started.adoc
- pom.xml
- src/main/java/com/vaadin/demo/sso/ProfileView.java
versions used for sso-kit and the other two components are outdated, they should come from the vaadin-bom directly.
> fix: remove hardcoded versions in pom

- articles/tools/sso/getting-started.adoc
- pom.xml
- src/main/java/com/vaadin/demo/sso/ProfileView.java
* fix: remove hardcoded versions in pom
* Update AuthenticationContext docs for SSO Kit
---------
Co-authored-by: Giovanni Lovato <giovanni@lova.to>
> fix: remove hardcoded versions in pom (#2218)

- articles/components/spreadsheet/index.asciidoc
Fix https://github.com/vaadin/flow-components/issues/4302
> docs: add cell data section to Spreadsheet docs

- articles/configuration/properties.asciidoc
Update properties that are available
and add default value for each property.
Fixes #2123
> fix: update available properties

- articles/production/distributed-deployment.adoc
Brief notes on scalability, high availability and session replication. Links to Kubernetes Kit as session replication solution.
Closes #1979
> docs: add notes on distributed deployment

- articles/components/text-field/index.asciidoc
The PR aims to improve the description of the pattern and allowedCharPattern Text Field features to better reflect the difference between them.
Fixes https://github.com/vaadin/docs/issues/1869
> docs: improve the description of pattern and allowedCharPattern

- articles/advanced/custom-instantiators.asciidoc
Add documentation for creating
a custom instantiator.
Part of #739
> feat: Document instantiator

- articles/integrations/spring/configuration.asciidoc
> chore: documented Spring add-on excludeUrls parameter

- articles/binding-data/components-binder-beans.asciidoc
> docs: added notes on binding nested properties

- articles/lit/guides/forms/web-component-field-strategy.asciidoc
- frontend/demo/fusion/forms/field-strategy/my-binder.ts
> feat: explain the new `model` argument of `getFieldStrategy`

- articles/lit/start/basics/index.adoc
Courtesy of Tatu Lund: The React `TodoView`is supposed to be a function. The filename had a typo and the Formik code example was faulty
> Update React basics tutorial

- dspublisher/theme/global.css
> NEW badge for Styling tabs in Components docs

- articles/tutorial/login-and-authentication.adoc
- articles/tutorial/navigation-and-layouts.adoc
- articles/tutorial/overview.adoc
- articles/tutorial/project-setup.adoc
Updated with utility class enums and Java 17 requirement
I also changed the download link from Vaadin Start to the V24 branch in GitHub
> Update tutorial for V24 release

- articles/lit/reference/endpoint-generator.adoc
Didn't render examples correctly, LGTM now when previewed with DSP
> Fix broken code box

- articles/tools/observability/customization.asciidoc
> fix: faulty code

- articles/tools/observability/customization.asciidoc
Fix groupId for opentelemetry-instrumentation-annotations
> fix: instrumentation groupId

- articles/production/docker.adoc
Language check for closed PR [#1876](https://github.com/vaadin/docs/pull/1876)
> Language and format updates for closed PR

- articles/styling/advanced/themes-for-embedded.adoc
- articles/styling/lumo/utility-classes.adoc
Contains edits to files touched by PR 2240.
> Edited themes-for-embedded & utility-classes docs - PR2240

- articles/tools/collaboration/going-to-production.asciidoc
Remove information about specific quotas and prices, as they were not in sync with the pricing page.
> Remove specific quota / pricing information

- articles/lit/guides/production/native.asciidoc
added instructions for checking if you have GraalVM installed and how to install it.
> add instructions for installing graalvm

- articles/tools/sso/integrations/azure-ad.asciidoc
- articles/tools/sso/integrations/keycloak.asciidoc
- articles/tools/sso/integrations/okta.asciidoc
A step-by-step guide on configuring SSO Kit to work with Azure Active Directory
> New Azure AD tutorial

- articles/binding-data/data-provider.asciidoc
PR 2062 related to lazy data binding was closed before it could be Language Checked.  While I was at it, I went through the whole document it touched.
> More Editing of Lazy Data Binding Document

- articles/tools/kubernetes/session-replication-debug-tool.adoc
Since I wasn't able to review and edit PR1931, I've created this branch and pull-request to edit the one document it involved.
> Editing Kubernetes Debut Tool Document

- articles/tools/kubernetes/index.asciidoc
This is a review of the document changed with the closed PR 2034.
> Edited Kubernetes Kit Index Page

- articles/contributing/editor-settings-intellij-idea.asciidoc
Added jakarta package and an empty line before static imports
> chore: fixed intellij idea import order instructions

- articles/production/docker.adoc
No need to require installation to local repo.
> Use `mvn package` instead of install

- frontend/demo/init.ts
Closes https://github.com/vaadin/hilla/issues/919
Closes https://github.com/vaadin/docs/issues/2325
Closes https://github.com/vaadin/docs/issues/2340
> fix: remove obsolete Hilla workaround

- articles/components/horizontal-layout/index.asciidoc
- frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-margin.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-padding.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing-variants.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout.ts
- frontend/demo/component/basiclayouts/basic-layouts-margin.ts
- frontend/demo/component/basiclayouts/basic-layouts-padding.ts
- frontend/demo/component/basiclayouts/basic-layouts-spacing-variants.ts
- frontend/demo/component/basiclayouts/basic-layouts-spacing.ts
- frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-horizontal-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-individual-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-vertical-alignment.ts
- frontend/demo/component/basiclayouts/basic-layouts-vertical-layout.ts
- frontend/demo/component/board/board-basic.ts
- frontend/demo/component/board/board-breakpoints.ts
- frontend/demo/component/board/board-column-span.ts
- frontend/demo/component/board/board-column-wrapping.ts
- frontend/demo/component/board/board-nested.ts
> Fix issue where .ts samples only render once

- articles/lit/components/index.adoc
- articles/lit/guides/styling.adoc
- articles/lit/start/basics/index.adoc
- articles/lit/start/faq.adoc
- articles/react/components/index.adoc
- articles/react/guides/styling.adoc
Some optimization prompted by our SEO agency.
> Improve Hilla SEO

- articles/components/charts/migrating-from-earlier-versions.asciidoc
Add missing content and check language
> Update Charts migration guide

- articles/components/_input-field-common-features.adoc
- articles/components/button/index.asciidoc
- articles/components/checkbox/index.asciidoc
- articles/components/combo-box/index.asciidoc
- articles/components/custom-field/index.asciidoc
- articles/components/date-picker/index.asciidoc
- articles/components/date-time-picker/index.asciidoc
- articles/components/email-field/index.asciidoc
- articles/components/index.asciidoc
- articles/components/password-field/index.asciidoc
- articles/components/radio-button/index.asciidoc
- articles/components/select/index.asciidoc
- articles/components/text-area/index.asciidoc
- articles/components/text-field/index.asciidoc
- articles/components/time-picker/index.asciidoc
- articles/styling/styling-components/sharing-styles.adoc
PR #2337 (input fields common features) was merged and closed before we could edit it for language. This branch and PR is for editing the files that other PR touched.
> Input Fields  Common Features (PR 2337)

- articles/react/components/accordion/index.adoc
- articles/react/components/app-layout/index.adoc
- articles/react/components/avatar/index.adoc
- articles/react/components/board/index.adoc
- articles/react/components/button/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names A to B.
> PR2296-Add React Components to Hilla - A to B

- articles/react/components/charts/index.adoc
- articles/react/components/checkbox/index.adoc
- articles/react/components/combo-box/index.adoc
- articles/react/components/confirm-dialog/index.adoc
- articles/react/components/context-menu/index.adoc
- articles/react/components/cookie-consent/index.adoc
- articles/react/components/crud/index.adoc
- articles/react/components/custom-field/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names beginning with the letter C.
> PR2296-Add React Components to Hilla - C

- articles/react/components/date-picker/index.adoc
- articles/react/components/date-time-picker/index.adoc
- articles/react/components/details/index.adoc
- articles/react/components/dialog/index.adoc
- articles/react/components/email-field/index.adoc
- articles/react/components/form-layout/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names D to F.
> PR2296-Add React Components to Hilla - D to F

- articles/tools/mpr/configuration/limitations.asciidoc
Mention RouteScope as alternative to ViewScope
> chore: Mention @RouteScope

- articles/react/components/list-box/index.adoc
- articles/react/components/login/index.adoc
- articles/react/components/menu-bar/index.adoc
- articles/react/components/message-input/index.adoc
- articles/react/components/message-list/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names L to M.
> PR2296-Add React Components to Hilla - L to M

- articles/react/components/scroller/index.adoc
- articles/react/components/select/index.adoc
- articles/react/components/split-layout/index.adoc
- articles/react/components/tabs/index.adoc
- articles/react/components/text-area/index.adoc
- articles/react/components/text-field/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names S to Text.
> PR2296-Add React Components to Hilla - S to Text

- articles/react/components/time-picker/index.adoc
- articles/react/components/tooltip/index.adoc
- articles/react/components/tree-grid/index.adoc
- articles/react/components/upload/index.adoc
- articles/react/components/vertical-layout/index.adoc
- articles/react/components/virtual-list/index.adoc
PR 2296 was allowed to merge and be closed before it could be checked for language. This pull request contains edits for files touched by that previous PR, but for file names Time to Z.
> PR2296-Add React Components to Hilla - Time to Z

- articles/lit/start/basics/index.adoc
> fix checkbox label in react todo demo 

- articles/components/time-picker/index.asciidoc
- articles/components/tooltip/index.asciidoc
- articles/components/tree-grid/index.asciidoc
- articles/components/upload/index.asciidoc
- articles/components/vertical-layout/index.asciidoc
- articles/components/virtual-list/index.asciidoc
PR 2296 changed the components files in the Hilla documentation.. It was closed before it could be checked for language. This branch was meant to contain edits for files touched by that PR, but only for file names Time to Z. 
However, I started this branch based on the "latest" and not "hilla".  As a result, I edited the Vaadin doc files and not the Hilla doc files. Rather than discard these edits, I created this new branch.  
See PR 2451 for the corresponding Hilla edits.
> Edits to Components Files - Time to Z

- articles/configuration/development-mode/index.asciidoc
- articles/upgrading/index.adoc
Fixes https://github.com/vaadin/flow/issues/16899
> Recommend line-awesome add-on for V24

- frontend/demo/component/menubar/menu-bar-combo-buttons.ts
- frontend/demo/component/menubar/menu-bar-icon-only.ts
- frontend/demo/component/menubar/menu-bar-icons.ts
- frontend/demo/component/menubar/menu-bar-tooltip.ts
Fixes https://github.com/vaadin/web-components/issues/5664
> fix: use correct custom element for menu-bar icon examples

- articles/tools/azure-cloud/autoscaling.adoc
- articles/tools/azure-cloud/getting-started.adoc
- articles/tools/azure-cloud/index.asciidoc
- articles/tools/azure-cloud/multiple-kubernetes-environments.adoc
- articles/tools/azure-cloud/tls.adoc
This is one of a series of PRs containing general formatting and layout improvements, and general clean-up of text.
> Minor Clean-Up: Tools - Azure Cloud

- articles/lit/start/quick.adoc
- articles/react/start/quick.adoc
> Update Hilla quick start tutorials

- .github/styles/Vocab/Docs/accept.txt
- articles/components/grid/index.asciidoc
- frontend/demo/component/grid/react/grid-column-reordering-resizing.tsx
- frontend/demo/component/grid/react/grid-content.tsx
- frontend/demo/component/grid/react/grid-lazy-column-rendering.tsx
> feat: add grid react examples

- .github/styles/Vaadin/ProductName.yml
See discussion at the bottom of closed PR #2502
> Revert mistake

- frontend/demo/component/app-layout/app-layout-bottom-navbar.ts
- src/main/java/com/vaadin/demo/component/applayout/AppLayoutBottomNavbar.java
Fixes https://github.com/vaadin/web-components/issues/3212
> Added aria-labels to applayout bottom navbar tabs

- articles/components/button/index.asciidoc
- frontend/demo/component/button/react/button-contrast.tsx
- frontend/demo/component/button/react/button-success.tsx
Add a button contrast React example
> docs: add button success react example

- articles/components/spreadsheet/index.asciidoc
Removed a limitation that doesn't seem to apply anymore, and also fixed a formatting error where a separate limitation ended up as part of a nested one.
Closes https://github.com/vaadin/flow-components/issues/5207
> docs: update spreadsheet limitations

- articles/lit/start/in-depth/login-and-authentication.adoc
Align the tutorial with changes in code made in https://github.com/vaadin/hilla-crm-tutorial/pull/54/files
> delay server calls until login info is ready

- frontend/demo/component/progressbar/progress-bar-completion-time.ts
- frontend/demo/component/progressbar/progress-bar-custom-range.ts
- frontend/demo/component/progressbar/progress-bar-determinate.ts
- frontend/demo/component/progressbar/progress-bar-indeterminate.ts
- frontend/demo/component/progressbar/progress-bar-label.ts
- frontend/demo/component/progressbar/progress-bar-theme-variants.ts
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarCompletionTime.java
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarCustomRange.java
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarDeterminate.java
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarIndeterminate.java
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarLabel.java
- src/main/java/com/vaadin/demo/component/progressbar/ProgressBarThemeVariants.java
- Simplified ProgressBar samples by removing custom labels where they didn't really add any value to the sample
- Added aria-labelledby and aria-describedby associations to remaining labels.
> Simplified progressbar samples and added aria-attributes

- articles/components/accordion/index.asciidoc
- frontend/demo/component/accordion/react/accordion-content.tsx
- frontend/demo/component/accordion/react/accordion-disabled-panels.tsx
- frontend/demo/component/accordion/react/accordion-filled-panels.tsx
- frontend/demo/component/accordion/react/accordion-reverse-panels.tsx
- frontend/demo/component/accordion/react/accordion-small-panels.tsx
- frontend/demo/component/accordion/react/accordion-summary.tsx
Extracted from https://github.com/vaadin/docs/pull/2632
> docs: add React examples for accordion

- articles/tutorial/login-and-authentication.adoc
See related [PR](https://github.com/vaadin/flow-crm-tutorial/pull/169). Closes #2577.
> Update security configuration

- frontend/demo/component/board/board-basic.ts
- frontend/demo/component/board/board-breakpoints.ts
- frontend/demo/component/board/board-column-span.ts
- frontend/demo/component/board/board-column-wrapping.ts
- frontend/demo/component/board/board-nested.ts
- frontend/demo/component/board/react/board-breakpoints.tsx
- frontend/demo/component/notification/react/notification-warning-preview.ts
Fixed a few more errors found by ESLint and Prettier.
> chore: fix Prettier errors, remove useless constructors

- articles/create-ui/templates/styling-templates.asciidoc
Add documentation for the `applyTheme` utility function.
If the helper isn't intended for public use, feel free to close this PR.
> docs: add documentation for applyTheme function

- frontend/demo/fusion/forms/field-strategy/my-text-field-strategy.ts
Implement a `FieldStrategy` method introduced in the recent 2.2.0-alpha8.
> Update Hilla form field strategy example

- articles/security/advanced-topics/securing-plain-java-app.adoc
Adds a note and code example to the plain apps security chapter about changing session ID on login to prevent Session Fixation vulnerabilities.
> fix: Change session Id on login

- articles/charts/charts-overview.asciidoc
> Updating license description for v8

- articles/lit/acceleration-kits/observability-kit/getting-started.adoc
- articles/lit/acceleration-kits/sso-kit/getting-started.adoc
- articles/lit/guides/production/cloud-providers/aws/index.adoc
- articles/lit/guides/production/cloud-providers/azure/index.adoc
- articles/lit/guides/production/cloud-providers/google/index.adoc
- articles/lit/guides/production/cloud-providers/heroku/index.adoc
- articles/lit/guides/reactive-endpoints.adoc
- articles/lit/guides/security/configuring.adoc
- articles/lit/start/quick.adoc
DO NOT MERGE before https://github.com/vaadin/hilla-cli/pull/2 is merged.
> Make React the default CLI option

- articles/lit/guides/endpoints.adoc
- package-lock.json
- package.json
- pom.xml
- src/main/java/com/vaadin/demo/fusion/accessingbackend/CounterService.java
Related to vaadin/hilla#1221
Fixes: vaadin/hilla#1237
> feat: add note about @BrowserCallable

- articles/react/guides/client-middleware.adoc
- articles/react/guides/reactive-endpoints.adoc
- articles/react/guides/routing.adoc
Adds a basic guide on how to implement routing with Hilla React.
> docs: add Hilla React routing documentation

- articles/contributing/docs/index.adoc
This is a minimal PR, just to change the URL for cloning the documentation from http to https.
> Change URL Protocol for GitHub

- scripts/pick/cherry-pick-config-hilla-react-components.js
Depends on https://github.com/vaadin/docs/pull/2836
> Add Hilla Auto Grid to cherry-pick keep paths list

- articles/tools/appsec/getting-started.asciidoc
- Updates the dependency name and version based on the new structure
- Updates the `bom-npm` output file path
> Update AppSec Kit dependency name

- articles/integrations/cdi/contexts.asciidoc
Fixes https://github.com/vaadin/flow/issues/6395 for v23
> Improve CDI PreserveOnRefresh documentation

- articles/upgrading/essential-steps/instructions/_common.adoc
Related to https://github.com/vaadin/flow/issues/17602
> Add note of changed getPathInfo behavior and implications on cookies

- articles/lit/start/faq.adoc
PR 2962, entitled "Add note on microservice architecture"  was closed before we could edit it. This PR is to edit the involved text files touched by that PR.
> Microservice Architecture Note (2962)

- articles/react/components/auto-grid/index.asciidoc
- frontend/demo/component/auto-grid/react/auto-grid-custom-columns.tsx
fixes: #2990
Also adds a section about the exposed refresh function to be called from parent component.
> feat: add custom column order and grid refresh sections

- articles/lit/guides/forms/binder-validation.adoc
As a follow-up to https://github.com/vaadin/hilla/pull/1912
this clarification helps to resolve the https://github.com/vaadin/hilla/issues/1840
> fix: clarify validation message interpolation example

- articles/guide/start/gradle.asciidoc
See release notes of Vaadin 24.3
> Update Gradle and Java version requirements

- articles/flow/configuration/development-mode/dev-tools/index.adoc
- articles/flow/configuration/properties.adoc
* Adds devmode.hostsAllowed property
* Note->plaintext; add reasoning
* First pass at editing.
* Second pass at editing.
---------
> cp: Adds devmode.hostsAllowed property (#3104)

- src/main/java/com/vaadin/demo/component/login/LoginOverlayInternationalization.java
Back-port of a merged [PR](https://github.com/vaadin/docs/pull/3124).
> fix: set i18n header before modifying for login java example (#5903) (CP: latest)

- articles/flow/tools/kubernetes/session-replication-debug-tool.adoc
Issue [#100](https://github.com/vaadin/kubernetes-kit/issues/100)
> Describe session serialization timeout property in Kubernetes Kit

- articles/hilla/lit/reference/type-conversion.adoc
Pull request 2693 was merged and closed without language being checked. This PR covers the documents affected by that earlier PR.
> Type Conversion - PR 2693 (next)

- articles/hilla/lit/start/faq.adoc
Pull request 2962 was merged and closed without language being checked. This PR covers the documents affected by that earlier PR.
> Note on Microservice Architecture - PR 2962

- articles/flow/contributing/editor-settings.adoc
> Remove the 'Known Problems in Configuration' paragraph

- articles/flow/integrations/embedding/properties.adoc
Remove non existing WebComponentDefinition and fix formatting.
> chore: fix typo on Embedding doc

- articles/components/side-nav/index.adoc
> docs: add code example for SideNavItem target property

- articles/components/tree-grid/index.adoc
- frontend/demo/component/tree-grid/react/tree-grid-scroll-to-index.tsx
- frontend/demo/component/tree-grid/tree-grid-scroll-to-index.ts
- src/main/java/com/vaadin/demo/component/treegrid/TreeGridScrollToIndex.java
Closes https://github.com/vaadin/docs/issues/3354
> docs: add documentation for treegrid scrollToIndex

- articles/components/side-nav/index.adoc
- frontend/demo/component/side-nav/react/side-nav-router.tsx
Fixes https://github.com/vaadin/docs/issues/3377
> docs: add documentation for side-nav router integration

- articles/lit/start/faq.adoc
Resolving: https://github.com/vaadin/docs/issues/3385
> docs: add SSR to Hilla FAQ

- articles/flow/integrations/cdi/contexts.adoc
Pull request 3291 was merged and closed without the language being checked. This PR covers the document affected by that earlier PRs
> RouteScopeOwner - PR 3291

- articles/components/checkbox/index.adoc
Pull requests 3370 and 3369 were merged and closed without the language being checked. This PR covers the document affected by those earlier PRs.
> CheckBox Features & Examples - PR 3370 & 3369

- articles/components/grid-pro/index.adoc
- articles/components/tree-grid/index.adoc
Pull requests 3371 and 3378 were merged and closed without the language being checked. This PR covers the documents affected by those earlier PRs.
> GridPro & TreeGrid - PR 3371 & 3378

- articles/components/badge/index.adoc
- articles/flow/advanced/loading-resources.adoc
> fix: /frontend → /src/main/frontend

- articles/upgrading/index.adoc
> fix: fix react opt-out note

- articles/components/button/index.adoc
Fixes https://github.com/vaadin/docs/issues/3536
> chore: remove unnecessary use of anchor in button documentation

- articles/components/menu-bar/index.adoc
- frontend/demo/component/menubar/menu-bar-drop-down-indicators.ts
- frontend/demo/component/menubar/react/menu-bar-drop-down-indicators.tsx
- src/main/java/com/vaadin/demo/component/menubar/MenuBarDropDownIndicators.java
> docs: add MenuBar dropdown indicators theme variant example

- articles/components/button/index.adoc
- frontend/demo/component/button/button-warning.ts
- frontend/demo/component/button/react/button-warning.tsx
- src/main/java/com/vaadin/demo/component/button/ButtonWarning.java
> docs: add example for Button warning theme variant

- articles/components/combo-box/index.adoc
- articles/components/multi-select-combo-box/index.adoc
- frontend/demo/component/combobox/combo-box-item-class-name.ts
- frontend/demo/component/combobox/react/combo-box-item-class-name.tsx
- frontend/demo/component/multi-select-combo-box/multi-select-combo-box-item-class-name.ts
- frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-item-class-name.tsx
- frontend/themes/docs/combo-box-item-class-name.css
- frontend/themes/docs/document.css
- frontend/themes/docs/multi-select-combo-box-chip-class-name.css
- frontend/themes/docs/multi-select-combo-box-item-class-name.css
- frontend/themes/docs/styles.css
- src/main/java/com/vaadin/demo/component/combobox/ComboBoxItemClassName.java
- src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxItemClassName.java
> docs: add Combo Box item class name generator example

- articles/flow/integrations/react.adoc
Pull request 3600 was merged and closed without the language being checked. This PR covers the document affected by that earlier PR.
> Wrap Field React Component into Flow Component - PR 3600

- articles/contributing/docs/vale.adoc
- articles/flow/security/advanced-topics/navigation-access-control.adoc
- articles/getting-started/tutorial/flow/layout.adoc
- articles/getting-started/tutorial/flow/styling.adoc
- articles/getting-started/tutorial/hilla/first-view.adoc
- articles/getting-started/tutorial/hilla/layout.adoc
- articles/tools/collaboration/advanced/backend-api.adoc
- articles/tools/kubernetes/getting-started.adoc
- articles/tools/kubernetes/update-version.adoc
- articles/tools/swing/communication.adoc
- src/main/java/com/vaadin/demo/component/notification/NotificationRetry.java
Fixed a couple of typos (plus some trailing whitespaces removed by auto-formatting on save).
> chore: fix some typos detected by cspell

- articles/charts/java-api/charts-getting-started.asciidoc
Fixes the Charts part of https://github.com/vaadin/docs/issues/3687
> Fixed overview link

- articles/testbench/demo-external.asciidoc
- articles/testbench/setup/testbench-license.asciidoc
Fixed Testbench part of https://github.com/vaadin/docs/issues/3687
> Chore: Fixed links

- articles/framework/addons/addons-cval.asciidoc
- articles/framework/addons/addons-downloading.asciidoc
- articles/framework/advanced/advanced-cdi.asciidoc
- articles/framework/articles/ComponentAddonProjectSetupHOWTO.asciidoc
- articles/framework/articles/GettingStartedOnNetBeans.asciidoc
- articles/framework/articles/IntegrationExperiences.asciidoc
- articles/framework/articles/RememberToTheSetTheLocale.asciidoc
- articles/framework/articles/ScalableWebApplications.asciidoc
- articles/framework/articles/UsingVaadinInIBMDomino.asciidoc
- articles/framework/articles/VaadinOnGrailsCreateProjectInIntelliJIDEA.asciidoc
- articles/framework/articles/VaadinTutorialForSwingDevelopers.asciidoc
- articles/framework/articles/WidgetStylingUsingOnlyCSS.asciidoc
- articles/framework/components/components-grid.asciidoc
- articles/framework/datamodel/datamodel-forms.asciidoc
- articles/framework/getting-started/getting-started-package.asciidoc
- articles/framework/installing/installing-toolchain.adoc
- articles/framework/tutorial.asciidoc
Fixing Framework part of https://github.com/vaadin/docs/issues/3687
> Ticket3687 framework part

- articles/designer/designer-designing.asciidoc
- articles/designer/designer-faq.asciidoc
- articles/designer/designer-installing-eclipse.asciidoc
- articles/designer/designer-theme.asciidoc
Fixed designer part of https://github.com/vaadin/docs/issues/3687
> Ticket3687 designer

- articles/bakeryfw8/theming.asciidoc
- articles/index.asciidoc
Fixed Bakery docs for https://github.com/vaadin/docs/issues/3687
> Updated links to current structure

- articles/board/java-api/installing.asciidoc
- articles/board/webcomponents-api/board-basic-use.asciidoc
Fixed Board part of https://github.com/vaadin/docs/issues/3687
> Updated links

- articles/configuration/licenses.adoc
- articles/guide/start/maven-archetype.asciidoc
- articles/guide/step-by-step/running/eclipse.asciidoc
- articles/guide/step-by-step/running/intellij.asciidoc
- articles/guide/step-by-step/running/netbeans.asciidoc
- articles/security/advanced-topics/security-practices.adoc
- articles/styling/custom-theme/style-scopes.adoc
- articles/tools/collaboration/going-to-production.asciidoc
- articles/tools/designer/using-designer/faq.asciidoc
- articles/upgrading/essential-steps/index.adoc
- frontend/demo/upgrade-tool/upgrade-tool.ts
> Chore: fix v23 internal redirect links

- articles/hilla/guides/routing.adoc
- articles/hilla/lit/guides/forms/binder-load.adoc
- articles/hilla/lit/guides/forms/binder-validation.adoc
- articles/hilla/lit/guides/forms/binder.adoc
- articles/hilla/lit/guides/forms/binding-arrays.adoc
- articles/hilla/lit/guides/forms/vaadin-components.adoc
- articles/hilla/lit/start/basics/index.adoc
Updated inline React examples to use self-closing tags where possible, also fixed some indentation and formatting.
> docs: use self-closing tags in inline React examples

- articles/flow/integrations/react.adoc
- articles/getting-started/views/index.adoc
- articles/hilla/lit/guides/forms/binder-load.adoc
- articles/hilla/lit/guides/forms/binder-validation.adoc
- articles/hilla/lit/guides/forms/form-images.adoc
- articles/hilla/lit/guides/forms/form-status-tracking.adoc
- articles/hilla/lit/guides/forms/reference.adoc
- articles/hilla/lit/guides/forms/vaadin-components.adoc
- articles/hilla/lit/guides/reactive-endpoints.adoc
- articles/styling/index.adoc
Fixed some incorrect indentation and a few other minor errors in inline examples.
> docs: fix indentation and some errors in inline TS examples

- src/main/java/com/vaadin/demo/component/customfield/DateRangePicker.java
Improves the example to propagate the invalid state from the custom field to its child components to give better visual feedback.
> docs: improve Flow custom field validation example

- dspublisher/dspublisher-scripts.js
- package-lock.json
- package.json
- tsconfig.json
- vite.dspublisher.ts
- Add Vite config for DSP3
- Bump DSP3 to version `3.0.0-alpha.2`
> feat: add Vite config for dsp

- package.json
- vite.dspublisher.ts
> feat: add Vite config for Astro DSP to v14 branch

- articles/control-center/application-deployment/index.adoc
Fixes https://github.com/vaadin/control-center/issues/693
> Suggest to use a proper tag for app images

- src/main/java/com/vaadin/demo/component/popover/PopoverNotificationPanel.java
> fix: do not add same div multiple times in Popover example

- dspublisher/dspublisher-scripts.js
- src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
Update phases and weights in the DSP scripts
Also, bump the DSP version to `3.0.0-alpha.5` which is now the default for all DSP commands
> chore: update phases and weights in dsp scripts

- articles/_preview-banner.adoc
- articles/control-center/index.adoc
- dspublisher/theme/global.css
This adds an badge and admonition block to indicate that Control Center is a preview feature.
Also adds a small improvement to the existing badges in dark mode.
Fixes https://github.com/vaadin/control-center/issues/725
> [Control Center] Add preview feature indication

- articles/flow/configuration/webpush.adoc
Updates documentation accordingly https://github.com/vaadin/flow/pull/20484.
> chore: Remove WebPush feature flag and use WebPushSubscription

- articles/components/dashboard/index.adoc
- frontend/demo/component/dashboard/dashboard-basic.ts
- frontend/demo/component/dashboard/dashboard-dense-layout.ts
- frontend/demo/component/dashboard/dashboard-internationalisation.ts
- frontend/demo/component/dashboard/dashboard-sections.ts
- frontend/demo/component/dashboard/dashboard-widget-contents.ts
- frontend/demo/component/dashboard/react/dashboard-basic.tsx
- frontend/demo/component/dashboard/react/dashboard-internationalisation.tsx
- frontend/demo/component/dashboard/react/dashboard-sections.tsx
- frontend/demo/component/dashboard/react/dashboard-widget-contents.tsx
- frontend/themes/docs/dashboard.css
- frontend/themes/docs/styles.css
- src/main/java/com/vaadin/demo/component/dashboard/DashboardBasic.java
- src/main/java/com/vaadin/demo/component/dashboard/DashboardInternationalisation.java
- src/main/java/com/vaadin/demo/component/dashboard/DashboardSections.java
- src/main/java/com/vaadin/demo/component/dashboard/DashboardWidgetContents.java
- src/main/resources/vaadin-featureflags.properties
Adds most examples except those for dynamic editing and screen reader announcement.
> docs: basic dashboard examples

- articles/tools/mpr/configuration/limitations.adoc
Fixes: https://github.com/vaadin/multiplatform-runtime/issues/12
> Document TouchKit not working with MPR

- articles/components/dashboard/index.adoc
- frontend/demo/component/dashboard/dashboard-announcements.ts
- frontend/demo/component/dashboard/react/dashboard-announcements.tsx
- src/main/java/com/vaadin/demo/component/dashboard/DashboardAnnouncements.java
Adds example demonstrating how to announce actions in the dashboard to screen readers.
> docs: dashboard announcements example

- articles/control-center/getting-started/configure-installation.adoc
- articles/control-center/getting-started/docker-desktop.adoc
- articles/control-center/getting-started/index.adoc
- articles/control-center/getting-started/local-environment.adoc
This adds some links between pages and other small edits
> [Control center] Cleanup pages for 1.1 release

- articles/components/dashboard/index.adoc
Added a link to https://vaadin.com/forum/t/new-dashboard-component-feedback-welcome/167980 from the feedback admonition on Dashboard page.
> Added link to Forum thread for feedback

- articles/hilla/guides/routing.adoc
> feat: add skipLayouts description to the routing.adoc

- articles/hilla/lit/guides/reactive-endpoints.adoc
> feat: add missing Subscription API descriptions

- frontend/demo/component/grid/react/grid-range-selection.tsx
> fix: update snippet tag to include all relevant code

- articles/flow/integrations/spring/oauth2.adoc
> docs: add documentation for OAuth2 login

- src/main/java/com/vaadin/demo/component/popover/PopoverNotificationPanel.java
Added setModal(true) to Notification Panel Flow sample
> Modality fix to Popover Notification Panel sample

- articles/styling/legacy/material-theme/color.adoc
- articles/styling/legacy/material-theme/index.adoc
- articles/styling/legacy/material-theme/typography.adoc
Depends on https://github.com/vaadin/web-components/pull/8673 and https://github.com/vaadin/flow-components/pull/7111
> chore: mark the Material theme as deprecated

- articles/control-center/application-deployment/index.adoc
Add mention and description of the environment variable management feature in Control Center.
Fixes https://github.com/vaadin/control-center/issues/843
> docs: [Control Center] add description of environment variable management feature

- articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Update MTK Analyzer version in docs.
> Update MTK Analyzer version to 2.0.17

- articles/flow/binding-data/field.adoc
Fix a typo in AbstractField example
> AbstractField setPresentationValue code example was using the wrong argument

- articles/control-center/identity-management/index.adoc
- articles/control-center/index.adoc
- dspublisher/theme/global.css
Some authentication features provided by Control Center are premium features. This PR marks this features as commercial features. Specifically:
Fixes https://github.com/vaadin/control-center/issues/880
> docs: mark Control center commercial authentication methods

- articles/building-apps/forms-data/replace-h2.adoc
- articles/getting-started/walk-through.adoc
Merge after https://github.com/vaadin/walking-skeleton/pull/45 has been merged.
> Update guide to use service connections

- articles/getting-started/index.adoc
- articles/getting-started/start/index.adoc
This PR clarifies what a walking skeleton is.
Addresses https://github.com/vaadin/walking-skeleton/issues/36
> Clarify walking skeleton

- articles/components/message-list/index.adoc
- frontend/demo/component/messages/message-list-ai-chat.ts
- frontend/demo/component/messages/react/message-list-ai-chat.tsx
- src/main/java/com/vaadin/demo/component/messages/MessageListAiChat.java
Fixes https://github.com/vaadin/docs/issues/4321
> docs: announcements in message-list chat example

- articles/flow/security/advanced-topics/external-configuration.adoc
In spring boot apps, propery values can be encrypted inline with Jasypt. This update demonstrates simple steps to do that.
> Add another approach - to encrypt property values with Jasypt

- articles/flow/advanced/downloads.adoc
> Add discussion thread to downloads.adoc

- src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java
- src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDividers.java
- src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuHierarchical.java
- src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java
- src/main/java/com/vaadin/demo/component/grid/GridContextMenuExample.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarDividers.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarDropDown.java
- src/main/java/com/vaadin/demo/component/menubar/MenuBarIcons.java
... and tiny code polishing. Based on comment by Jan Heinrich 🏅
> docs: use addSeparator for adding dividers

- dspublisher/theme/global.css
- dspublisher/theme/init-browser.ts
- Switch from old Google font to the new NB International Pro font
- Switch font weight used with headings from semi-bold to normal
> V7: Use new Vaadin font NB International Pro

- articles/components/upload/styling.adoc
See https://github.com/vaadin/web-components/pull/10060
> docs: remove upload file parts dropped in V25
